### ISSUE TITLE
AppImage tsMuxeR not found

### ISSUE THREAD

**Issue by darekpro** [justdan96/tsMuxer#103]
I have again problem with build tsmuxer from arch repo and.... I tried run AppImage lnx-nightly-2020-01-02--01-10-53.zip
and I have this error:
![Zrzut ekranu z 2020-01-02 13-57-57](https://user-images.githubusercontent.com/58607093/71668130-fc89eb80-2d67-11ea-9544-4bc4f208dc95.png)

and this is from arch repo
![71666581-c77a9a80-2d61-11ea-95ac-80d4234d2eab](https://user-images.githubusercontent.com/58607093/71668148-0f9cbb80-2d68-11ea-840b-4812269856b2.png)

**Comment by justdan96** [comment]
Can you check the name of the main tsMuxer executable? Should be either tsMuxeR or tsmuxer. 

With the AppImage I'll have to check that tonight.

**Comment by darekpro** [comment]
Yes name was /usr/bin/tsmuxer I change to /usr/bin/tsMuxeR but still there is a problem

**Comment by justdan96** [comment]
Is the GUI AppImage in the same folder as the CLI?

**Comment by darekpro** [comment]
yes ofc 
![Zrzut ekranu z 2020-01-02 15-07-29](https://user-images.githubusercontent.com/58607093/71670826-82f6fb00-2d71-11ea-9946-794a235d2978.png)

**Comment by justdan96** [comment]
Okay I'll have to test this once I get home, I'm not sure why it isn't recognising the executable
