### ISSUE TITLE
First MPLS / M2TS and Chapters

### ISSUE THREAD

**Issue by zamengo** [justdan96/tsMuxer#104]
I use the w64-nightly-2020-01-02--01-10-53 and have this errors When use "UHD Blu-ray folder":

- First MPLS dont respect the option after remux.
- First M2TS dont respect the option after remux.
- Chapters dont respect the list, put only "00:00:00.000" after remux.

**Comment by jcdr428** [comment]
@justdan96 @xavery straightforward fix. Could you please merge the push #106 asap for testing (I don't have qt5 installed so can't check whether the issue is fully solved).

**Comment by justdan96** [comment]
#106 has now been merged and will be a part of the next nightly build.

**Comment by zamengo** [comment]
Nice one! Works fine now!
