### ISSUE TITLE
Incorrect I_end values in ClipInf CPI EP Entries with UHD

### ISSUE THREAD

**Issue by jcdr428** [justdan96/tsMuxer#107]
tsPacket.cpp lines 965-980 define the threshold values for I-frame size to increment I_end.
These values seem to be extracted from the Blu-ray patents (eg US 2009/0016703 A1).

Until the threshold values for Transfer Rate > 60000000 (ie for UHD Blu-ray) are known, the I_end values above 1 recorded in the ClipInf CPI EP Entries are likely to be incorrect.

**Comment by jcdr428** [comment]
Bug solved by commit #112.
A big Thanks to tymoxa for his invaluable help on UHD blu-ray specs.

**Comment by xavery** [comment]
#112 is now merged, closing.
