### ISSUE TITLE
Correctly Handle FPS Detection

### ISSUE THREAD

**Issue by justdan96** [justdan96/tsMuxer#109]
Can be tested using the following file:
https://mega.nz/#!NAtw1RqK!uQF9Uqn33KUCwe5fG66ojAJAkOv1bPNhKkcHQTSuceQ

It is a HEVC file, 2160p, 60 FPS, AAC audio. The FPS isn't detected correctly and 60FPS isn't an option in the "change framerate" drop-down.

![tsMuxerGUI-60FPS](https://user-images.githubusercontent.com/503722/71771655-c353a600-2f36-11ea-81db-146229fa1b14.png)

Attempting to mux anyway will result in the following output:
```
tsMuxeR version 2.6.15. github.com/justdan96/tsMuxer
This HEVC stream doesn't contain fps value. Muxing fps is absent too. Set muxing FPS to default 25.0 value.
HEVC stream doesn't contain fps field. Muxing fps=25
Decoding AAC stream (track 2): Sample Rate: 48KHz  Channels: 6
B-pyramid level 1 detected. Shift DTS to 2 frames
Processed 9843 video frames
Flushing write buffer
Mux successful complete
Muxing time: 2 sec
```

This appears to not just be affecting 60FPS files, will do some more testing.

**Comment by jcdr428** [comment]
@justdan96 FPS can be either in VPS or SPS nal. tsMuxer currently reads FPS only from the VPS.
The [commit](https://github.com/jcdr428/tsMuxer/commit/48c6d5b2e3775d195b7e83fbb02f1cdcc83689d4) is ready but I need pull request #94 to be merged to avoid conflicts.

**Comment by justdan96** [comment]
#94 merged

**Comment by jcdr428** [comment]
@justdan96 I've pushed the commit #113. And the fps is also detected by the GUI :) :) :)

**Comment by justdan96** [comment]
#113 merged

**Comment by jcdr428** [comment]
FPS (and other HEVC stream info) detection in the GUI now fixed with #115.

My, that was a stupid bug, it took me hours to find this missing line...

**Comment by xavery** [comment]
> My, that was a stupid bug, it took me hours to find this missing line...
tsMuxer is unfortunately full of stringly-typed code like that. I expect issues like these to crop up every time support for a particular audio/video/subtitle type is added or somehow modified, as there is naturally always a place that you're going to miss.

**Comment by jcdr428** [comment]
Indeed... Anyway, push merged, issue #109 can be closed. It might have fixed issue #89 also, let's see what damkalan-uth will report after next nightly build.

**Comment by darekpro** [comment]
This is latest build from arch repo, fps not is auto detected and I need set manual fps for video.

![Zrzut ekranu z 2020-01-07 20-23-33](https://user-images.githubusercontent.com/58607093/71922604-8d5b2f80-318b-11ea-9f0d-45ec95656599.png)

**Comment by jcdr428** [comment]
@darekpro is it the latest build from https://github.com/justdan96/tsMuxer/actions (built one hour ago) ?

**Comment by darekpro** [comment]
Not exactly from here but from from arch repo but yes Im sure I use latest version.

**Comment by jcdr428** [comment]
@darkrepo please keep on reporting on issue #89. This issue #109 was open for incorrect fps detection for HEVC and is now closed.
