### ISSUE TITLE
Wrong Dialog opened when "Browsing" for the output UHD Blu-ray folder (tsMuxerGUI)

### ISSUE THREAD

**Issue by jeffkiku2019** [justdan96/tsMuxer#117]
When "UHD Blu-ray folder" is selected as the Output type and the Browse button is clicked, a "Select File name" dialog is presented instead of the "Select Folder" dialog. This makes it impossible to select an output folder for the UHD Blu-ray mux. You have to cancel out of the dialog and manually enter the entire path to the folder in the "folder" field.

**Comment by jcdr428** [comment]
Commit #119 should fix this.

**Comment by justdan96** [comment]
Bug should have been fixed by PR #119 - can you please check and confirm on latest nightly?

**Comment by jcdr428** [comment]
@justdan96 the UHD buttons are not there anymore, they have been replaced by the V3 option in merge #120. So yes this bug is fixed ;)

**Comment by jeffkiku2019** [comment]
I've confirmed that the nightly release from 2020-01-11 has eliminated this problem.  Thanks for the quick response.
