### ISSUE TITLE
Stuttering Video 

### ISSUE THREAD

**Issue by Liv77** [justdan96/tsMuxer#118]
what is the main output needed to export UHD blu-ray folder for audio and video ? I have one 4K video that is ts file? muxing is successful its just that the video stutters and then its fine again.
Here is the video image below. I'm using the latest update tsmuxer for mac.
![UHD Video](https://user-images.githubusercontent.com/59346428/71946499-0d879200-3198-11ea-8298-06457f5d94e5.png)

**Comment by jcdr428** [comment]
@Liv77 please provide link to download the related TS sample file, thanks.

**Comment by Liv77** [comment]
This is where I got the video from but i had to download the file  
 and this is the link but i don't see the video in there.  https://www.fshare.vn/folder/I8BLSVT5Y7T9?token=1578530151


 http://www.hdvietnam.com/threads/the-thao-roland-garros-2019-final-thiem-vs-nadal-2160p-giai-quan-vot-phap-mo-rong-chung-ket.1530450/

Here is more info about the video

General
ID                                       : 16 (0x10)
Complete name                            : /Users/afleszar/Desktop/2019.06.09.Roland Garros 2019.FINAL.Thiem vs Nadal.2160p.RUS.ENG.ts
Format                                   : MPEG-TS
File size                                : 31.3 GiB
Duration                                 : 3h 38mn
Overall bit rate mode                    : Variable
Overall bit rate                         : 20.5 Mbps

Video
ID                                       : 5889 (0x1701)
Menu ID                                  : 18001 (0x4651)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L5.1@Main
Codec ID                                 : 36
Duration                                 : 3h 38mn
Bit rate                                 : 19.1 Mbps
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 50.000 fps
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.046
Stream size                              : 29.2 GiB (93%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio #1
ID                                       : 5890 (0x1702)
Menu ID                                  : 18001 (0x4651)
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 2
Codec ID                                 : 4
Duration                                 : 3h 38mn
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 KHz
Frame rate                               : 41.667 fps (1152 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -8ms
Stream size                              : 300 MiB (1%)
Language                                 : std
Language, more info                      : Clean effects

Audio #2
ID                                       : 5891 (0x1703)
Menu ID                                  : 18001 (0x4651)
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 2
Codec ID                                 : 4
Duration                                 : 3h 38mn
Bit rate mode                            : Constant
Bit rate                                 : 192 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 KHz
Frame rate                               : 41.667 fps (1152 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -8ms
Stream size                              : 300 MiB (1%)
Language                                 : English
Language, more info                      : Clean effects

Menu
ID                                       : 5888 (0x1700)
Menu ID                                  : 18001 (0x4651)
Duration                                 : 3h 38mn
List                                     : 5889 (0x1701) (HEVC) / 5890 (0x1702) (MPEG Audio, std) / 5891 (0x1703) (MPEG Audio, English)
Language                                 :  / std / English
Service name                             : DVR-UHD  
Service provider                         : HS    
Service type                             : digital television

and here is attachment of the video

**Comment by jcdr428** [comment]
@Liv77 if you have the video, just isolate and cut the stuttering part of the m2ts with an hex editor (eg HxD) to reduce the file size, upload to any file sharing service and provide the link. Without the sample to analyse the stream we cannot do anything.

**Comment by justdan96** [comment]
@Liv77 Sorry I had to edit your comment, we can't link to TV/film sharing websites. 

As you're on Mac you can use the head command to copy only the first 19MB of the file:
```
head -c 19M "2019.06.09.Roland Garros 2019.FINAL.Thiem vs Nadal.2160p.RUS.ENG.ts" > small.ts
```

**Comment by Liv77** [comment]
so i'm uploading the entire file in dropbox , would that work so you can have access to? My Team name is Wildcats and email is ofleszar7@gmail.com

**Comment by justdan96** [comment]
We don't really need the whole file, just the parts that stutter.

**Comment by Liv77** [comment]
it goes on and off the whole video so i can't really detect which parts? do you know a free store that i can upload videos that are large file at least 30 GB for file sharing. dropbox won't work.

**Comment by Liv77** [comment]
Im going to upload the video in HighTail its the same as email ofleszar7@gmail.com as above and Team name is BluCourt. How should I invite you to see the video?

**Comment by Liv77** [comment]
I uploaded the whole video on https://spaces.hightail.com/dashboard/news its Videos and in Space Dashboard which is the same title and the file can be downloaded. I added it on Jan 11.

**Comment by Liv77** [comment]
Here is the link https://spaces.hightail.com/space/rAXSTd3MRR

**Comment by Liv77** [comment]
What happened to UHD Blu Ray folder and and UHD Blu ray ISO for output is it gone i just downloaded the latest version from Download tsMuxeR 2.6.15 2020-01-11 Nightly Mac ?

**Comment by justdan96** [comment]
Those settings have been moved to the Blu-Ray tab.

**Comment by Liv77** [comment]
![TSmuxer](https://user-images.githubusercontent.com/59346428/72208401-2631c980-3470-11ea-81e5-1945e7ed3bc0.png)
Hi I don't see it under blu ray tab the UHD

**Comment by jcdr428** [comment]
@Liv77 Please keep this thread for the "stittering video" issue.
The option is "BD-ROM V3 format". You need to select it only for AVC, the V3 option is selected automatically if HEVC is detected during the mux.

**Comment by Liv77** [comment]
Hey justdan96 i just uploaded the same one it shorted to 5 GB its the same link

**Comment by justdan96** [comment]
Is it the TS file or the original? If you have the original we can run it through tsMuxer with the same settings and test if we get corrupted output like you.

**Comment by Liv77** [comment]
its the same video TS file original,  i just used trimmed it down. can you test it for me and send me a picture on tsmuxer for UHD to see how you do it so i can do the same thing to see if it works?

**Comment by justdan96** [comment]
Sorry we would need the original file before you have run it through tsMuxer

**Comment by Liv77** [comment]
The original file is the same one  in High Tail just in 31GB same one 
2019.06.09.Roland Garros 2019.FINAL.Thiem vs Nadal.2160p.RUS.ENG.ts
01/10/2020 | 10:12 pm | 31 GB that you can download

**Comment by Liv77** [comment]
Here is the link https://spaces.hightail.com/space/rAXSTd3MRR/files/fi-c5b532ea-71b0-4ad7-a9be-fc5840602534/fv-3cd426f2-300c-4b08-bdd9-5ef96fde98a7/2019.06.09.Roland%20Garros%202019.FINAL.Thiem%20vs%20Nadal.2160p.RUS.ENG.ts

**Comment by justdan96** [comment]
I have the file, I will try to mux it myself and see if I get odd output.

**Comment by justdan96** [comment]
Nothing in the first 3 1/2 minutes after muxing in the same way as you. Would you be able to give timestamps of when you are seeing stuttering? Alternatively you could set the [logging level to debug in VLC](https://www.dedoimedo.com/computers/vlc-secrets-logging.html) and then just leave the file playing and hope the stuttering is put into the log file.
