### ISSUE TITLE
Enhancement: add hash of tsMuxer latest commit after version number in console

### ISSUE THREAD

**Issue by jcdr428** [justdan96/tsMuxer#127]
It would allow to be certain of which version users have used when reporting bugs. Currently it is kind of a mess...

@xavery, I'm sure this is something you know how to implement ?

**Comment by justdan96** [comment]
I think I have a decent idea on how to accomplish this.

**Comment by xavery** [comment]
@justdan96 I have a solution that's practically ready and would like to submit it later today. Let me know if that's OK.

**Comment by justdan96** [comment]
Yeah that is fine, I can see how you approached the problem and compare notes 😁
