### ISSUE TITLE
Bad looking subtitle font - linux

### ISSUE THREAD

**Issue by darekpro** [justdan96/tsMuxer#133]
Hello
I noticed bad looking font in linux system, no shadows and strange space between letters.
Thank for support.

![1_00:01:05 346](https://user-images.githubusercontent.com/58607093/72203767-5a0cef00-3470-11ea-9fce-7ac825f26b20.png)
![1_00:01:05 650](https://user-images.githubusercontent.com/58607093/72203768-5bd6b280-3470-11ea-886e-c5358851b55b.png)
![1_00:01:59 992](https://user-images.githubusercontent.com/58607093/72203771-5d07df80-3470-11ea-8aac-165d03502949.png)
![1_00:02:00 878](https://user-images.githubusercontent.com/58607093/72203772-5e390c80-3470-11ea-94b9-4d7fab4c1dc3.png)

**Comment by jcdr428** [comment]
@darekpro yes this is the same for Windows. We might look at this in the future, in the meantime you can convert your srt to BD sup with [easySUP](https://www.videohelp.com/software/easySUP) hwich works very well.

**Comment by justdan96** [comment]
Is this an issue with the kerning or something? Can we try it out with a few different fonts to check it is an issue with the renderer?

**Comment by jcdr428** [comment]
@justdan96 Windows version doesn't use freetype, but seems to me that in textSubtitlesRenderFT.cpp :
line 588 `pen.x += face->glyph->advance.x >> 6;`
line 593 `mSize->cx = pen.x + face->glyph->bitmap_left;`

the glyph left side bearing `bitmap_left` is already included in `advance.x` so is added twice.
Try change to `mSize->cx = pen.x;`
Same for line 540.

**Comment by jcdr428** [comment]
@darekpro please try my latest build https://github.com/jcdr428/tsMuxer/actions and report.
I haven't tried it as I am on Windows.

**Comment by darekpro** [comment]
Hmm I don't see any difference still problem with space between letters, no shadow and bad looking edges
![1_00:01:05 142](https://user-images.githubusercontent.com/58607093/72618045-90e47880-393a-11ea-95d6-d6bf56988168.png)

**Comment by darekpro** [comment]
Helvetica font 
![1_00:01:04 979](https://user-images.githubusercontent.com/58607093/72618357-326bca00-393b-11ea-9073-30126d2c5b70.png)

**Comment by justdan96** [comment]
I wonder what happens if you use a fixed width font like GNU Freefont Mono?

**Comment by jcdr428** [comment]
@darekpro thanks. Could you please try latest build (a169bb3) https://github.com/jcdr428/tsMuxer/actions

**Comment by darekpro** [comment]
![Zrzut ekranu z 2020-01-17 15-50-30](https://user-images.githubusercontent.com/58607093/72621154-ffc4d000-3940-11ea-813a-e00e6bbe655b.png)
![Zrzut ekranu z 2020-01-17 15-52-00](https://user-images.githubusercontent.com/58607093/72621264-34388c00-3941-11ea-802e-f4bdd3d658ae.png)

**Comment by jcdr428** [comment]
@darekpro this is the latest build 88b9561 ?  It was created only 13 min. ago.

**Comment by darekpro** [comment]
No no this is screen with mono fonts :)

**Comment by darekpro** [comment]
@jcdr428 you know what.. I use pamac to rebuild tsmuxer and you change not main repo right? I dont know how to manual build .. ;/

**Comment by justdan96** [comment]
You could edit the PKGBUILD yourself and then run makepkg - or try the binary made in output of the GitHub Actions on @jcdr428's repo.

**Comment by darekpro** [comment]
How :) ?
![Zrzut ekranu z 2020-01-17 16-19-10](https://user-images.githubusercontent.com/58607093/72623214-fe95a200-3944-11ea-9387-19ddcc285049.png)

**Comment by jcdr428** [comment]
So all these pictures were not my build ?
Just go to https://github.com/jcdr428/tsMuxer/actions , click on the top "Build for linux", click on "Artifacts" at the top left, download "tsMuxer"

**Comment by darekpro** [comment]
Yes sorry... I donwloaded pack from here https://bintray.com/justdan96/tsMuxer/tsMuxerGUI-Nightly/2020-01-17--01-10-08#files and replaced file from https://github.com/jcdr428/tsMuxer/actions

![1_00:01:04 940](https://user-images.githubusercontent.com/58607093/72624338-0e15ea80-3947-11ea-8995-93c127c5e0f1.png)

**Comment by jcdr428** [comment]
@darekpro Just to be sure... this is the build https://github.com/jcdr428/tsMuxer/suites/406472859/artifacts/1185098

**Comment by darekpro** [comment]
Yes :)

**Comment by jcdr428** [comment]
@darekpro new try... https://github.com/jcdr428/tsMuxer/suites/417185880/artifacts/1305874

**Comment by darekpro** [comment]
@jcdr428 
Hi, nothing has changed.

**Comment by darekpro** [comment]
progress :)
![72624338-0e15ea80-3947-11ea-8995-93c127c5e0f1](https://user-images.githubusercontent.com/58607093/73021939-e207d700-3e28-11ea-9258-2c141ec9a9e4.png)

**Comment by jcdr428** [comment]
@darekpro what's the name of these fonts giving bad results ?

**Comment by darekpro** [comment]
I use Helvetica looks good 
![1_00:01:08 354](https://user-images.githubusercontent.com/58607093/73023675-542deb00-3e2c-11ea-95b6-539f5d89a11b.png)

**Comment by jcdr428** [comment]
@darekpro so it is not perfect but definitely looking better ;)

**Comment by jcdr428** [comment]
@darekpro hopefully with this one, it will look even better https://github.com/jcdr428/tsMuxer/suites/417290642/artifacts/1307079

**Comment by darekpro** [comment]
Now much better! so one problem less but still no shadows and I noticed also problem with color change:
![Zrzut ekranu z 2020-01-23 22-30-57](https://user-images.githubusercontent.com/58607093/73025516-07e4aa00-3e30-11ea-87d1-48165a59e89e.png)
![1_00:01:05 607](https://user-images.githubusercontent.com/58607093/73025527-0adf9a80-3e30-11ea-86c6-b3e49286e9ad.png)

**Comment by justdan96** [comment]
Nice to see some progress!

**Comment by jcdr428** [comment]
@darekpro what "Color" number have you entered in your example ? If you have entered e.g. `#b1b2b3b4,` the first three digits `b1 b2 b3` are the Red Green Blue values, and the last one `b4` is the transparency -which should remain `ff` if you want 100% opacity.

**Comment by darekpro** [comment]
I don't enter numbers i just use slide bar like on screen
![73025516-07e4aa00-3e30-11ea-87d1-48165a59e89e](https://user-images.githubusercontent.com/58607093/73058714-79564400-3e94-11ea-9a63-95c5f977726d.png)

**Comment by darekpro** [comment]
![Zrzut ekranu z 2020-01-24 10-32-24](https://user-images.githubusercontent.com/58607093/73058863-d18d4600-3e94-11ea-9c94-73afc0a43713.png)
check this one
![Zrzut ekranu z 2020-01-24 10-32-32](https://user-images.githubusercontent.com/58607093/73058872-d3efa000-3e94-11ea-9f72-c99ef1316e86.png)
![1_00:01:11 320](https://user-images.githubusercontent.com/58607093/73058879-d651fa00-3e94-11ea-95a5-490a59a1e4f8.png)

**Comment by justdan96** [comment]
It looks like to enable transparency for QColorDialog we need to use QColorDialog::ShowAlphaChannel. 

So for that I believe we could change this line:
https://github.com/justdan96/tsMuxer/blob/0702a4b353860830f4a6f42653a947b6c39d5381/tsMuxerGUI/tsmuxerwindow.cpp#L1884

To:
```
color = QColorDialog::getColor(color, this, QString("Select Color"), QColorDialog::ShowAlphaChannel);
```

**Comment by jcdr428** [comment]
@justdan96 actually there is already transparency on the subtitles. But the transparency is applied on the whole subtitle instead of being applied on the outer border only.

**Comment by justdan96** [comment]
Oh I thought the alpha slider was missing from the dialog.

**Comment by justdan96** [comment]
Should we leave this one open to track remaining issues with subtitles or is this a "good enough" fix?

**Comment by jcdr428** [comment]
@justdan96 The fix has solved the irregular spacing between letters. It hasn't solved the lack of border or transparency problem raised by darekpro.
Maybe we can close this issue and open a specific one for border/transparency.

**Comment by justdan96** [comment]
Will close this one, if anyone is still concerned they can create a new issue for the border and transparency visual.
