### ISSUE TITLE
Bug: Incorrect LPCM length in mux + WAV header in demux

### ISSUE THREAD

**Issue by jcdr428** [justdan96/tsMuxer#136]
Cf. [https://forum.doom9.org/showthread.php?p=1893304#post1893304](https://forum.doom9.org/showthread.php?p=1893304#post1893304) :

`[tsMuxer] add garbage at end and create wav header incorrect (data not multiple of channels*bytedepth).`

I have verified that the bug is still current with latest nightly build.

**Comment by jcdr428** [comment]
As noted in #137, tsMuxer adds zeros at the end of the last block to align with frame length of 5 ms.
This is not a bug.

**Comment by justdan96** [comment]
Can you confirm that this issue can be closed?

**Comment by jcdr428** [comment]
@justdan96 incorrect header length for wav64 is fixed by #137. The issue can be closed when the push is merged.
