### ISSUE TITLE
C++14 support

### ISSUE THREAD

**Issue by xavery** [justdan96/tsMuxer#14]
What's holding the project back from requiring C++14 support?
All the recommended compilers in README.md support it :

- The default GCC version in Debian 10 is [8.3.0](https://packages.debian.org/buster/g++), which even [supports C++17](https://gcc.gnu.org/projects/cxx-status.html#cxx17).
- Ubuntu 19.04 also ships [GCC 8.3.0](https://packages.ubuntu.com/disco/devel/g++).
- MSYS2 has shipped [GCC 9.1.0](https://github.com/msys2/MSYS2-packages/blob/master/gcc/PKGBUILD#L10) since 4th of July this year, with the previous major version being [7.3.0](https://github.com/msys2/MSYS2-packages/commit/aa64260bff000567f30b453720cb80ae9fb06dbd#diff-1ea3a29c6344ec07af27b8beec71d498), which also supported C++17.
- MSVC 2017 15.0 (so, the first public release) supports [all C++14 features](https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2017).

The lowest common denominator thus seems to be C++14.

**Comment by justdan96** [comment]
I suspect there's no specific reason, I'd have to test in the build pipeline containers if there's any issues. Going forward I'd like all builds to be run through Docker, to ensure consistent results.

**Comment by justdan96** [comment]
Ubuntu 19:
```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
```

MXE:
```
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
```

osxcross:
```
-- The C compiler identification is Clang 8.0.0
-- The CXX compiler identification is Clang 8.0.0
```

So it looks like there is coverage for C++14 for all the compilers in use.

**Comment by justdan96** [comment]
Simply setting `set(CMAKE_CXX_STANDARD 14)` and doing the builds mentioned above results in successful compilation. I think we should be find to set this new value - unless you can think of any reason not to?

**Comment by xavery** [comment]
I really don't, go ahead!
