### ISSUE TITLE
TsMuxer enable 50fps

### ISSUE THREAD

**Issue by mariustrifan83** [justdan96/tsMuxer#142]
I'm using TsMuxer and want to add native 50 fps to Change fps It is available 24, 25, 30

**Comment by justdan96** [comment]
Should probably add 60fps too

**Comment by mariustrifan83** [comment]
Use to create bluray full hd 50p video. I'm a wedding cameraman

**Comment by xavery** [comment]
> Use to create bluray full hd 50p video. I'm a wedding cameraman

Nice to see non-programmers not being afraid to report issues on GitHub.

**Comment by mariustrifan83** [comment]
Thanks for the help and the changes made. I am now happy that I can make BD-Video with the latest TSMuxer version.

https://dl.bintray.com/justdan96/tsMuxer/:mac-nightly-2020-01-20--01-09-45.zip
