### ISSUE TITLE
UHD Setting and Audio on latest TSMuxer GUI git- 146be40

### ISSUE THREAD

**Issue by Liv77** [justdan96/tsMuxer#152]
I would like to know how to set up UHD  video setting in latest TS muxer in blu ray tab in options and output in mac? Also what should the audio be set to as well to play on UHD players? Can this vary on different video formats like mkv vs ts or mp4 4K videos?
![TS Muxer for mac](https://user-images.githubusercontent.com/59346428/72690542-566e0d80-3aeb-11ea-9603-a876791ea3b4.png)

**Comment by FilipeAmadeuO** [comment]
Set BD-ROM V3 format checkbox and you will have UHD compatible structure. 
If you import HEVC it will be set automatically

**Comment by Liv77** [comment]
what about for output? which folder or iso

**Comment by justdan96** [comment]
That's in the output section

**Comment by Liv77** [comment]
should I select Blu-ray iso , Blu-ray Folder or AVCHD for UHD or can it be any?

**Comment by Liv77** [comment]
I got it
