### ISSUE TITLE
Enhancement: ability to detect language of audio/subtitle from BD folder

### ISSUE THREAD

**Issue by darekpro** [justdan96/tsMuxer#166]
Will be nice to see this enhancement in future 
"ability to detect language of audio/subtitle from BD folder"

**Comment by jcdr428** [comment]
@darekpro could you please clarify ? When a Blu-ray .m2ts is added to tsMuxer, language of audio/subtitle is already detected.

**Comment by darekpro** [comment]
Not for me
https://i.imgur.com/q8IWHE7.png

**Comment by darekpro** [comment]
and mkvtoolnix 
https://i.imgur.com/TMgiuvb.png

**Comment by jcdr428** [comment]
@darekpro please zip all files and send link. In STREAM folder only one file, the first 20MB of 00003.m2ts (in Linux cut with `head -c 19M 00003.m2ts > 00003cut.m2ts`)

**Comment by darekpro** [comment]
[Shadow (2018).zip](https://github.com/justdan96/tsMuxer/files/4362592/Shadow.2018.zip)

:)

**Comment by jcdr428** [comment]
I can't help, no problems on Windows. @xavery @justdan96 do you have the same problem as @darekpro on Linux ?

![5e71110](https://user-images.githubusercontent.com/56721609/77228367-76738900-6b8f-11ea-88a2-dc18deca8a91.jpg)

**Comment by darekpro** [comment]
I checked on Windows and it's working but I checked also another notebook with linux and there is the same problem.

**Comment by xavery** [comment]
As usual in the "works on Windows, doesn't on anything else" genre, file name case sensitivity was the culprit.

**Comment by darekpro** [comment]
Thank you!
