### ISSUE TITLE
Can't find ttf file for font Arial

### ISSUE THREAD

**Issue by bouchnouk** [justdan96/tsMuxer#170]
Got an error code 254 with error message "Can't find ttf file for font Arial" on macOS 10.15.2 (Catalina) when I press "Start muxing" button. The font Gungseouche.ttf is not on my machine. However, the font AppleMyungjo.ttf is on the library/fonts directory. I tried to remove/rename the font but, as it is considered a "system font", I can't. I tried to deactivate the font but Tsmuxer still doesn't work. Everything else seems to be ok.

I know I could use the Windows version but, since a macOS version is available, why not use it? Is it a bug?

Thanks in advance.
<img width="596" alt="2020-02-01_22-44-00" src="https://user-images.githubusercontent.com/20449937/73602581-7cac9800-4544-11ea-837c-8e1d2baead9f.png">

**Comment by jcdr428** [comment]
@bouchnouk could you please copy your .meta file.

**Comment by justdan96** [comment]
Check in the subtitles font dialog. You should be able to select an alternative.

The error itself I had a similar sounding issue on Linux where a font family or OTF font was selected - it has to be specifically a TTF font. I started looking into providing a suitable default per platform but decided against it in the end.

**Comment by bouchnouk** [comment]
Thank you. The asked metafile is joined. I tried several fonts (Helvetica, Monica, etc. for example) and the same error code is shown. I also tried with other files and the result is unfortunately the same. The selected fonts are displayed in another window under the "All fonts" category. I don't know what to do next.

<img width="445" alt="2020-02-02_19-19-49" src="https://user-images.githubusercontent.com/20449937/73617867-0619a400-45f1-11ea-861b-3044016648d4.png">


[The.Irishman.2019.1080p.NF.WEB-DL.DDP5.1.Atmos.H.265.HDR-Pawel2006.meta.zip](https://github.com/justdan96/tsMuxer/files/4145748/The.Irishman.2019.1080p.NF.WEB-DL.DDP5.1.Atmos.H.265.HDR-Pawel2006.meta.zip)
<img width="596" alt="2020-02-02_19-14-51" src="https://user-images.githubusercontent.com/20449937/73617815-960b1e00-45f0-11ea-8199-0c9c4202ae7f.png">

**Comment by justdan96** [comment]
What fonts are listed if you run this in a terminal:
```
ls /System/Library/Fonts/*.ttf
```
You can also try installing the GNU Freefont TTF files from http://ftp.gnu.org/gnu/freefont/ into User > Library > Fonts.

**Comment by bouchnouk** [comment]
Thank you. Here is the result of the command: 
/Library/Fonts/Arial Unicode.ttf
/Library/Fonts/MyriadWebPro-Bold.ttf
/Library/Fonts/MyriadWebPro-Condensed.ttf
/Library/Fonts/MyriadWebPro-CondensedIt.ttf
/Library/Fonts/MyriadWebPro-Italic.ttf
/Library/Fonts/MyriadWebPro.ttf
/Library/Fonts/OpenSans-Bold.ttf
/Library/Fonts/OpenSans-BoldItalic.ttf
/Library/Fonts/OpenSans-ExtraBold.ttf
/Library/Fonts/OpenSans-ExtraBoldItalic.ttf
/Library/Fonts/OpenSans-Italic.ttf
/Library/Fonts/OpenSans-Light.ttf
/Library/Fonts/OpenSans-LightItalic.ttf
/Library/Fonts/OpenSans-Regular.ttf
/Library/Fonts/OpenSans-Semibold.ttf
/Library/Fonts/OpenSans-SemiboldItalic.ttf

However, when I look with Finder, there is much more fonts available. 
<img width="1473" alt="2020-02-03_11-43-45" src="https://user-images.githubusercontent.com/20449937/73672240-8801df80-467a-11ea-88d7-88b97e7441a4.png">

I'll give a try with the GNU Freefont TTF files.

**Comment by justdan96** [comment]
From the command output you should be able to use OpenSans font, if you could try that and let us know if it works.

**Comment by bouchnouk** [comment]
Thank you. I can confirm that it works with OpenSans font.

**Comment by justdan96** [comment]
There's a wider question related to this - if Freetype supports multiple font formats why do we only use TTF? I might look into alternative ways of supporting fonts, to make issues like this one obsolete.

**Comment by justdan96** [comment]
I think we can use this to update the documentation in the short term and look at better solutions for looking up font files in the long term.

Are you okay for the issue to be closed now?

**Comment by bouchnouk** [comment]
Ok. I agree with that. The issue can be closed.

Thank you.
