### ISSUE TITLE
No HDR after remux Terminator 2 (Tag der Abrechnung )1991 UHD

### ISSUE THREAD

**Issue by cob66** [justdan96/tsMuxer#187]
No HDR after remux Terminator 2 (Tag der Abrechnung )1991 UHD (German ver.)

**Comment by xavery** [comment]
Could you provide some more details? Screenshots, console outputs? What did you get, what did you expect to get? How did you observe the bug?

**Comment by jcdr428** [comment]
@cob66 please also upload the tsMuxer mpls and clpi, and if possible a link for a m2ts sample containing HDR, 20 to 50 MB (!! not the whole movie contains HDR)

**Comment by jcdr428** [comment]
@cob66 Please try [this fork](https://github.com/jcdr428/tsMuxer/suites/445996907/artifacts/1681058) and confirm whether the problem has been fixed, thanks.

**Comment by cob66** [comment]
Cześć, może łatwiej po polsku? 😊

Zwróciłem uwagę, że tylko konkretnie ten tytuł ma problem z HDR10.

Po remuksie znika flaga HDR i kolory są nieprawidłowe

Pozdrawiam, Artur

**Comment by xavery** [comment]
Arturze, chętnie, ale na GitHubie musimy trzymać się angielskiego. :-) Dzięki za zgłoszenie, w miarę możliwości wypróbuj forka, bo @jcdr428 jest tutaj specem od wszelkich rzeczy związanych z HDR, HEVC, i całą tą resztą.

For our international readers : Artur reports that this particular title has problems with HDR10, and the HDR flag disappears after remuxing, resulting in invalid colours in the video stream.

**Comment by jcdr428** [comment]
Fixed with proposed merge #189.

**Comment by cob66** [comment]
> @cob66 Please try [this fork](https://github.com/jcdr428/tsMuxer/actions) and confirm whether the problem has been fixed, thanks.
> Edit: select the platform, then the build, then click on Artifact on top right to download tsMuxer.exe.

problem fixed, thanks :)
