### ISSUE TITLE
Multi-language support！

### ISSUE THREAD

**Issue by tamplin** [justdan96/tsMuxer#192]
I wanna Chinese version

**Comment by justdan96** [comment]
I guess for this we would need to collate translations and parse in the required messages depending on the user's language settings. I could take a look at the Qt5 code to see if we could swap out strings in a simple way.

**Comment by xavery** [comment]
Qt already supports all that. The only requirement is that translatable strings used inside the source files are passed through `QObject::tr`. Strings available in UI files are marked as "translatable" by default. Translatable strings are saved to `.ts` files which can then be translated into different languages. The `.ts` files are turned into `.qm` at build time, and are loaded by the application depending on the desired language.

**Comment by xavery** [comment]
#196 is the first step to getting this done. It's not yet complete, since the compiled translations will have to be integrated with the binary and actually loaded in the main function. However, this can wait until we actually have any actual translations.

**Comment by justdan96** [comment]
Please find the Russian translation here: https://github.com/justdan96/tsMuxer/blob/master/tsMuxerGUI/translations/tsmuxergui_ru.ts

Please feel free to contribute a Chinese translation!

**Comment by justdan96** [comment]
@tamplin I will be closing this one down since we now support multiple languages. Extra translations are highly welcome.
