### ISSUE TITLE
Add an option for limiting the size of the output file

### ISSUE THREAD

**Issue by xavery** [justdan96/tsMuxer#195]
As seen on Doom9 forums, users don't always know how to cut the size of the output file in order to deliver a sample for analysis. This can be just as well implemented in tsmuxer itself.

**Comment by justdan96** [comment]
We could also update the documentation to include commands for chopping up the output file, until this functionality can be added.

**Comment by jcdr428** [comment]
@xavery there is already the option --cut-end in Split & Cut tab. Isn't it the same as what is proposed ?
