### ISSUE TITLE
Preserve the MPLS playlist item order and count 

### ISSUE THREAD

**Issue by stanionascu** [justdan96/tsMuxer#197]
Some mpls playlists can consist of multiple clpis and m2ts streams. Currently tsMuxer creates a single output m2ts / clip / mpls. Instead tsMuxer should have a mode when the order and number of playlist items is preserved.

**Comment by FilipeAmadeuO** [comment]
This could be interesting in order to keep the original structure

**Comment by justdan96** [comment]
Just to confirm, has this been resolved by #206 ?

**Comment by jcdr428** [comment]
@justdan96 Yes.

**Comment by stanionascu** [comment]
> Just to confirm, has this been resolved by #206 ?

Sorry for the delay in the response. This "issue" was about playlists with multiple files. E.g.: at this time when remuxing a playlist (e.g. changing an audio track), tsMuxer will produce a single output playlist + clpi + m2ts file. Instead, this issue is requesting to maitain the count and order of the clips and m2ts streams from the playlist, to make re-authoring (fixing the audio / subtitle streams) a bit less painful process. This information is already available within tsMuxer when adding the files, and tsMuxer has the functionality of generating multiple streams, based on their duration or size.

**Comment by jcdr428** [comment]
@stanionascu sorry I misunderstood the issue, it was initially preserving "the order and number of playlist items" -which was resolved by #206 and #159 .

If you want tsMuxer to output several clpi/m2ts, this would need substantial changes. Why not use a batch script ?

**Comment by stanionascu** [comment]
> @stanionascu sorry I misunderstood the issue, it was initially preserving "the order and number of playlist items" -which was resolved by #206 and #159 .
> 
> If you want tsMuxer to output several clpi/m2ts, this would need substantial changes. Why not use a batch script ?

Sometimes the audio or subtitle track can be a single continuous source while the playlist is composed of multiple. Using a batch file (hoping that there are no overlaps) would require cutting the extra track into the equivalent number and duration to match the playlist.

**Comment by jcdr428** [comment]
@stanionascu unless I mistanderstood again, you can use a batch file to output all the clpi and m2ts keeping the same numbers as original. Then you modify the mpls with BDEdit to change the list of playItem tracks as needed.
