### ISSUE TITLE
compile under Qt5

### ISSUE THREAD

**Issue by Selur** [justdan96/tsMuxer#2]
here's a patchfile of the changes I made to (tsMuxerGUI to) allow the compilation under Qt5 with Qt Creator:
https://pastebin.com/hWNu9eVW

**Comment by justdan96** [comment]
Amazing! I'll get this merged soon!

**Comment by justdan96** [comment]
I can't seem to get this patch applied - it just errors out for me. Can you please supply the command line options I can use to apply this patch or fork the repo, apply the patch and submit a pull request?

**Comment by Selur** [comment]
(you did apply the patch only to the tsMuxerGUI-part right)
sorry, busy today and the next few days, but I zipped the whole tsMuxer checkout folder I modified and uploaded it to: https://drive.google.com/open?id=16HlS20FQ37UpsuiUQmEedYX-rpQTNCKG

**Comment by justdan96** [comment]
Nevermind - got the command:
```
git apply --reject --whitespace=fix tsmuxer_compile_with_qcreator_and_qt5.txt
```
I've pushed the changes to the following branch:
https://github.com/justdan96/tsMuxer/tree/enhancement-qt5

I'll try this out in my VMs to see how it impacts the current Windows and Linux build instructions.
