### ISSUE TITLE
Error while loading shared libraries: libstdc++-6.dll in static tsmuxer @MSYS2

### ISSUE THREAD

**Issue by abakum** [justdan96/tsMuxer#202]
![image](https://user-images.githubusercontent.com/18271863/75077071-be60ab00-5512-11ea-97e2-6756a0fcda01.png)
Static tsmuxer @MINGW well run
![image](https://user-images.githubusercontent.com/18271863/75077262-4646b500-5513-11ea-9863-6adddd3d25f1.png)

**Comment by Aleksoid1978** [comment]
Confirm - linked dynamically
![tsMuxer_Dlls](https://user-images.githubusercontent.com/11625603/75294998-8096b600-5875-11ea-9dc6-8c70085e8d91.png)
.

**Comment by justdan96** [comment]
Sorry are you saying it compiles fine in Mingw32 but not Msys2? My understanding of Msys2 was that there were the 3 subsystems, Msys2 for package management, Mingw32 for compiling 32-bit programs and Mingw64 for compiling 64-bit programs.

**Comment by Aleksoid1978** [comment]
Compile using msys2 + mingw32/64 can’t create static .dll/.exe, I checked it on other project.

**Comment by qyot27** [comment]
>Sorry are you saying it compiles fine in Mingw32 but not Msys2? My understanding of Msys2 was that there were the 3 subsystems, Msys2 for package management, Mingw32 for compiling 32-bit programs and Mingw64 for compiling 64-bit programs.

No, it appears what they're saying is that the so-called 'static' build is failing to run under the MSys2 main shell because they don't have GCC installed there.  They clearly do have it installed in the MinGW64 shell because it runs, but it's obvious this isn't actually a static build.

>Compile using msys2 + mingw32/64 can’t create static .dll/.exe, I checked it on other project.

MSys2's repo builds of GCC are built shared, which means you have to explicitly use stuff like `-static-libstdc++` and `-static` in your LDFLAGS to force it to use the static libraries.  tsMuxeR controls this using the -DTSMUXER_STATIC_BUILD=true option.

Running in the MSys2 shell:
```
MSYS /e/Documents/tsmuxer/build/tsMuxer
$ ldd tsmuxer.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ff814900000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ff812b60000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ff812160000)
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7ff8137e0000)
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7ff8128d0000)
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7ff8125e0000)
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7ff812780000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7ff812030000)
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7ff813410000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7ff813810000)
        gdiplus.dll => /c/WINDOWS/WinSxS/amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.18362.657_none_17b0a85e6da0b266/gdiplus.dll (0x7fffddda0000)
        SHELL32.dll => /c/WINDOWS/System32/SHELL32.dll (0x7ff814150000)
        combase.dll => /c/WINDOWS/System32/combase.dll (0x7ff812ec0000)
        cfgmgr32.dll => /c/WINDOWS/System32/cfgmgr32.dll (0x7ff812880000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7ff813960000)
        shcore.dll => /c/WINDOWS/System32/shcore.dll (0x7ff813360000)
        windows.storage.dll => /c/WINDOWS/System32/windows.storage.dll (0x7ff811890000)
        bcryptPrimitives.dll => /c/WINDOWS/System32/bcryptPrimitives.dll (0x7ff812560000)
        sechost.dll => /c/WINDOWS/System32/sechost.dll (0x7ff8138c0000)
        advapi32.dll => /c/WINDOWS/System32/advapi32.dll (0x7ff813b30000)
        profapi.dll => /c/WINDOWS/System32/profapi.dll (0x7ff811820000)
        powrprof.dll => /c/WINDOWS/System32/powrprof.dll (0x7ff811840000)
        UMPDC.dll => /c/WINDOWS/System32/UMPDC.dll (0x7ff8117d0000)
        shlwapi.dll => /c/WINDOWS/System32/shlwapi.dll (0x7ff812d60000)
        kernel.appcore.dll => /c/WINDOWS/System32/kernel.appcore.dll (0x7ff8117e0000)
        cryptsp.dll => /c/WINDOWS/System32/cryptsp.dll (0x7ff812010000)
```

was built with MinGW64 shell, though, using:
```
cmake ../ -G Ninja -DTSMUXER_STATIC_BUILD=true
```

**Comment by Aleksoid1978** [comment]
But in COMPILING.md write "run ./rebuild_linux.sh" and "This will create statically compiled versions of tsMuxer - so no external DLL files are required." It's wrong :)

**Comment by justdan96** [comment]
I think I remember getting shared binaries even with `-static` passed in, if any of the dependencies are only available as shared. I'm not sure if we need to update the documentation some more, there is a pull request open for some msys2 updates.

**Comment by abakum** [comment]
Thanks @ qyot27 for truly static

**Comment by abakum** [comment]
@justdan96 https://github.com/justdan96/tsMuxer/pull/184/commits/740c2d4047464741dcb2b58cedf858ffc687fc91
