### ISSUE TITLE
Support passing parameters currently delivered via metafiles in the commandline

### ISSUE THREAD

**Issue by xavery** [justdan96/tsMuxer#204]
Currently, doing any actual work in tsMuxeR requires creating a metafile which instructs the program on what actually needs to be done. This is rather unorthodox among existing programs, most notably `ffmpeg`, which uses the commandline as its main and only interface in order for users to instruct the program on the work to be done.
I think the same can, and should, be done in tsMuxeR, as the current approach requires any external scripts and/or programs using tsMuxeR to be aware of the syntax and format of the metafile, **and do any stream format detection themselves in any but the simplest cases** while tsMuxeR has the facilities to do that on its own.
To illustrate, the following metafile :
```
MUXOPT --no-pcr-on-video-pid --new-audio-pes --vbr --vbv-len=500
V_MPEG4/ISO/AVC, "/home/daniel/bbb_sunflower_1080p_30fps_normal.mp4", insertSEI, contSPS, track=1, lang=und
A_MP3, "/home/daniel/bbb_sunflower_1080p_30fps_normal.mp4", track=2, lang=und
A_AC3, "/home/daniel/bbb_sunflower_1080p_30fps_normal.mp4", track=3, lang=und
```
Could be instead expressed with the following commandline :
```
tsmuxer -i bbb_sunflower_1080p_30fps_normal.mp4 -map 0:0 -insertSEI -contSPS -lang und -map 0:1 -lang und -map 0:2 -lang und --no-pcr-on-video-pid --new-audio-pes --vbr --vbv-len=500 out.ts
```
This is obviously inspired by the aforementioned ffmpeg, and uses the following set of rules :
- `-i` parameters contain paths to the input tracks.
- `-map x:y` parameters mean that the parameters following them refer to the `y`th track in the `x`th input file.
- Two-dashed parameters are parameters meant to control the output. 
- The last parameter in the commandline is the path to the output file/folder.

You will notice that there are no switches meant to express the format of the given tracks : this is because tsMuxeR would default to detecting these itself in this mode, unless perhaps explicitly overridden with a `-format` parameter or something similar. Remember that currently, in order to properly generate the metafile, the binary has to be run beforehand in "stream detection mode" in order to put the proper formats in the generated metafile.

This summary is a result of a mail exchange with @abakum , so I believe that real users will be able to benefit from these changes.

Comments welcome.

**Comment by jcdr428** [comment]
I am totally for it. The current way of passing parameters via the meta file is quite unorthodox.

**Comment by justdan96** [comment]
Great idea!

**Comment by abakum** [comment]
I tried to squeeze out everything that is possible from the concept of creating and editing a metafile. This approach does not at all cancel either tsMuxerGUI or what offers @xavery 
Look https://github.com/abakum/tsMuxer/blob/abakum-py/tsMuxeR.py

**Comment by abakum** [comment]
Sorry google for my english \8^)

**Comment by justdan96** [comment]
I think someone on the forums was asking about a batch mode, a fully command line mode would probably go some of the way to fulfil that.

**Comment by xavery** [comment]
Maybe not explicitly, but it would definitely make using the program much more script-compatible. Thus, running batch workloads would be as simple as writing a for-loop in your favourite scripting language.

**Comment by nabsltd** [comment]
Wouldn't a script still have to use some tool that returns info about the streams in the source file so that you could create the parameters for the tsMuxer command line?

In other words, how would the script know which input streams to map to which output streams unless it already knew something about the content of the source file(s)?  With that knowledge, it's easy to create the metafile, and then feed that to txMuxer.  mediainfo can provide everything a script needs to create the tsMuxer metafile.

Sure, command line options would be a bit easier, but that's not really the hard part in this case.

**Comment by abakum** [comment]
@nabsltd Look https://github.com/abakum/tsmuxerCLI#ex

**Comment by abakum** [comment]
tsmuxerGUI and tsmuxerCLI use tsmuxer in detect mode to build .meta

**Comment by lonecrane** [comment]
Great idea, I am looking forward to full CLI for a long time. Also I would like to suggest that in demux mode pids can be given via argvs directly and precisely, for example "0x1100,0x1101".

**Comment by abakum** [comment]
For select track 0x1100 and track 0x1101 from a.ts use
```tsmuxer.py a.ts+ =track=4352 + =track=4353 dir_with_demuxed```
where 4352 is the decimal of the hexadecimal number 1100

**Comment by lonecrane** [comment]
@abakum That's wonderful. I would use this nice script until tsMuser-CLI can directly deal with these parameters.

**Comment by abakum** [comment]
@lonecrane look https://github.com/abakum/tsmuxerCLI/commit/c684df42576011cadd914224622e5000ce30ab7c

**Comment by lonecrane** [comment]
@abakum Thanks, such a nice code. Now both decimal and hexadecimal parameters are OK. 
However, take for example demux, what I exactly looking forward to is just choosing the needed streams with CLI, no other calculation or detection (such as time-shift value) needed. In the GUI version we just check some streams, don't we? It would be much better that tsMuxer-CLI behaves interactively as eac3to.

**Comment by abakum** [comment]
Do not worry @lonecrane be happy:
```tsmuxer.py dir_with_demuxed a.ts+ =track=0x1100 + =track=0x1101 ! -```
demuxed track 0x1100 and track 0x1101 from a.ts to dir_with_demuxed
no calculation
no detection
no time-shift
no GUI
no tsMuxer-CLI
no interactively
no eac3to
no SARS-CoV-2
\8^)

**Comment by abakum** [comment]
https://en.wikibooks.org/wiki/Eac3to/How_to_Use

STEP 1: By typing
eac3to.exe "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits"
the title playlist of the disc is generated:
1) 00040.mpls, 00294.m2ts, 1:58:59
   - Chapters, 20 chapters
   - h265/HEVC, 2160p24 /1.001 (16:9)
   - h265/HEVC, 1080p24 /1.001 (16:9) - Dolby Vision Enhancement Layer
   - TrueHD, English, multi-channel, 48kHz
   - E-AC3, Spanish, multi-channel, 48kHz
   - E-AC3, French, multi-channel, 48kHz
   - AC3, English, stereo, 48kHz
   - AC3, English, stereo, 48kHz

**Comment by abakum** [comment]
STEP 2: By adding the title number you want, the above command changes to 
eac3to.exe "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits" 1)
and the stream/track list of the specific title is generated:
M2TS, 2 video tracks, 5 audio tracks, 5 subtitle tracks, 0:00:04, 11.988p
1: Chapters, 20 chapters
2: h265/HEVC, 2160p24 /1.001 (16:9), 10 bits
3: h265/HEVC, 1080p24 /1.001 (16:9), 10 bits - Dolby Vision Enhancement Layer
4: TrueHD/AC3 (Atmos), English, 7.1 channels, 48kHz
   (embedded: AC3, 5.1 channels, 448kbps, 48kHz, dialnorm: -27dB)
5: E-AC3, Spanish, 7.1 channels, 768kbps, 48kHz, dialnorm: -27dB
   (core: AC3, 5.1 channels, 448kbps, 48kHz, dialnorm: -27dB)
6: E-AC3, French, 7.1 channels, 768kbps, 48kHz
   (core: AC3, 5.1 channels, 448kbps, 48kHz)
7: AC3, English, 2.0 channels, 192kbps, 48kHz, dialnorm: -27dB, -17ms
8: AC3, English, 2.0 channels, 192kbps, 48kHz, dialnorm: -27dB, -17ms
9: Subtitle (PGS), English
10: Subtitle (PGS), Chinese
11: Subtitle (PGS), Chinese
12: Subtitle (PGS), Chinese
13: Subtitle (PGS), Chinese

or by tsmuxerCLI:
tsmuxer.py tsmuxer12.exe "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls"+
Пайтон 2.7 C:\Python27\python.exe ('Russian_Russia', '1251')
[u'tsmuxer.py', u'tsmuxer12.exe', u'1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\\BDMV\\PLAYLIST\\00040.mpls+']@410
(u'tsmuxer12.exe', u'1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\\BDMV\\PLAYLIST\\00040.mpls')@57, 447
Network Optix tsMuxeR.  Version 2.6.12. www.networkoptix.com
Track ID:    4113
Stream type: HEVC
Stream ID:   V_MPEGH/ISO/HEVC
Stream info: Profile: Main10@5.1 Resolution: 3840:2160p Frame rate: 23.976
Stream lang:
Stream delay: 17

...
File #00000 name=1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\STREAM\00294.m2ts
Duration: 01:58:59.465
start-time: 524280
Marks: 00:00:00.000 00:05:00.425 00:08:20.374 00:13:27.640 00:16:39.790
Marks: 00:23:33.495 00:30:29.661 00:35:35.550 00:42:26.377 00:51:35.092
Marks: 00:56:37.310 01:02:30.079 01:06:34.573 01:12:05.320 01:19:46.198
Marks: 01:28:48.823 01:33:44.452 01:38:12.595 01:41:44.681 01:49:47.581
Marks: 01:58:59.215


8><---fm.meta:
MUXOPT --no-pcr-on-video-pid --new-audio-pes --vbr --vbv-len=500 --start-time=524280 --custom-chapters=00:00:00.000;00:05:00.425;00:08:20.374;00:13:27.640;00:16:39.790;00:23:33.495;00:30:29.661;00:35:35.550;00:42:26.377;00:51:35.092;00:56:37.310;01:02:30.079;01:06:34.573;01:12:05.320;01:19:46.198;01:28:48.823;01:33:44.452;01:38:12.595;01:41:44.681;01:49:47.581;01:58:59.215
V_MPEGH/ISO/HEVC, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4113, contSPS
V_MPEGH/ISO/HEVC, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4117, contSPS
A_AC3, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4352
A_AC3, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4353
A_AC3, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4354
A_AC3, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4355
A_AC3, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4356
S_HDMV/PGS, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4768, lang=eng, fps=23.976
S_HDMV/PGS, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4769, lang=zho, fps=23.976
S_HDMV/PGS, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4770, lang=zho, fps=23.976
S_HDMV/PGS, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4771, lang=zho, fps=23.976
S_HDMV/PGS, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4772, lang=zho, fps=23.976
8><---

**Comment by abakum** [comment]
STEP 3: Finally, choose the tracks that are going to be processed and output like this
eac3to "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits" 1) 2: ULTRAHD\00040.track_4113.hevc 3: ULTRAHD\00040.track_4117.hevc 4: ULTRAHD\00040.track_4352.ac3 9: ULTRAHD\00040.track_4768.sup
or by tsmuxerCLI:
tsmuxer.py ULTRAHD "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls"+ =track=4113 + =track=4117 + =track=4352 + =track=4768 ! - 
Пайтон 2.7 C:\Python27\python.exe ('Russian_Russia', '1251')
[u'tsmuxer.py', u'tsmuxer12.exe', u'ULTRAHD', u'1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\\BDMV\\PLAYLIST\\00040.mpls+', u'=track=4113', u'+', u'=track=4117', u'+', u'=track=4352', u'+', u'=track=4768', u'!', u'-']@410
(u'tsmuxer12.exe', u'1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\\BDMV\\PLAYLIST\\00040.mpls')@57, 447
Network Optix tsMuxeR.  Version 2.6.12. www.networkoptix.com
Track ID:    4113
Stream type: HEVC
Stream ID:   V_MPEGH/ISO/HEVC
Stream info: Profile: Main10@5.1 Resolution: 3840:2160p Frame rate: 23.976
Stream lang:
Stream delay: 17

...
File #00000 name=1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\STREAM\00294.m2ts
Duration: 01:58:59.465
start-time: 524280
Marks: 00:00:00.000 00:05:00.425 00:08:20.374 00:13:27.640 00:16:39.790
Marks: 00:23:33.495 00:30:29.661 00:35:35.550 00:42:26.377 00:51:35.092
Marks: 00:56:37.310 01:02:30.079 01:06:34.573 01:12:05.320 01:19:46.198
Marks: 01:28:48.823 01:33:44.452 01:38:12.595 01:41:44.681 01:49:47.581
Marks: 01:58:59.215


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] =track=4113 [1]@532
[1] + =track=4117 [1, 2]@532
[1, 2] + =track=4352 [1, 2, 3]@532
[1, 2, 3] + =track=4768 [1, 2, 3, 8]@532
[1, 2, 3, 8] ! [4, 5, 6, 7, 9, 10, 11, 12]@508
[4, 5, 6, 7, 9, 10, 11, 12] - [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]@508
8><---fm.meta:
MUXOPT --no-pcr-on-video-pid --new-audio-pes --vbr --vbv-len=500 --start-time=524280 --custom-chapters=00:00:00.000;00:05:00.425;00:08:20.374;00:13:27.640;00:16:39.790;00:23:33.495;00:30:29.661;00:35:35.550;00:42:26.377;00:51:35.092;00:56:37.310;01:02:30.079;01:06:34.573;01:12:05.320;01:19:46.198;01:28:48.823;01:33:44.452;01:38:12.595;01:41:44.681;01:49:47.581;01:58:59.215
V_MPEGH/ISO/HEVC, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4113, contSPS
V_MPEGH/ISO/HEVC, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4117, contSPS
A_AC3, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4352
#A_AC3, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4353
#A_AC3, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4354
#A_AC3, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4355
#A_AC3, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4356
S_HDMV/PGS, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4768, lang=eng, fps=23.976
#S_HDMV/PGS, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4769, lang=zho, fps=23.976
#S_HDMV/PGS, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4770, lang=zho, fps=23.976
#S_HDMV/PGS, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4771, lang=zho, fps=23.976
#S_HDMV/PGS, "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls", track=4772, lang=zho, fps=23.976
8><---
(u'tsmuxer12.exe', 'c:\\windows\\temp\\tmpvoyo6v', u'ULTRAHD')@40, 587
Network Optix tsMuxeR.  Version 2.6.12. www.networkoptix.com
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
6.8% complete
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
Decoding TRUE-HD stream (track 3): AC3 core+TRUE-HD. Peak bitrate: 7158Kbps (core 448Kbps) Sample Rate: 48KHz Channels: 7.1
Processed 106 video frames
Processed 106 video frames
100.0% complete
Flushing write buffer
Demux complete.
Demuxing time: 0 sec

dir /B ULTRAHD
00040.track_4113.hevc
00040.track_4117.hevc
00040.track_4352.ac3
00040.track_4768.sup

**Comment by abakum** [comment]
or:
```tsmuxer.py tsmuxer12.exe ULTRAHD "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls"+ =V  ! -```
```tsmuxer.py tsmuxer12.exe ULTRAHD "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls"+ =A =1  ! -```
```tsmuxer.py tsmuxer12.exe ULTRAHD "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls"+ =S =1 ! -```

**Comment by lonecrane** [comment]
@abakum Hi, what's the tsmuxer12.exe in your code? I would like to use your nice code to generate the meta file for a blu-ray media source.

**Comment by abakum** [comment]
Hi @lonecrane There is no tsmuxer12.exe in the code, but if you rename tsmuxer.py to tsmuxer12.py then instead run tsmuxer.exe  will run tsmuxer12.exe on Windows

**Comment by lonecrane** [comment]
@abakum Here is your example usage code:
`tsmuxer.py tsmuxer12.exe ULTRAHD "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls"+ =track=4113 + =track=4117 + =track=4352 + =track=4768 ! - 
`
Here 'tsmuxer12.exe' appears. 
And I would like to generate the meta file for a blu-ray disc, enabling all the streams of the disc. Could you kindly give me the correspoding command?

**Comment by xavery** [comment]
After giving it some thought, I decided that it's actually pointless exactly due to the reasons @nabsltd listed. Closing.
