### ISSUE TITLE
tsMuxer (after 54f59df) doesn't set the fps field correctly in HEVC

### ISSUE THREAD

**Issue by AFriedo** [justdan96/tsMuxer#210]
In the example the fps (including the subtitles) were changed from 24000/1001 to 25fps. MPlayer Shows 25fps in file information and 23.976fps in stream information.
![file](https://user-images.githubusercontent.com/61536090/75421997-df266780-593b-11ea-8353-982a45ea2790.png)
![stream](https://user-images.githubusercontent.com/61536090/75421999-dfbefe00-593b-11ea-9d91-fdb02bf0708d.png)

**Comment by jcdr428** [comment]
@AFriedo I believe it has always been like this, even before 54f59df or 2.6.12 (I've just tested with both of them).

tsMuxer is a muxer, not an encoder: it changes the PCRs (program clock reference) in the packet headers, but it doesn't modify the streams.
Mpeg-TS fps is extracted from the gaps between PCR packets.
Video stream fps is extracted from the pps or sps of the video stream.

tsMuxer could also change the fps inside the video streams, but it goes beyond the scope of a muxer. Same thing happens with mkvtoolnix, when you change to 25fps the stream is still shown as 23.976 in mediainfo.

**Comment by justdan96** [comment]
I'll close this one off
