### ISSUE TITLE
Output to MP4

### ISSUE THREAD

**Issue by 775405984** [justdan96/tsMuxer#214]
It says here in your About page that tsMuxer support containers and formats like MP4/MOV. 

But I can't seem to find the mp4 option in tsMuxerGUI output menu.

For me, the only way to turn .ts file to .mp4 file right now is Demux it with tsMuxer, and then remux the audio and video tracks with My MP4Box GUI. It's very inconvenient.

What am I missing here? Do I need to type in some code?

**Comment by jcdr428** [comment]
@775405984 "tsMuxer supports MP4/MOV" means tsMuxer can detect streams in MP4/MOV to mux them as TS/M2TS. Not the opposite ;)
The best option is to use MP4Box as command line, directly with the ts/m2ts file:
`MP4Box -add file.ts new_file.mp4`
