### ISSUE TITLE
Filenames with periods get truncated on demux

### ISSUE THREAD

**Issue by MarcoO74** [justdan96/tsMuxer#225]
If the input filename of a demux operation contains periods besides the last one then the filename gets truncated. For example "Trip to the U.S. West Coast.ts" becomes something like "Trip to the U.track_256.264" instead of "Trip to the U.S. West Coast.track_256.264", like any other file.

Since the filenames of the output of a demux operation can't be controlled then it's crucial that all files follow the same logic, in order to use it in scripts for automation..

**Comment by abakum** [comment]
> Since the filenames of the output of a demux operation can't be controlled

Maybe at the same time instead of --demux
let write --demux=foo then there will be foo.track_256.264

**Comment by jcdr428** [comment]
@justdan96 in type.cpp line 303, change
`endPos = i;`
to
`if (endPos == src.size())
     endPos = i;`

**Comment by justdan96** [comment]
I just tested the change @jcdr428 suggested, I can't reproduce the issue after that.
