### ISSUE TITLE
Forced Subttiles Turned ON

### ISSUE THREAD

**Issue by Eriz0Sexy** [justdan96/tsMuxer#236]
tsmuxer is wonderfull software, thank you very much for all work, but,, it´s possible add Turned ON por subttitles forced track?
I need this option for UHD. Thanks

**Comment by justdan96** [comment]
Would you be able to provide a concept for what that would look like in the GUI?

**Comment by Eriz0Sexy** [comment]
something like that, sorry for the bad drawing

https://i.imgur.com/2SntLHM.jpg

thank you

**Comment by jcdr428** [comment]
@Eriz0Sexy how is it different from the default track option already impemented ?

<img width="452" alt="DefaultTracks" src="https://user-images.githubusercontent.com/56721609/77850554-b06a0e00-71d3-11ea-8180-4b523783bc38.png">

**Comment by jcdr428** [comment]
@xavery this issue should be closed.

**Comment by xavery** [comment]
@jcdr428 Thanks, closing as requested.
