### ISSUE TITLE
Trying to import m4v... nothing happens

### ISSUE THREAD

**Issue by binba2** [justdan96/tsMuxer#240]
tsmuxer nightly 2020-03-10--01-12-52 (version git-eecf6b0) on OS X 10.13.6
Installed homebrew, freetype and zlib.

1. Attempting to import an m4v file into tsmuxerGUI... nothing happens. Dragging into the input window, nothing happens. Via "add" button, choosing file, "open", nothing happens. (Open dialog closes, same behavior as if I hit "cancel").
Other (e.g. wav) files do open properly.

2. Tried with 3 different m4v files. These are generated from Adobe Premiere or Adobe Media Encoder Mac with H264-Bluray settings.  1080p Rec709 (2D), nothing fancy.
Importantly, _those same m4v files work great in the "old" tsMuxer 2.6.11._ They get opened, recognized, author, and the resulting BluRay discs play great on numerous hardware BluRay players.

3. Tried a bit with tsMuxeR CLI (first time I’m using it):
With just feeding it the m4v file:
	`Error: moov atom not found`
with a meta file:
	`Can't detect stream type`

**Comment by jcdr428** [comment]
@binba2 can we please get a link to a sample of m4v not working.

**Comment by justdan96** [comment]
@binba2 Are you able to provide a sample file?

**Comment by binba2** [comment]
Sorry for the delay. Here is a sample file:
[https://drive.google.com/open?id=1ZhffF6_5nXK0pzi4Iwx_2-gc1ITbtwzu]
Ignore the video playback, download the source m4v with the button in the top-right corner.

**Comment by jcdr428** [comment]
@binba2 the format of your sample is pure AVC. Simple rename the file extension from .m4v to .avc, .264 or .h264, and it will be detected by tsMuxer.

**Comment by justdan96** [comment]
Are you okay to test this and confirm if the issue can be closed?

**Comment by abakum** [comment]
http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4

tsmuxer.exe bbb_sunflower_1080p_60fps_normal.mp4
tsMuxeR version git-5e71110. github.com/justdan96/tsMuxer
Error: MP4/MOV error: Invalid H.264/AVC frame at position 2119182

tsmuxer12.exe bbb_sunflower_1080p_60fps_normal.mp4
Network Optix tsMuxeR.  Version 2.6.12. www.networkoptix.com
Track ID:    1
Stream type: H.264
Stream ID:   V_MPEG4/ISO/AVC
Stream info: Profile: High@4.2  Resolution: 1920:1080p  Frame rate: 60
Stream lang: und

Track ID:    2
Stream type: MPEG-Audio
Stream ID:   A_MP3
Stream info: Bitrate: 160Kbps  Sample Rate: 48KHz  Channels: 2  Layer: 3
Stream lang: und

Track ID:    3
Stream type: AC3
Stream ID:   A_AC3
Stream info: Bitrate: 320Kbps Sample Rate: 48KHz Channels: 5.1
Stream lang: und

Duration: 00:10:34.533

**Comment by abakum** [comment]
http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4

tsmuxer.exe bbb_sunflower_1080p_30fps_normal.mp4
tsMuxeR version git-5e71110. github.com/justdan96/tsMuxer
Track ID:    1
Stream type: H.264
Stream ID:   V_MPEG4/ISO/AVC
Stream info: Profile: High@4.1  Resolution: 1920:1080p  Frame rate: 30
Stream lang: und

Track ID:    2
Stream type: MPEG-Audio
Stream ID:   A_MP3
Stream info: Bitrate: 160Kbps  Sample Rate: 48KHz  Channels: 2  Layer: 3
Stream lang: und

Track ID:    3
Stream type: AC3
Stream ID:   A_AC3
Stream info: Bitrate: 320Kbps Sample Rate: 48KHz Channels: 5.1
Stream lang: und

Duration: 00:10:34.533

**Comment by jcdr428** [comment]
@abakum you should have opened a new issue.
Fixed with #249 .

**Comment by abakum** [comment]
![image](https://user-images.githubusercontent.com/18271863/77155685-f2e26b00-6aae-11ea-8b53-e4f8a1d37fc2.png)


> tsmuxer.exe bbb_sunflower_1080p_60fps_normal.mp4
> tsMuxeR version git-**5e71110**. github.com/justdan96/tsMuxer
> Error: MP4/MOV error: Invalid H.264/AVC frame at position 2119182

**Comment by abakum** [comment]
![image](https://user-images.githubusercontent.com/18271863/77156001-83b94680-6aaf-11ea-8550-92b94ea3bc9e.png)

**Comment by justdan96** [comment]
I will close this issue for now, @abakum please open a new one if your issue persists.

**Comment by abakum** [comment]
All ok:
c:\msys64\home\Konstantin.Abakumov>tsmuxer.exe bbb_sunflower_1080p_60fps_normal.mp4
tsMuxeR version git-eaf35b4. github.com/justdan96/tsMuxer
Track ID:    1
Stream type: H.264
Stream ID:   V_MPEG4/ISO/AVC
Stream info: Profile: High@4.2  Resolution: 1920:1080p  Frame rate: 60
Stream lang: und

Track ID:    2
Stream type: MPEG-Audio
Stream ID:   A_MP3
Stream info: Bitrate: 160Kbps  Sample Rate: 48KHz  Channels: 2  Layer: 3
Stream lang: und

Track ID:    3
Stream type: AC3
Stream ID:   A_AC3
Stream info: Bitrate: 320Kbps Sample Rate: 48KHz Channels: 5.1
Stream lang: und

Duration: 00:10:34.533
