### ISSUE TITLE
[Nightly Debian package: Ubuntu 19.10]: Installation fault due to dependency on elogind package

### ISSUE THREAD

**Issue by RogueScholar** [justdan96/tsMuxer#241]
I can't speak to why tsMuxer has this dependency (editing the DEBIAN/control file manually to remove the dependency/change it to a Recommends or Suggests/add systemd as an alternate has seemingly no effect on tsMuxer's operability for me) but as libelogind0 conflicts with systemd (an essential Ubuntu package) I believe the issue warrants further investigation.

**Comment by justdan96** [comment]
Sorry that was me fiddling with the dependencies in OBS. For some reason it was always pulling in something to do with systemd. I'll try editing it and see if I can remove the dependency.

**Comment by RogueScholar** [comment]
Looks like you were successful on that front; apt pulled in the package for installation. But now dpkg is griping that the debian/control file in it lacks the Maintainer field. :unamused:

**Comment by justdan96** [comment]
Also the requirements list is really long - I'll have to look at how the spec file should look to resolve those issues.

**Comment by justdan96** [comment]
I found that debbuild translates the Packager field to Maintainer - will add that in today.

**Comment by justdan96** [comment]
@RogueScholar can you please check the [latest](https://build.opensuse.org/package/binaries/home:justdan96/tsMuxer/Ubuntu_debbuild_19.10)?

**Comment by justdan96** [comment]
Will close due to aging.
