### ISSUE TITLE
Error: Bitstream exception std::exception when demuxing UHD

### ISSUE THREAD

**Issue by lonecrane** [justdan96/tsMuxer#252]
I have some UHDs released by a group featuring DIY research. These UHDs works fine with player and other demux tools ffempg and 'DGDemux', but can not be processed by tsMuser. When opening the main mpls file with tsMuxerGUI, nothing happened as if I have not opened it. The result with command line version as belows:
 ```
w64-nightly-2020-03-19--01-11-55\tsMuxeR.exe "X:\1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls"
tsMuxeR version git-5e71110. github.com/justdan96/tsMuxer
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
Error: Bitstream exception std::exception. It does not have to be! Please contact application support team for more information.
```
The latest tsMuxer version which deals with this file correctly is found as:
```
w64-nightly-2019-12-22--01-10-25\tsMuxeR.exe "X:\1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls"
tsMuxeR version 2.6.15. github.com/justdan96/tsMuxer
Track ID:    4113
Stream type: HEVC
Stream ID:   V_MPEGH/ISO/HEVC
Stream info: Profile: Main10@5.1 Resolution: 3840:2160p Frame rate: 23.976
Stream lang:
Stream delay: 17
...
```
And w64-nightly-2019-12-27--01-10-05 issues error like w64-nightly-2020-03-19--01-11-55 does.
What can I do for further diagnostic?

**Comment by jcdr428** [comment]
@lonecrane please zip the files and send me the link. In STREAM folder please copy only one file -the first 20 MB of 00040.m2ts. You can cut the file with e.g. HxD hex editor -just Search->Goto offset 21000000, select data to the end, delete it and save the file under a new name.

**Comment by justdan96** [comment]
@lonecrane Please test the nightly version that will be released tomorrow morning and let me know if the issue remains.

**Comment by lonecrane** [comment]
@jcdr428 Hi, many thanks. 
The sample has been made as your instruction and uploaded to: https://www.mediafire.com/file/dx40ogunu0snomk/1917_2019_ULTRAHD_BluRay_2160p_HEVC_Atmos_TrueHD7.1-sGnb@CHDBits-Sample.rar/file

**Comment by abakum** [comment]
tsMuxeR.exe "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\PLAYLIST\00040.mpls"
tsMuxeR version git-eaf35b4. github.com/justdan96/tsMuxer
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
Error: Bitstream exception std::exception. It does not have to be! Please contact application support team for more information.

**Comment by abakum** [comment]
tsmuxer12.exe "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\STREAM\00294.m2ts"
Network Optix tsMuxeR.  Version 2.6.12. www.networkoptix.com
Track ID:    4113
Stream type: HEVC
Stream ID:   V_MPEGH/ISO/HEVC
Stream info: Profile: Main10@5.1 Resolution: 3840:2160p Frame rate: 23.976
Stream lang:
Stream delay: 17
...
Duration: 02:28:52.802



tsmuxer.exe "1917 2019 ULTRAHD BluRay 2160p HEVC Atmos TrueHD7.1-sGnb@CHDBits\BDMV\STREAM\00294.m2ts"
tsMuxeR version git-eaf35b4. github.com/justdan96/tsMuxer
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
Error: Bitstream exception std::exception. It does not have to be! Please contact application support team for more information.

**Comment by jcdr428** [comment]
Thanks @abakum. Fixed by #255 .

**Comment by lonecrane** [comment]
@jcdr428 The latest code works fine. Thanks a lot.

**Comment by jcdr428** [comment]
@lonecrane good. Could you please close the issue.
