### ISSUE TITLE
Subtitle font size reset to 65 when relauching app

### ISSUE THREAD

**Issue by damkalan-uth** [justdan96/tsMuxer#257]
Subtitle font size reset to 65 when relauching app

**Comment by jcdr428** [comment]
@damkalan-uth which system ? On my Windows it is working ok, i.e. setting is saved and shown when relanching app.

**Comment by justdan96** [comment]
@damkalan-uth if you can't provide an update I will close the issue due to ageing.

**Comment by xavery** [comment]
Judging from the code, font size/face changes are always supposed to trigger saving the settings if the font settings were changed successfully. However, not all GUI elements triggered saving the settings file, so I fixed this by explicitly saving them when the application shuts down, which should prevent similar problems in the future.
