### ISSUE TITLE
[bug] With multi-m2ts mpls, subtitles drift out of sync

### ISSUE THREAD

**Issue by jcdr428** [justdan96/tsMuxer#262]
See notification of bug here https://forum.doom9.org/showthread.php?p=1905010#post1905010

**Comment by FilipeAmadeuO** [comment]
The solution maybe would be for tsmuxer to mantain the multi m2ts (one mpls) struture and not join the multi m2ts in one big m2ts.
This way we could build one by one m2ts and keep the exact same struture as before.

**Comment by jcdr428** [comment]
@FilipeAmadeuO that would be nice, however this would be a substantial rewrite of the code as currently tsMuxer is set to write only one m2ts, clpi, mpls, and pre-defined index.bdmv and MovieObject.bdmv. Plus code writing for the ATCd seamless branching etc.

**Comment by FilipeAmadeuO** [comment]
> @FilipeAmadeuO that would be nice, however this would be a substantial rewrite of the code as currently tsMuxer is set to write only one m2ts, clpi, mpls, and pre-defined index.bdmv and MovieObject.bdmv. Plus code writing for the ATCd seamless branching etc.

OK. Understood. Maybe a improvement for the future.

**Comment by lonecrane** [comment]
According to the tests on the UHD BD 'WALL E', now subtitles are demuxed very precise.
Internal timestamp presented by player:
![fig 1-2](https://user-images.githubusercontent.com/36885830/77837079-606d5600-7197-11ea-8de0-6887b5b6f917.png)
The Demuxed timestamp with the latest version matches very precisely:
![fig 1-1](https://user-images.githubusercontent.com/36885830/77837083-63684680-7197-11ea-96cf-d51c5acf82c7.png)
The Demuxed timestamp with the previous version w64-nightly-2020-03-25--01-12-53 delays 358ms:
![fig 1-3](https://user-images.githubusercontent.com/36885830/77837149-50a24180-7198-11ea-8612-0a66a8a61f2d.png)
