### ISSUE TITLE
[bug] Empty "About" tab at startup

### ISSUE THREAD

**Issue by jcdr428** [justdan96/tsMuxer#267]
The "About" tab is empty unless and until a language is selected in the bottom left dropdown menu.
English should be the selected language by default.

Once selected, language should be saved in .ini file for next startup.

<img width="405" alt="EmptyAboutTab" src="https://user-images.githubusercontent.com/56721609/77850496-32a60280-71d3-11ea-912a-d9213dcce3f1.png">

**Comment by jcdr428** [comment]
@xavery could you please have a look at this one ?

**Comment by justdan96** [comment]
Xavery is taking a bit of a break, I'll see if I can pick this one up.
