### ISSUE TITLE
Output path check for invalid characters

### ISSUE THREAD

**Issue by dmiva** [justdan96/tsMuxer#268]
I was making TS Muxing, and have forgot about invalid characters in Windows file names. So i specified output folder with file name "Alita: Battle Angel (2019).ts". After muxing completed, a file with name Alita was created in output folder. It's size was 0 bytes. 
![image](https://user-images.githubusercontent.com/24508298/77855375-bd4d2880-71f8-11ea-9f35-9965559fe773.png)
![image](https://user-images.githubusercontent.com/24508298/77855360-9e4e9680-71f8-11ea-99e1-71423c02d7c8.png)
But the file itself is flushed to the disk and takes space. You can see it in file recovery software
![image](https://user-images.githubusercontent.com/24508298/77855462-449a9c00-71f9-11ea-8b40-c7a4a5a0c458.png)
I think the could be implemented check for invalid characters in output path before starting muxing.

**Comment by jcdr428** [comment]
Good idea. From [MS doc](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions), the forbidden characters should be the nine<>:"/\|?* and ASCII 0 to 31. Any other for Linux or Mac platforms ?

**Comment by dmiva** [comment]
According to [stackoverflow](https://stackoverflow.com/a/31976060), for Linux its forward slash ('/') and null ('\0'). For [mac os ](https://ss64.com/osx/syntax-filenames.html) looks like the same. Maybe it's worth considering making whitelist of characters, instead of checking the OS version.

**Comment by justdan96** [comment]
@xavery Can you weigh in on this?

**Comment by justdan96** [comment]
I've taken a look and there's a few things here:

1. I have added the invalid characters as a boolean function in https://github.com/justdan96/tsMuxer/blob/master/libmediation/fs/osdep/file_unix.cpp and https://github.com/justdan96/tsMuxer/blob/master/libmediation/fs/osdep/file_win32.cpp
2. We have to check both the folder names in the path and the filename, there is similar code we can reuse for this.
3. Although we have getDirSeparator() defined in https://github.com/justdan96/tsMuxer/blob/master/libmediation/fs/directory.cpp the functions we use such as extractFileExt(...), extractFileName(...), extractFileName2(...), extractFilePath(...) and closeDirPath(...) don't actually use that in https://github.com/justdan96/tsMuxer/blob/master/libmediation/types/types.cpp. Instead they use OR with \ or /. To make things more consistent I can try switching them over.
4. Once that is done I can try to write the code to error if there are any invalid characters anywhere in the output path. If needed we could also have it automatically change them to an underscore (or something similar).

**Comment by justdan96** [comment]
Just tested the following branch successfully: https://github.com/justdan96/tsMuxer/tree/bug-check-for-invalid-chars-in-filename

![invalid_filename_error](https://user-images.githubusercontent.com/503722/77935503-63f10200-72a9-11ea-81a8-b7bd4efe9c74.png)

I will create a draft pull request with this functionality.
