### ISSUE TITLE
Enhancement: Muxing dual track DV Blu-ray to single track DV

### ISSUE THREAD

**Issue by jcdr428** [justdan96/tsMuxer#271]
Many DV SoCs for TV/STB/OTT do not read profile 7 -Dolby seems to limit this profile to Blu-ray player SoCs.

EL and RPU nals of the second hevc track can be transferred to the primary hevc track, creating a DV profile 6. Apparently welcomed https://forum.doom9.org/showthread.php?p=1905727#post1905727

Enhancement for 2.7+.

**Comment by GabeBlincoln** [comment]
I know this is old, but I'd suggest closing this.   
Dolby's 9/16/2019 documents simply say, "Note: Profiles 0–3 and 6 are not supported for new applications."
Regardless of whether it works on old devices or even current ones, two HEVC layers (whatever their track layout) still requires the hardware to have a second HEVC decoder chip, and almost nothing currently made has this.   Nearly anything playing it would be playing in a compatibility mode where the EL is discarded, making it equivalent to dropping the unused EL and converting to Profile 8.1 with dovi_tool... doesn't matter much for MEL.   The devices that can play the FEL version properly can all (AFAIK) play Profile 7 FEL properly too.   Making it into a deprecated profile for the purpose of the illusion of compatibility is kinda a waste of disk space and liable to break without notice.

**Comment by jcdr428** [comment]
@GabeBlincoln ok, I close.
