### ISSUE TITLE
[Request] Keep original timestamps

### ISSUE THREAD

**Issue by mukarator** [justdan96/tsMuxer#279]
Add an option for preserving the original timestamps and audio start time, without altering them in any way during the muxing process.

**Comment by jcdr428** [comment]
@mukarator could you please add an example and/or sample where tsMuxer alter the original timestamp / audio start time, thanks.

**Comment by jcdr428** [comment]
@mukarator could you please provide details. Without details or sample we cannot work on the issue, and we will have to close it.

**Comment by jcdr428** [comment]
@xavery no details /answer, I believe we can close the issue. @mukarator can reopen if needed.
