### ISSUE TITLE
VOB file does not load if it contains an (what it thinks is an invalid?) dvd_subtitle track

### ISSUE THREAD

**Issue by JohnLBergqvist** [justdan96/tsMuxer#284]
If my VOB file contains a subtitle track (stream 0x20 in the below example from FFMPEG)
```
Input #0, mpeg, from 'VTS_01_0.VOB':
  Duration: 00:00:55.58, start: 0.197678, bitrate: 162323 kb/s
    Stream #0:0[0x1bf]: Data: dvd_nav_packet
    Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, smpte170m, progressive), 720x480 [SAR 8:9 DAR 4:3], Closed Captions, 30.57 fps, 59.94 tbr, 90k tbn, 59.94 tbc
    Stream #0:2[0x80]: Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
    Stream #0:3[0x83]: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:4[0x20]: Subtitle: dvd_subtitle
```

The file just simply refuses to be added in TSMuxer (`git-97d49e4`) If I remove the subtitle track from the VOB, TSMuxer sees the file and I can then mux fine

Can you not just detect the presence of the subtitle track and ignore it, rather than simply giving up silently?

Update: It seems this is failing only if the VOB file both contains a subtitle track and isn't the 1st PGC in the VTS.

1. VTS_02_PGC_01 (has subtitle track): Works but complains it can't process track 1 (which is the subtitle track itself)
3. VTS_02_PGC_01 (doesn't have subtitle track): Works and doesn't complain at all.
3. VTS_02_PGC_02 (has subtitle track): Doesn't work at all - refuses to add the VOB.
4. VTS_02_PGC_02 (doesn't have subtitle track): Works and doesn't complain at all.

I'm extracting the content one PGC at a time, based on the IFOs on the DVD. So it's possible that when extracting the 2nd and future PGC's, the subtitle track is somehow corrupt/invalid?

**Comment by jcdr428** [comment]
@JohnLBergqvist I haven't managed to reproduce the issue. Could you please provide samples of VTS_02_PGC_01 and VTS_02_PGC_02 which contain subtitles and provoke this bug.
Please cut the VTS files e.g. with an hex editor to reduce them preferably below 50MB each.

**Comment by jcdr428** [comment]
@xavery no answer from @JohnLBergqvist for five months, the issue cannot be reproduced without sample.
I suggest we close this issue, JohnLBergqvist can reopen if needed.
