### ISSUE TITLE
tsMuxeR input file size limited

### ISSUE THREAD

**Issue by oshbo** [justdan96/tsMuxer#285]
I am using tsMuxeR to mux Blu-ray compatible 1920 x 1080 mp4 video with embedded AC-3 audio into a Blu-ray folder structure.  For testing purposes, I am using the GUI version of tsMuxer (vs. using line command).  My issue is that the largest video file size I am able to add is <4GB, otherwise the program crashes.  I am able to "add" multiple video segments as long as they are <4GB but only the first video segment makes it into the resulting Blu-ray folder.  Similarly, if I try to "join" files segments to the first file segment, the process stops with a "moov atom not found" error after the first segment is muxed.  This occurs even when the video segments are identical (with different file names).  My goal is to use a sufficient amount of video source files to result in a Blu-ray folder size of up to 25GB for writing to a Blu-ray disc.    Please advise.  Thanks.

**Comment by jcdr428** [comment]
@oshbo as I understand, for data > 4GB, there is a "wide" atom right after the "moov" atom, to extend the data lenght field from 4 to 8 bytes. I guess tsMuxer does not take this "wide" atom into account, I'll have a look.

**Comment by jcdr428** [comment]
@oshbo please try [this W64 build](https://github.com/jcdr428/tsMuxer/suites/611960754/artifacts/4687470) or [this Linux build](https://github.com/jcdr428/tsMuxer/suites/611960760/artifacts/4687438) to see whether it solves the issue. If it does, I will push the fix.

**Comment by oshbo** [comment]
**@jcdr428** Thanks for looking at this.  tsMuxeR is perfect for my project so I am very motivated to get it working.

I have not tried your fix yet because I cannot get the command line method to work using the original "tsMuxeR.exe" or your fix.  I get the return message "Can't detect stream type".  I have only used the GUI version until now so I am sure that I am doing something wrong.   I created/saved the meta file below (as "test.meta") from the GUI app and executed it on the command line.  The GUI version executes with no issues. 

**command line:** D:\tsmuxer> tsmuxer test.meta

**"test.meta" metafile content:**
MUXOPT --no-pcr-on-video-pid --new-audio-pes --blu-ray --vbr  --auto-chapters=5 --vbv-len=500
V_MPEG4/ISO/AVC, "D:\tsmuxer\test.mp4", insertSEI, contSPS, track=1, lang=und
A_AC3, "D:\tsmuxer\test.mp4", track=2, lang=und

Please advise.
Thanks.

**Comment by oshbo** [comment]
**@jcdr428** In addition to above, the output for **D:\tsmuxer>tsmuxer test.mp4** is below.  This tells me that tsmuxer can detect the stream type.

Network Optix tsMuxeR.  Version 2.6.12. www.networkoptix.com
Track ID:    1
Stream type: H.264
Stream ID:   V_MPEG4/ISO/AVC
Stream info: Profile: High@4.2  Resolution: 1920:1080p  Frame rate: 60
Stream lang: und

Track ID:    2
Stream type: AC3
Stream ID:   A_AC3
Stream info: Bitrate: 192Kbps Sample Rate: 48KHz Channels: 2
Stream lang: und

Duration: 00:00:39.884

**Comment by oshbo** [comment]
**@jcdr428** I got your fix to work.  I was able to mux one 9GB file into the Blu-ray structure.  Thanks!  I am going to continue to test joining files etc. If I encounter any problems I will let you know.  The problem I had in my 2 previous posts is that I did not specify the output location.  Thanks again.

**Comment by oshbo** [comment]
**@jcdr428** The next test I ran was to join 5 files approximately 1GB in size.  The process started but terminated at 19.7% with a "moov atom not found" error.  Based on the percent completed, it appears that the error occurred after the first file was muxed.  Since there is only 2 tracks (1 video, 1 audio) named in the meta file, my assumption is that the video segments may be joined before the process begins (?).  Here is the meta file:

MUXOPT --no-pcr-on-video-pid --new-audio-pes --blu-ray --vbr  --auto-chapters=5 --vbv-len=500
V_MPEG4/ISO/AVC, "D:\tsmuxer\Source\test (1).mp4"+"D:\tsmuxer\Source\test (2).mp4"+"D:\tsmuxer\Source\test (3).mp4"+"D:\tsmuxer\Source\test (4).mp4"+"D:\tsmuxer\Source\test (5).mp4", insertSEI, contSPS, track=1, lang=und
A_AC3, "D:\tsmuxer\Source\test (1).mp4"+"D:\tsmuxer\Source\test (2).mp4"+"D:\tsmuxer\Source\test (3).mp4"+"D:\tsmuxer\Source\test (4).mp4"+"D:\tsmuxer\Source\test (5).mp4", track=2, lang=und

**Comment by oshbo** [comment]
**@jcdr428** For the third test, I added 5x 1GB video files to the queue and started the muxing process.  The process completed successfully.  However, it produced a single 5GB m2ts file in the "bdmv/stream" folder but the play length was equivalent one of the input files (presumably the first file in the queue).  There were also a lot of artifacts in the video.  I am not sure what the output should have been for this test.

**Comment by oshbo** [comment]
Closed by mistake?

**Comment by jcdr428** [comment]
@oshbo the second/third test is a different bug, you should open a new issue if somebody else wants to work on it.
I'll push the fix for this issue.

**Comment by oshbo** [comment]
@jcdr428  Thanks for the fix!

**Comment by otaviocarpinteiro** [comment]
I'm sorry to restart this issue, but I'm having the same problem of oshbo. I created two mp4 videos in ShotCut editor and tried to join them. The message TsMuxer issues is the same "moov atom not found". Please see the attached PNG file. I'm using the most recent version of TsMuxer. Any suggestion? Thank you all, Otavio

![TsMuxer-Join](https://github.com/justdan96/tsMuxer/assets/70480576/1a3b2ab5-2468-4730-9f57-208fb5bc67bf)
