### ISSUE TITLE
File naming at demux

### ISSUE THREAD

**Issue by ferraript** [justdan96/tsMuxer#286]
Please change file naming of output files when using demux option.
I'll rather explain this using example:
Lets say I have three episodes of the same TV show. Names are like this:
TV.Show.S01.E01.mp4
TV.Show.S01.E02.mp4
TV.Show.S01.E03.mp4

If I demux audio track from first file, I get file TV.track_2.ac3.
Now if I demux audio track from next input files, the same file TV.track_2.ac3 is being overwritten and I end up with one audio file only.

Suggested behavior:
Demuxed tracks will preserve filename part of the input file appended with "_track" or ".track" suffix.
So I'll get files
TV.Show.S01.E01_track_2.ac3
TV.Show.S01.E02_track_2.ac3
TV.Show.S01.E03_track_2.ac3

Thanks.

**Comment by jcdr428** [comment]
@ferraript please advise which tsMuxer version you are using, thanks.

**Comment by ferraript** [comment]
I was using version from 2019/12/30.
As I can see, it's solved in latest version.
I'm an idiot. Sorry for bothering.

**Comment by jcdr428** [comment]
@ferraript no worries.
