### ISSUE TITLE
Mono PCM not muxed mono?

### ISSUE THREAD

**Issue by ktmf01** [justdan96/tsMuxer#287]
Hi,

To conserve quite a stack of Video8 tapes, I'm digitalizing them and putting them on Blu-ray discs. However, the audio on those tapes is mono. As I'm not 100% sure of ffmpegs AC3 codec, I'd like to keep the audio as PCM.

However, mono PCM, 16 bit, 48kHz has a datarate of 768kb/s. When I add this to tsMuxer, the datarate is displayed as 1536kb/s, that of a stereo stream. The GUI says 'mono' though. The filesize of the resulting mux is indeed such that I conclude that the audiotrack is no longer 1 channel.

Is this a limitation of Blu-ray (that mono has to be muxed as dual mono) or is there something else going on? I've been looking around in the source code, but couldn't find anything responsible for this change.

Thanks in advance.

**Comment by ktmf01** [comment]
I just found this bit of code in LPCMStreamReader::convertLPCMToWAV

` int mch = m_channels + (m_channels % 2 == 1 ? 1 : 0);`

It looks like only an even number of channels is accepted? There is no commentary explaining this sadly.

**Comment by jcdr428** [comment]
@ktmf01 this comes from the "Blu-ray Disc™ Read-Only Format Part 3: Audio Visual Basic Specifications":
HDMV LPCM audio streams for Primary audio
Number of channels shall be 2, 4, 6 or 8 channels. All the channels shall be sampled simultaneously on sampling phase.

**Comment by ktmf01** [comment]
Okay, that is very clear. Thank you for your comment. I'm going to reconsider using AC3 then, because 2-channel PCM is probably a bit too space consuming for my project.

**Comment by jcdr428** [comment]
@ktmf01 do you really need to keep a BDMV format to play in a Blu-Ray player ? Otherwise AAC VBR would be the best by far.

**Comment by ktmf01** [comment]
Yes, I'm going to burn these to Blu-ray M-discs and hand them out to family members, of which two have a Blu-ray player connected to their TV but not a Blu-ray drive in their PC's. That is the lowest common denominator, so I'll stick with that.

Sticking to a standard also gives me more confidence that these discs might still be (easily) playable 20 years from now. DVD would be even better from a compatibility view, but that would require too many (~10 times as much) discs for my taste.

Anyway, once more thanks for your explanation!
