### ISSUE TITLE
Separate DTS file will not load in version 24-04 and 26-04 works fine in 30-03 nightly

### ISSUE THREAD

**Issue by pwacooijmans** [justdan96/tsMuxer#290]
Dear justdan96,

Seperate DTS files will not load in version 24-04 nightly and 26-04 nightly but works fine in 30-03 nightly.

Kind Regards,

Pieter Cooijmans

**Comment by jcdr428** [comment]
@xavery just tested, DTS are accepted in 2020-04-16 bintray version but not in 2020-04-19. So it comes from the 18-04 commits, could you please have a look ?

**Comment by xavery** [comment]
> @xavery just tested, DTS are accepted in 2020-04-16 bintray version but not in 2020-04-19. So it comes from the 18-04 commits, could you please have a look ?

Thanks, bisecting reveals that 97d49e4d1ea2c849ce6996f273c94426fc6bfb3d caused this. I'll have a look.

**Comment by jcdr428** [comment]
@xavery actually the error comes from `if (strEndWith(tmpname, ".ts")) demuxer = new TSDemuxer(readManager, "");` replaced by `if (strEndWith(tmpname, "ts"))` : this includes .dts files !!

**Comment by xavery** [comment]
> @xavery actually the error comes from `if (strEndWith(tmpname, ".ts")) demuxer = new TSDemuxer(readManager, "");` replaced by `if (strEndWith(tmpname, "ts"))` : this includes .dts files !!

Yes. What a stupid mistake on my part. The commit is already on its way.
