### ISSUE TITLE
HEVC stream reader - Out of Bounds comparison

### ISSUE THREAD

**Issue by moderndeveloperllc** [justdan96/tsMuxer#292]
Looking through the compilation build logs for another issue I saw this:
```
/Users/runner/runners/2.169.1/work/tsMuxer/tsMuxer/tsMuxer/hevcStreamReader.cpp:319:41: warning: result of comparison of constant 3981312000 with expression of type 'int' is always true [-Wtautological-constant-out-of-range-compare]
    else if (width <= 7680 && pixelRate <= 3981312000)
```
Looks to be the last comparison of the if/else tree to set DV `level`. Seems like `pixelrate` needs to be 64 bit?

**Comment by jcdr428** [comment]
@moderndeveloperllc or at least unsigned int. Good catch, I'll change that.
