### ISSUE TITLE
error-3 in mux ts

### ISSUE THREAD

**Issue by roboluzzo** [justdan96/tsMuxer#295]
Hi, I have a problem with the tsmuxer version of 29-04-2020, in practice I try to mux a hevc 60 fps file with a truehd audio file, everything runs smoothly up to about 84% after which it gives me error -3. I am attaching a printshot which summarizes the situation.
I forgot the hevc file is a 68.4 gb single layer dolby vision to which the audio track is added which is about 4 gb.
Thank you, Roberto.
![tsmuxer error -3](https://user-images.githubusercontent.com/35394610/80582436-ff8fa280-8a0e-11ea-939f-49e142f6aa90.jpg)

**Comment by jcdr428** [comment]
@roboluzzo what is your OS, and which is the latest bintray version without this error, e.g. 2020-04-28?

**Comment by roboluzzo** [comment]
Hi, windows 10, I am currently using the Nightly of 29-04 but the problem with the versions that I have tried, from 10 days to today, has always been there, except with films that do not exceed 60 gb.
Thank you, Roberto.
________________________________
Da: jcdr428 <notifications@github.com>
Inviato: mercoledì 29 aprile 2020 13:15
A: justdan96/tsMuxer <tsMuxer@noreply.github.com>
Cc: roberto <roboluzzo@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [justdan96/tsMuxer] error-3 in mux ts (#295)


@roboluzzo<https://github.com/roboluzzo> what is your OS, and which is the latest bintray version without this error, e.g. 2020-04-28?

**Comment by justdan96** [comment]
I don't have any files that are that large to be able to test with - but if you are able to share the full details from mediainfo and ffprobe of a file, or possibly even the file itself, over email to myself at justdan96@gmail.com I might be able to reproduce the problem.

**Comment by jcdr428** [comment]
@justdan96 as there has been no answer from @roboluzzo to privide the required info, we should close the issue. @roboluzzo still has the option to request reopening.
