### ISSUE TITLE
DTS doesn't show when loading the playlist from an ISO file.

### ISSUE THREAD

**Issue by pwacooijmans** [justdan96/tsMuxer#296]
Dear Justdan96,

DTS does not show when loading the playlist of an ISO file created with tsMuxer.
Secondly since a few months the subtitles all have an unknown language in the latest version of KODI (leia) when opening directly from ISO created with tsMuxer. This was not the case a while ago.
This was tested with version 28-04 nightly.

Kind Regards and thanks in advance for fixing this,

Pieter Cooijmans

**Comment by justdan96** [comment]
Could you give a screenshot of the issue, along with steps to reproduce with some files <20MB? Just to be clear if these are 2 separate issues it's better to raise them as such, so we can track each individually.

**Comment by pwacooijmans** [comment]
I shall ask my college who is using tsMuxer if he can deliver the
screenshots

Op do 30 apr. 2020 14:35 schreef Dan <notifications@github.com>:

**Comment by pwacooijmans** [comment]
Issue has been fixed with the latest version, nevermind this issue :) You can close it sorry for the inconvenience.

**Comment by xavery** [comment]
> Issue has been fixed with the latest version, nevermind this issue :) You can close it sorry for the inconvenience.

Alright, I'm closing the issue in this case.
