### ISSUE TITLE
audio and subtitles not completely demuxed when demuxing together with video

### ISSUE THREAD

**Issue by hyllm** [justdan96/tsMuxer#299]
when demuxing together with video, last bytes of audio and subs are not demuxed... when demuxing, audio and subs separately, all is demuxed correctly...

**Comment by jcdr428** [comment]
@hyllm could you please test previous versions, and advise from which version we can see this behavior?

**Comment by hyllm** [comment]
will try today. :)

**Comment by hyllm** [comment]
ok.. so version "w64-nightly-2020-04-14--02-13-14" demuxes everything OK

**Comment by jcdr428** [comment]
@justdan96 is it possible to delete version w64-nightly-2020-04-14--02-13-14 from bintray ? There has been no commit on 13 April, I can't understand why this version is on bintray / to which code it corresponds. It is ennoying because several users have referred to this version to mention bugs.

**Comment by hyllm** [comment]
by git-version, it's the same as 2020-04-07

**Comment by jcdr428** [comment]
@hyllm yes but it does not give the same results https://forum.doom9.org/showthread.php?p=1907745#post1907745 so not the same version as 2020-04-07.
This is why it would be better to delete 2020-04-14.

**Comment by jcdr428** [comment]
@hyllm bug solved with commit #300, could you please close the issue.

**Comment by justdan96** [comment]
> @justdan96 is it possible to delete version w64-nightly-2020-04-14--02-13-14 from bintray ? There has been no commit on 13 April, I can't understand why this version is on bintray / to which code it corresponds. It is ennoying because several users have referred to this version to mention bugs.

I've deleted the files from this version from Bintray.
