### ISSUE TITLE
Ubuntu i386 libraries

### ISSUE THREAD

**Issue by qyot27** [justdan96/tsMuxer#3]
Ubuntu (well, I suppose Debian) provides the ability to do this automatically, without having to download a tarball.  It should be a matter of simply:
```
sudo dpkg --add-architecture i386
```

Even if the exact step might change in future versions due to the shakeups with i386 support.

**Comment by justdan96** [comment]
Are you able to validate this in a VM? With my testing even with i386 as an added architecture some files are missing.

**Comment by qyot27** [comment]
The following was sufficient on my normal install of Ubuntu 19.04 64-bit (based on the existing instructions in the README):

```
# add-architecture step performed before apt-getting the dependencies:

# download/install dependencies
sudo apt-get install build-essential \
flex \
libelf-dev \
libc6-dev \
binutils-dev \
libdwarf-dev \
libc6-dev-i386 \
g++-multilib \
qt4-qmake \
libqt4-dev \
libfreetype6-dev \
libfreetype6-dev:i386 \
checkinstall && \

# download source
git clone git://github.com/justdan96/tsMuxer.git && \
cd tsMuxer/tsMuxer && \

# build libmediation
cd libmediation && \
make -j$(nproc) && \

# compile tsMuxer
cd ../tsMuxer && \
make -j$(nproc) && \

# generate the tsMuxerGUI makefile and build
cd ../tsMuxerGUI && \
qmake && \
make -j$(nproc) && \

# install
cd ../bin && \
ln -s tsMuxeR tsmuxer && \
ln -s tsMuxerGUI tsmuxergui && \
    sudo checkinstall \
    --pkgname=tsmuxer \
    --pkgversion="1:$(./tsmuxer | \
                      grep "tsMuxeR version" | \
                      cut -f3 -d " " | \
                      sed 's/.$//')-git-$(\
                      git rev-parse --short HEAD)-$(\
                      date --rfc-3339=date | sed 's/-//g')" \
    --backup=no \
    --deldoc=yes \
    --delspec=yes \
    --deldesc=yes \
    --strip=yes \
    --stripso=yes \
    --addso=yes \
    --fstrans=no \
    --default cp -R * /usr/bin && \
mv *.deb ~/
```

Ideally, the build system will eventually be simplified and consolidated across platforms so that all that directory traversing is no longer necessary and stuff like install adheres to the FHS, but one thing at a time.

**Comment by justdan96** [comment]
Wow that's fantastic - I'll look to update the instructions soon!

**Comment by filler56789** [comment]
@qyot27: many thanks for the detailed info **THUMBS UP**

@justdan96: please add just two files to the directory "tsMuxer/src" — **zconf.h** && and **zlib.h**. Better than making the average user download and install the **zlib-devel** package.

**Comment by justdan96** [comment]
> @justdan96: please add just two files to the directory "tsMuxer/src" — **zconf.h** && and **zlib.h**. Better than making the average user download and install the **zlib-devel** package.

I'll have a look at that but I am wary to include external development dependencies in with the main package, as that means I have to keep them up to date with the upstream package instead of relying on the package maintainers for the user's OS.

**Comment by filler56789** [comment]
> I'll have a look at that but I am wary to include external development dependencies in with the main package, as that means I have to keep them up to date with the upstream package instead of relying on the package maintainers for the user's OS.

As I said, 1) only two files and 2) you like to make things more complicated than they actually are. Those two files are called by "matroska-whatever.*" and unless you yourself find a good reason to update it, you won't have to keep an eye on the "latest & greatest" revisions of zconf.h and zlib.h.
Be careful and don't let yourself get infected by Lord_Mulder's syndrome, which one day in the year 2012 invented absurd "reasons" to NOT change ONE BYTE in the file that contained the current /correct version of the software 😄

**Comment by qyot27** [comment]
I actually removed upx from the list for a reason, btw.  It's not a dependency, so it doesn't belong in a list of dependencies¹ (for that matter, some of the others in that list look a bit odd, but I didn't deep dive into it).  If the end user wants to be compulsive about packing their stuff down with upx to save a megabyte or two, that's their business, but it's not required in order to get a working build of tsMuxeR.

¹pre-emptively, yes, neither is checkinstall, but checkinstall is a package management tool.

**Comment by justdan96** [comment]
@qyot27 That makes sense, I'll remove the UPX packing
