### ISSUE TITLE
Muxing 2 * (Bluray-3D) : errors

### ISSUE THREAD

**Issue by vandenk** [justdan96/tsMuxer#301]
Hello,

I managed to muxer 2 bluray-3d titanic and also 2 bluray-3d hobbit 1, everything is fine.

But impossible to muxer hobbit 2 and hobit 3 !
Tested tsmuxer64-2020-04-30 and tsmuxer64-2020-05-09
![HOBBIT_DESOLATION_OF_SMAUG_PT2](https://user-images.githubusercontent.com/11425010/81990622-ca569780-963f-11ea-9761-354302b07291.jpg)
![HOBBIT_BATTLE_FIVE_ARMIES_PT3](https://user-images.githubusercontent.com/11425010/81990618-c75ba700-963f-11ea-866a-883205bf2411.jpg)

**Comment by vandenk** [comment]
Hobbit2: stops after first disc
Hobbit3: the part of the second disc jerks strongly

**Comment by jcdr428** [comment]
@vandenk Is it the same behavior with tsMuxer 2.6.12 ?
You should unselect "Insert SEI and VUI data" and "Continually insert SPS/PPS".

**Comment by vandenk** [comment]
I did not test tsmuxer 2.6.12 because it planted Titanic ...
I tested Hobbit 3 with tsmuxer64-2020-04-30 and tsmuxer64-2020-05-09 by unchecking "Continually insert SPS/PPS" but did not touch "Insert SEI and VUI data": same result.
I just tested Hobbit 3 with tsmuxer64-2020-05-09 by unchecking "Continually insert SPS/PPS" and "Insert SEI and VUI data": same result.
![HOBBIT_BATTLE_FIVE_ARMIES_PT3-2](https://user-images.githubusercontent.com/11425010/82036452-34ebef80-96a1-11ea-97e7-16a0fff256f7.jpg)

**Comment by jcdr428** [comment]
@vendenk could you please test with 2.6.12, so that we know whether it is a bug introduced by open-source commits (in which case you will have to test other intermediate versions to identify commit creating the bug), or it was old behavior (in which case the fault can also come from incorrectly remuxed H264).
Is it an original Bluray, or a compressed version by e.g. DVDFab ?

**Comment by vandenk** [comment]
Hobbit 3
Ok tested with 2.6.12 : no messages, same problem.
Even by reading the 00000.m2ts (2D), same problem.
![HOBBIT_BATTLE_FIVE_ARMIES_PT3-3](https://user-images.githubusercontent.com/11425010/82044206-37544680-96ad-11ea-951d-2b87855def96.jpg)
I just tested Hobbit 3 with tsmuxer64-2020-05-09 by unchecking "Continually insert SPS/PPS" and "Insert SEI and VUI data" in H264/MVC : same result.
![HOBBIT_BATTLE_FIVE_ARMIES_PT3-4](https://user-images.githubusercontent.com/11425010/82044300-62d73100-96ad-11ea-836d-a0ab92ac01d3.jpg)

Is it an original Bluray, or a compressed version by e.g. DVDFab ? : I can unfortunately not answer ... but I don't see the point of compressing ...  but I don't know.

**Comment by jcdr428** [comment]
@vandenk your file is not the original bluray and has been re-encoded: pic_order_cnt_lsb is the frame number in the GOP, and in a 23.976p Bluray it does not go above 24 = 1 second. The problem may be with the encode, you should try to mux from the original Bluray.

**Comment by vandenk** [comment]
Hobbit 2 disque 1 (english, french DTS-HD MA 7.1) : 22,7 Go
Hobbit 2 disque 2 (english, french DTS-HD MA 7.1) : 30,7 Go

Hobbit 3 disque 1 (english, french DTS-HD MA 7.1 + AC3 Hindi) : 29,8 Go
Hobbit 3 disque 2 (english, french DTS-HD MA 7.1 + AC3 Hindi) : 22.1 Go

I'm going to download another version to see ...

**Comment by vandenk** [comment]
New Hobbit 2 disque 1 :  34.25 Go
Disc Size:      36,763,419,161 bytes
Protection:     AACS
BD-Java:        Yes
Extras:         Blu-ray 3D
BDInfo:         0.5.8
PLAYLIST REPORT:
Name:                   00099.MPLS
Length:                 1:36:05.676 (h:m:s.ms)
Size:                   33,850,171,392 bytes
Total Bitrate:          46.97 Mbps
VIDEO:
Codec                   Bitrate             Description    
-----                   -------             -----------    
MPEG-4 AVC Video        25418 kbps          1080p / 23.976 fps / 16:9 / High Profile 4.1
MPEG-4 MVC Video        11429 kbps                          
AUDIO:
Codec                           Language        Bitrate         Description    
-----                           --------        -------         -----------    
DTS-HD Master Audio             English         4809 kbps       7.1 / 48 kHz / 4809 kbps / 24-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 24-bit)
Dolby Digital Audio             Czech           448 kbps        5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio             Hungarian       448 kbps        5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio             Polish          448 kbps        5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio             Russian         448 kbps        5.1 / 48 kHz / 448 kbps / DN -4dB
SUBTITLES:
Codec                           Language        Bitrate         Description    
-----                           --------        -------         -----------    
Presentation Graphics           English         50.323 kbps                    
Presentation Graphics           Czech           38.126 kbps                    
Presentation Graphics           Arabic          26.269 kbps                    
Presentation Graphics           Danish          39.729 kbps                    
Presentation Graphics           Estonian        36.408 kbps                    
Presentation Graphics           Finnish         39.572 kbps                    
Presentation Graphics           Hebrew          37.049 kbps                    
Presentation Graphics           Hungarian       44.836 kbps                    
Presentation Graphics           Icelandic       43.836 kbps                    
Presentation Graphics           Norwegian       41.579 kbps                    
Presentation Graphics           Polish          39.079 kbps                    
Presentation Graphics           Portuguese      45.849 kbps                    
Presentation Graphics           Romanian        41.814 kbps                    
Presentation Graphics           Russian         37.559 kbps                    
Presentation Graphics           Swedish         41.636 kbps                    
Presentation Graphics           Czech           1.682 kbps                      
Presentation Graphics           Hungarian       1.839 kbps                      
Presentation Graphics           Polish          0.000 kbps                      
Presentation Graphics           Russian         1.723 kbps    

New Hobbit 2 disque 1 :  30.55 Go
Disc Size:      32,789,634,047 bytes
Protection:     AACS
BD-Java:        Yes
Extras:         Blu-ray 3D
BDInfo:         0.5.8
PLAYLIST REPORT:
Name:                   00099.MPLS
Length:                 1:30:36.180 (h:m:s.ms)
Size:                   30,490,036,224 bytes
Total Bitrate:          44.87 Mbps
VIDEO:
Codec                   Bitrate             Description    
-----                   -------             -----------    
MPEG-4 AVC Video        24440 kbps          1080p / 23.976 fps / 16:9 / High Profile 4.1
MPEG-4 MVC Video        10499 kbps                          
AUDIO:
Codec                           Language        Bitrate         Description    
-----                           --------        -------         -----------    
DTS-HD Master Audio             English         4867 kbps       7.1 / 48 kHz / 4867 kbps / 24-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 24-bit)
Dolby Digital Audio             Czech           448 kbps        5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio             Hungarian       448 kbps        5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio             Polish          448 kbps        5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio             Russian         448 kbps        5.1 / 48 kHz / 448 kbps / DN -4dB
SUBTITLES:
Codec                           Language        Bitrate         Description    
-----                           --------        -------         -----------    
Presentation Graphics           English         32.854 kbps                    
Presentation Graphics           Czech           24.817 kbps                    
Presentation Graphics           Arabic          17.138 kbps                    
Presentation Graphics           Danish          26.720 kbps                    
Presentation Graphics           Estonian        23.883 kbps                    
Presentation Graphics           Finnish         26.214 kbps                    
Presentation Graphics           Hebrew          24.326 kbps                    
Presentation Graphics           Hungarian       29.067 kbps                    
Presentation Graphics           Icelandic       29.042 kbps                    
Presentation Graphics           Norwegian       27.270 kbps                    
Presentation Graphics           Polish          25.888 kbps                    
Presentation Graphics           Portuguese      29.467 kbps                    
Presentation Graphics           Romanian        27.849 kbps                    
Presentation Graphics           Russian         24.566 kbps                    
Presentation Graphics           Swedish         27.850 kbps                    
Presentation Graphics           Czech           0.944 kbps                      
Presentation Graphics           Hungarian       1.071 kbps                      
Presentation Graphics           Polish          0.245 kbps                      
Presentation Graphics           Russian         0.966 kbps  


it would be weird if it were re-encoded

**Comment by vandenk** [comment]
Hobbit 3 disque 1 (english, french DTS-HD MA 7.1 + AC3 Hindi) : 29,8 Go
MPEG-4 AVC Video 25937 kbps Left Eye / 1080p / 23.976 fps / 16:9 / High Profile 4.1
MPEG-4 MVC Video 11954 kbps Right Eye
DTS-HD Master Audio English 4811 kbps 7.1 / 48 kHz / 4811 kbps / 24-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 24-bit)
DTS-HD Master Audio French 2782 kbps 7.1 / 48 kHz / 2782 kbps / 16-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 16-bit)
Dolby Digital Audio Hindi 448 kbps 5.1 / 48 kHz / 448 kbps / DN -27dB

Hobbit 3 disque 2 (english, french DTS-HD MA 7.1 + AC3 Hindi) : 22.1 Go
MPEG-4 AVC Video 20120 kbps Left Eye / 1080p / 23.976 fps / 16:9 / High Profile 4.1
MPEG-4 MVC Video 15064 kbps Right Eye
DTS-HD Master Audio English 4599 kbps 7.1 / 48 kHz / 4599 kbps / 24-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 24-bit)
DTS-HD Master Audio French 2710 kbps 7.1 / 48 kHz / 2710 kbps / 16-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 16-bit)
Dolby Digital Audio Hindi 448 kbps 5.1 / 48 kHz / 448 kbps / DN -27dB

New Hobbit 3 disque 1 : 29.38 GB
MPEG-4 AVC Video 25937 kbps 1080p / 23.976 fps / 16:9 / High Profile 4.1
MPEG-4 MVC Video 11954 kbps
DTS-HD Master Audio English 4811 kbps 7.1 / 48 kHz / 4811 kbps / 24-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 24-bit)
Dolby Digital Audio French 448 kbps 5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio Spanish 448 kbps 5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio Portuguese 448 kbps 5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio Hungarian 448 kbps 5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio Polish 448 kbps 5.1 / 48 kHz / 448 kbps / DN -4dB

New Hobbit 3 disque 2 : 24.40 GB
MPEG-4 AVC Video 25956 kbps 1080p / 23.976 fps / 16:9 / High Profile 4.1
MPEG-4 MVC Video 11424 kbps
DTS-HD Master Audio English 4598 kbps 7.1 / 48 kHz / 4598 kbps / 24-bit (DTS Core: 5.1 / 48 kHz / 1509 kbps / 24-bit)
Dolby Digital Audio French 448 kbps 5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio Spanish 448 kbps 5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio Portuguese 448 kbps 5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio Hungarian 448 kbps 5.1 / 48 kHz / 448 kbps / DN -4dB
Dolby Digital Audio Polish 448 kbps 5.1 / 48 kHz / 448 kbps / DN -4dB


NOTE THAT THE VIDEO OF DISC 1 IS THE SAME IN THE 2 VERSIONS !
MPEG-4 AVC Video 25937 kbps
MPEG-4 MVC Video 11954 kbps
HOWEVER FOR DISC 2 IT HAS BEEN RECOMPRESSED ... SO I HAVE DOWNLOADED New Hobbit 3 disc 2, ADD THE DTS FRENCH AND MUXER THE 2 : ALL WORKS !
![TSMUX](https://user-images.githubusercontent.com/11425010/83188078-719ef880-a12f-11ea-93f9-a6ed527eac6f.jpg)

For Hobbit 2, it's disque 1 recompressed ....

**Comment by jcdr428** [comment]
@vandenk thanks, could you please close the issue if solved.

**Comment by vandenk** [comment]
ok
