### ISSUE TITLE
A standard track selection for 1 audio file and 1 subtitle.

### ISSUE THREAD

**Issue by pwacooijmans** [justdan96/tsMuxer#302]
Dear Justdan96,

Hereby I would like to ask for a feature request that adds the ability to select 1 audio and 1 subtitle file in a blu-ray iso for h265 and h264/avc to play automaticly upon starting the blu-ray.
This USED to be possible by placing the first audio track on the top of the list just below the Video track and the subtitle just below that one but it doesn't work anymore. So maybe you can improve it a bit and add the selection option to not force, but like in an mkv just play it automaticly as standard option.

Thanks for all your support and keep up the good work.

Kind regards,

Pieter Cooijmans

**Comment by xavery** [comment]
This is already implemented on master in the "Default tracks" section in the "Blu-ray" tab :
![image](https://user-images.githubusercontent.com/127875/82474838-eb9a0680-9acb-11ea-98e1-ed8147b0f9b4.png)

**Comment by pwacooijmans** [comment]
Thanks a lot :)

Op wo 20 mei 2020 18:59 schreef Daniel Kamil Kozar <notifications@github.com

**Comment by pwacooijmans** [comment]
Sorry for that stupid question...really amazed that you guys think of
everything :)

Op wo 20 mei 2020 19:02 schreef Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by xavery** [comment]
This was actually suggested over at the Doom9 forums, but thanks!

**Comment by xavery** [comment]
Closing this - feel free to open a new issue if you experience problems or have further suggestions.
