### ISSUE TITLE
Cheat Season 1 Audio problem

### ISSUE THREAD

**Issue by Nemesh64** [justdan96/tsMuxer#306]
Problem with audio after muxing.
1. I load the playlist from episode 1.
2. De-select the English subtitle
3. Select: Do not change SEI and VUI data.
4. Mux to new directory as BDMV folder.

So I keep Video+Audio.

tsMuxeR version git-0fa0738. github.com/justdan96/tsMuxer
Decoding H264 stream (track 1): Profile: High@4.1  Resolution: 1920:1080i  Frame rate: 25
H.264 muxing fps is not set. Get fps from stream. Value: 25
B-pyramid level 1 detected. Shift DTS to 2 frames
B-pyramid level 2 detected. Shift DTS to 3 frames
Decoding DTS-HD stream (track 2): Bitrate: 1536Kbps  core + MLP data.Sample Rate: 48KHz  Channels: 5.1 (DTS Master Audio 24bit)
Processed 66912 video frames
Flushing write buffer
Creating Blu-ray stream info and seek index
Creating Blu-ray playlist
Mux successful complete
Muxing time: 30 sec

When I playback the muxed result the audio is completely wron and out of sync.
Think this has to do with the pyramid level 1 and 2 and the  audio shift.
Video is 1080i@25 fps and the audio is DTS-HD Master Audio 5.1 (Sample Rate 48kHz - 24-Bit)

When Im do this with CloneBD they playback works fine

**Comment by jcdr428** [comment]
@Nemesh64 can you please provide a 40-50mb sample of the m2ts. You can cut the original m2ts with an hex editor eg HxD.

**Comment by Nemesh64** [comment]
Sorry for the very late reply but have been away for work some time.
I don't know how to do that... sorry...
But I can send the whole BD by a file transfer service.
But were must I send the link to?
Have attatched a screenshot on this reply.
Also, the video freezes after 10 seconds, no audio and a jump, then freezes again etc. etc.
Source is original BD.
Hope to hear from you and with regards,
Nemesh


![Screenshot](https://user-images.githubusercontent.com/23451125/87598395-6c076d00-c6f3-11ea-9ea3-0bfbea2a5da0.jpg)

**Comment by jcdr428** [comment]
@Nemesh64 if you upload the whole BD as an archive file, I won't be the one looking at the issue as I am on a metered connection... You could upload the m2ts only (I can download only part of it), or alternatively you can cut the m2ts file with an Hex editor, eg [HxD](https://mh-nexus.de/en/hxd/).

**Comment by Nemesh64** [comment]
The M2TS file from Episode 1 is 11.08GB.
I can split it with WinRAr and use a file-send service.
1. How big (max) can be each file?
2. To what email adress can I send the link for download?
I think splitting with the Hexeditor or WinRAR is the same.
If not, then please explain to me in detail how to use the HexEdit.
With regards,

Nemesh

**Comment by jcdr428** [comment]
@Nemesh64 I thought you would need all WinRAR files to uncompress the first file.
If not the case, you can split in 100 MB files and post the link here for the first file.

For HxD: see [picture](https://mh-nexus.de/en/graphics/HxDShotLarge.png)
You drag & drop your file in HxD, select the part you want to cut/discard, hit 'Delete' on the keyboard, and save the file with a new name.

**Comment by Nemesh64** [comment]
How large can I make each file?
Remember, episode 1 is 11,08 GB.

**Comment by Nemesh64** [comment]
All right......
Episode 1 is 11.08GB and a total of 22 RAR, ech file 500 MB.
Part 1: https://fil.email/ubiyfBwB

**Comment by jcdr428** [comment]
@Nemesh64 yes I could download the part 1. I don't need the other parts.
The bug is effectively existing since 2.6.12... I will see if I can do something.

**Comment by Nemesh64** [comment]
Many thank Jcdr, I hope you can do something about it.
As I wrote above, when I rip the episode from the BD with CloneBD there is no playback issue.
However, I can't add a subtitle.
With much regards,

Nemesh

**Comment by jcdr428** [comment]
@Nemesh64 please try https://github.com/jcdr428/tsMuxer/suites/1186063535/artifacts/17400781 and report whether it has solved your issue, thanks.

**Comment by jcdr428** [comment]
@Nemesh64 please confirm whether the issue is fixed, thanks.

**Comment by Nemesh64** [comment]
Hello jcdr,

Look almost every day here but I only now saw you request and I am deeply ashed of myself that I only saw you reply after 8 days.
Give you my sincere apologies and will try the build immediatly.
Will report back a.s.a.p.
With much regards,

Nemesh

**Comment by Nemesh64** [comment]
Just test on Cheat Season 1 Episode 1.
Works like a charm and no more problems with audio & video.
Many, many thank Jcdr.
With much regards,

Nemesh
