### ISSUE TITLE
Muxing to .ISO results in unplayable file.

### ISSUE THREAD

**Issue by Nemesh64** [justdan96/tsMuxer#307]
TsMuxer Nightly 25-06-2020 muxing a 4K/UHD movie  directly to a .ISO results in a unplayable .ISO
For playback with Windows MediaPlayer Classic I mounted the .ISO in Virtual CloneDrive 5.5.0.0
However, neither Windows MediaPlayer Classic or my Dune HD 4K Pro will play the file.
If I mux the same files to a Blu-Ray Folder everything plays fine.
Then I switched back to TsMuxer Nightly 25-06-2020 and muxed again to .ISO
and this time everything worked fine.

Settings for muxing are:
1. Video
2. Audio (2 tracks -> Dutch and English)
3. Dutch subtitle

The English audio- and Dutch- subtitle track are set to default.
Haven't tried this with a Blu-Ray movie.
Give you my best regards.

**Comment by lbnascimento** [comment]
This is happening because tsMuxer is incorrectly placing the M2TS file in the root directory of the image, instead of placing it in BDMV/STREAM.

**Comment by xavery** [comment]
Sorry about this - will be fine in tomorrow's nightly build.
