### ISSUE TITLE
Mistakenly detect a MPEG4-AVC H.264 encoded file as HDR10

### ISSUE THREAD

**Issue by xingchenli1996** [justdan96/tsMuxer#313]
Sometimes when I convert my original mp4 video clip with tsmuxer, the original file isn't HDR file at all, but the muxer itself mistakenly add an HDR10 information to the converted clip and make the clip unreadable on Scenarist and some other BLURAY-PLAYER

**Comment by xingchenli1996** [comment]
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
Format settings                          : CABAC
Format settings, CABAC                   : Yes
Format settings, GOP                     : N=1
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 4mn 6s
Bit rate mode                            : Variable
Bit rate                                 : 125 Mbps
Width                                    : 2 048 pixels
Height                                   : 1 152 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 2.206
Stream size                              : 3.58 GiB (100%)
Language                                 : English
Encoded date                             : UTC 2020-07-16 05:59:28
Tagged date                              : UTC 2020-07-16 05:59:28
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 4mn 6s
Source duration                          : 4mn 5s
Bit rate mode                            : Constant
Bit rate                                 : 317 Kbps
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 46.875 fps (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 9.31 MiB (0%)
Source stream size                       : 9.31 MiB (0%)
Language                                 : English
Encoded date                             : UTC 2020-07-16 05:59:30
Tagged date                              : UTC 2020-07-16 05:59:30


THIS IS THE ORIGINAL MP4 VIDEO CLIP AND IT ISN'T AN HDR FILE

**Comment by xingchenli1996** [comment]
Video
ID                                       : 4113 (0x1011)
Menu ID                                  : 1 (0x1)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
HDR format                               : SMPTE ST 2086, HDR10 compatible
Format settings                          : CABAC
Format settings, CABAC                   : Yes
Format settings, GOP                     : N=1
Codec ID                                 : 27
Duration                                 : 4mn 6s
Bit rate mode                            : Variable
Bit rate                                 : 123 Mbps
Maximum bit rate                         : 40.0 Mbps
Width                                    : 2 048 pixels
Height                                   : 1 152 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 24.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 2.180
Stream size                              : 3.54 GiB (89%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Mastering display color primaries        : R: x=1.159780 y=0.946620, G: x=0.840040 y=0.979220, B: x=0.155860 y=0.228800, White point: x=1.262840 y=0.502560
Mastering display luminance              : min: 322415.4473 cd/m2, max: 397427 cd/m2
Maximum Content Light Level              : 33744 cd/m2
Maximum Frame-Average Light Level        : 32407 cd/m2

Audio #1
ID                                       : 4352 (0x1100)
Menu ID                                  : 1 (0x1)
Format                                   : PCM
Format settings                          : Big / Signed
Muxing mode                              : Blu-ray
Codec ID                                 : 128
Duration                                 : 4mn 6s
Bit rate mode                            : Constant
Bit rate                                 : 2 304 Kbps
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Stream size                              : 67.6 MiB (2%)

Audio #2
ID                                       : 4353 (0x1101)
Menu ID                                  : 1 (0x1)
Format                                   : PCM
Format settings                          : Big / Signed
Muxing mode                              : Blu-ray
Codec ID                                 : 128
Duration                                 : 4mn 6s
Bit rate mode                            : Constant
Bit rate                                 : 6 912 Kbps
Channel(s)                               : 6 channels
Channel layout                           : L R C Ls Rs LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 24 bits
Stream size                              : 203 MiB (5%)

Text
ID                                       : 4608 (0x1200)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Delay relative to video                  : -84ms

HOWEVER, TSMUxER RECOGNIZES THIS CLIP AS AN HDR FILE, IT'S WEIRD

**Comment by jcdr428** [comment]
@xingchenli1996 please provide a sample of the original m2ts.

**Comment by xingchenli1996** [comment]
> @xingchenli1996 please provide a link for the file.
the original file is a little bit large and I need to take times to upload it somewhere

**Comment by jcdr428** [comment]
@xingchenli1996 I guess the 4mn 6s mp4 file on which you posted the mediainfo should be enough ?

**Comment by jcdr428** [comment]
@xingchenli1996 I would really like to have a sample of the H264 track, to understand how a HDR_metadata can end up in the stream.

**Comment by justdan96** [comment]
I guess a 20MB slice of the file should suffice?

**Comment by jcdr428** [comment]
@justdan96 without news / answer from @xingchenli1996, I believe we can close that issue. @xingchenli1996 can re-open if he comes again.

**Comment by ValZapod** [comment]
Newer file is also not HDR file. Overflown metadata is a bug in mediainfo but the point here is that transfer of BT.709 is SDR.
