### ISSUE TITLE
disk track information is only partially parsed 

### ISSUE THREAD

**Issue by lonecrane** [justdan96/tsMuxer#317]
Hi, I have encountered a blu-ray disk that cannot be parsed correctly by tsmuxer. Its subtitle trackers are not recognized by the latest tsmuxer but BDInfo can show the correct information.
![tsmuxer-1](https://user-images.githubusercontent.com/36885830/88754416-305bb100-d191-11ea-8aa4-3be7a516ff44.png)
![tsmuxer-2](https://user-images.githubusercontent.com/36885830/88754427-35b8fb80-d191-11ea-84f8-8b2c434ae6e6.png)
The following is the zipped file of the disk including the first 32MB of the largest M2TS file, can anyone help to have a look at it?
[http://www.mediafire.com/file/84r03acup7ct4fs/Demux_test.rar/file](url)

**Comment by xavery** [comment]
Unfortunately this doesn't seem resolvable without a full copy of the original BD, and I wasn't able to reproduce this with my own copy, as it's most probably simply a different release.
I'm going to leave this one unassigned if there's anyone else willing to do some work here.

**Comment by lonecrane** [comment]
@xavery Thanks a lot. Actually it is a DIYed BD released by a famous group, and I have encountered another BD with similar problem. Maybe the sample file is so short that it doesn't even contain any subtitle data. I am ready to upload a larger sample or even the full copy if you are willing to give it further study.

**Comment by jcdr428** [comment]
@lonecrane this is not a bug from tsMuxer. The 00000.mpls playlist does not include any subtitle track: when analysing the mpls with an hex editor or BDEdit, you will see that the number of PG files in the STN table is actually 0 !
The subtitle tracks are part of the clpi and m2ts but are "hidden", i.e. not accessible via the Blu-ray menu.

**Comment by lonecrane** [comment]
@jcdr428 Thanks a lot. The new sample including other relevant m2ts files and with a larger size of 128M has been uploaded to
[http://www.mediafire.com/file/h3vnotge4e2xaku/Parasite_2019_B%2526W_Version_Sample-128M.rar/file](url). I am uploading another larger sample in case of any need. When it is ready I will update this reply.
