### ISSUE TITLE
Option to add name to audio- and sub tracks.

### ISSUE THREAD

**Issue by Viking55** [justdan96/tsMuxer#318]
Option to name the tracks like in MKV Merge where there's a box "Track name" in which one can describe the track, e.g. AC3-5.1, color of subtitle, SDH, sup or srt etc. It's helpful when having several audio and/or sub tracks. What's written in that box shows up in VLC when choosing tracks. It's not showing on my Zidoo Z9S though, but that's a different issue I guess.

**Comment by jcdr428** [comment]
@Viking55 IMO this is not feasible. Each MPEG-TS descriptor for video, audio or subtitle is standardized in ISO/IEC 13818-1.

**Comment by Viking55** [comment]
Is there any possibility of "customization"? I'm way out of my league here, but, is everything else according to standardization?
Either way, I have to thank you all that have worked, and still do, on getting ts Muxer up to date. I understand that you have put in a lot of time and effort in getting here. Amazing job!

![Bow](https://user-images.githubusercontent.com/58627166/92287611-71837580-ef34-11ea-9691-8eae05743cb3.gif)

**Comment by xavery** [comment]
@Viking55 The difference lies in the file format. Matroska natively supports stuff like custom names for tracks, while MPEG-TS does not. Even if we added a "custom" descriptor to the streams tsMuxer produces, it would be essentially useless, since no other device/program would be able to read it.
