### ISSUE TITLE
Subtitle language

### ISSUE THREAD

**Issue by blackjack4494** [justdan96/tsMuxer#321]
For some reason when there are multiple subtitles only the first 5 subtitles have a language flag added. All those after the 5th subtitle do not. BDInfo shows me the language of all subtitles. The playlist file is totally fine and containing language flags for the subtitles.

Also noteworthy there are 5 audio tracks. 

However if I check other Movies with 5 audio tracks there are more than 5 subtitles language flagged but still not all.

**Comment by jcdr428** [comment]
@blackjack4494 Can you put some screenshots to clarify the issue. On my side I can output ts/m2ts/blurays that have 15 subtitle languages without problems.

**Comment by blackjack4494** [comment]
![tsmuxer](https://user-images.githubusercontent.com/4406639/90989787-b276a400-e59c-11ea-8142-0a37f7c97d20.png)

One example. @jcdr428 
I have other files with exact same problem. BDInfo, Handbrake etc all show everything right but tsmuxer.

**Comment by jcdr428** [comment]
@blackjack4494 I need a ~50MB sample of the m2ts to test.
You can cut the M2TS with an hex editor eg HxD: select data from address 0320 000 to the end, delete the data and save the file.

**Comment by jcdr428** [comment]
@xavery no answer from @blackjack4494. You can close this issue, the bug relates to tsMuxer 2.6.12.

**Comment by blackjack4494** [comment]
@jcdr428 Sorry I forgot this issue. Yes I downloaded the nighlty build and everything worked there. However where can you get 2.6.15? The latest official I can find is 2.6.12 all after this version seems to be nightly builds.

**Comment by jcdr428** [comment]
@blackjack4494 yes there is no official version yet working with UHD. You'll have to put pressure on @justdan96 to release 2.6.17 ;)
