### ISSUE TITLE
Adding French language to tsMuxeR

### ISSUE THREAD

**Issue by FRtranslator** [justdan96/tsMuxer#323]
Hi,
I would like to contribute by sending the French translation of tsMuxeR.
I did my best.
As I can't send files to the repo (unless you give me push/write access), I post them here.

Enjoy! :)
[french.zip](https://github.com/justdan96/tsMuxer/files/5126150/french.zip)

**Comment by xavery** [comment]
Merged in #324, thanks a lot!
