### ISSUE TITLE
Fixed little mistake in French translation

### ISSUE THREAD

**Issue by FRtranslator** [justdan96/tsMuxer#326]
Hey :)

I fixed a little typo in the French translation. Double-checked now, everything looks good.
Sorry guys ;)

[tsmuxergui_fr.zip](https://github.com/justdan96/tsMuxer/files/5135203/tsmuxergui_fr.zip)

**Comment by xavery** [comment]
Fixed in 818f916e7c0e803037e08def8a578fce12f77630, thanks.
