### ISSUE TITLE
audio track with delay +21000 " not recognized and ignored"

### ISSUE THREAD

**Issue by darekpro** [justdan96/tsMuxer#329]
Hello,

When I want create new blu-ray folder and I adding new audio track with delay +21000 after creating folder the same folder can not be open again in tsmuxer.

BDMV sample
https://drive.google.com/file/d/1ahX4_jtOihYTAyVKXj2hmAGg7jKRfVEx/view?usp=sharing

![Zrzut ekranu z 2020-09-01 11-32-39](https://user-images.githubusercontent.com/58607093/91833340-de51f380-ec46-11ea-8b11-36e830fb47d5.png)

**Comment by jcdr428** [comment]
@darekpro you need to grant access to your drive link.

**Comment by darekpro** [comment]
Upsss sorry :) done

**Comment by jcdr428** [comment]
tsMuxer scans the beginning of the m2ts to analyze the tracks. The size of the analyzed chunk is DETECT_STREAM_BUFFER_SIZE = 16 MB (line 42 of vod_common.h). With your delay of 21 ms, the AC3 track starts after this 16 MB chunk, so is not detected.

One solution would be to increase the buffer size, with the detrimental effect of increasing memory need / time needed to scan. An audio starting 21 sec. after video being quite uncommon, in such situation it would be preferable to append a 21 sec. "silence" AC3 before your AC3 track.

**Comment by darekpro** [comment]
"in such situation it would be preferable to append a 21 sec. "silence" AC3 before your AC3 track."
True but not with DTS-MA, TRUEHD itd :P

**Comment by jcdr428** [comment]
@darekpro True... I'll propose the one-line patch to increase buffer to 64 MB, let's see what @xavery thinks about this.

**Comment by xavery** [comment]
> @darekpro True... I'll propose the one-line patch to increase buffer to 64 MB, let's see what @xavery thinks about this.

Sounds okay, the whole algorithm should start with a small-ish value and gradually work its way up to larger ones anyway. However, since we have no real performance/memory usage targets, and no real way to compare memory usage across changes or versions, simply increasing the buffer size here is the natural way to go.

**Comment by jcdr428** [comment]
Thanks @xavery.
@darekpro could you please test latest bintray nightly, and close the issue if your problem is fixed.

**Comment by darekpro** [comment]
Perfect now everything it is ok. Thank you.
