### ISSUE TITLE
GUI crashes sometimes when removing a track or an input file

### ISSUE THREAD

**Issue by ettorps** [justdan96/tsMuxer#336]
In some cases the GUI crashes (segmentation fault) when clicking on either remove button from "Input files" or "Tracks".
Not every "remove" triggers the crash. If you have multiple input files, for example, it seems not to happen when you remove the files from bottom to top. Having only a single input file and removing it seems to trigger the crash in almost all cases.
In the "Tracks" section the "remove" is more likely to trigger the crash when randomly removing tracks "in the middle". If you remove track after track in order it seems to never happen.

I tracked it down to the Nightly Build 2020-02-10--01-10-49, there it happens the first time.
The Nightly Build 2020-02-08--01-09-39 does not have the problem.

I somehow think it has to do with this commit (but I have no evidence):
31d39b60a79f5b39cf357cdb91f42a17b737b4fe
(Implement support for default audio and subtitle tracks when muxing to Blu-ray)

Because there is also an issue with the select boxes for the default stream when removing tracks (which do not trigger the segmentation fault). The select boxes then often show streams which have been removed, which is fixed when randomly moving one track up and down again.

**Comment by ettorps** [comment]
Commit 31d39b60a79f5b39cf357cdb91f42a17b737b4fe indeed introduced this problem.
I just built the GUI from commit 0035efb243a72a085c67c965e1fcf9637a998593 and there the GUI is not crashing, whereas in a Build from commit 31d39b60a79f5b39cf357cdb91f42a17b737b4fe the GUI crashes.

**Comment by xavery** [comment]
@ettorps This should be fixed in [`2020-09-17--02-22-29`](https://bintray.com/justdan96/tsMuxer/tsMuxerGUI-Nightly/2020-09-17--02-22-29#files), please test and report back.

**Comment by ettorps** [comment]
@xavery: awesome, I just gave the new nightly build a try. The crash seems gone.
I could not produce any crash anymore.

But the default track select boxes still behave a little weird.
For example I just added a MKV file with 4 audio tracks. When I removed the first one, the "default audio" box still had 4 entries.
After I removed the 2nd track (still 2 audio tracks there) the "default audio" box had three entries.
In another try, when I removed a subtitle track, suddenly one of the audio tracks was listed in the "default subtitle" box.

**Comment by xavery** [comment]
> But the default track select boxes still behave a little weird.
> For example I just added a MKV file with 4 audio tracks. When I removed the first one, the "default audio" box still had 4 entries.
> After I removed the 2nd track (still 2 audio tracks there) the "default audio" box had three entries.
> In another try, when I removed a subtitle track, suddenly one of the audio tracks was listed in the "default subtitle" box.
I admit this is not my finest work. I found it really tricky to integrate this functionality with the existing code, so I'm sure there are still bugs here and there. I'll look into this.

**Comment by xavery** [comment]
@ettorps I just pushed a change that should fix what you're describing. It will be included in the 2020-09-18 nightly which should run in about two hours.

**Comment by ettorps** [comment]
Yes, it seems the select boxes are updated correctly.
Awesome, thank you for the effort to fix that.
