### ISSUE TITLE
Version 2.6 removes writing library entry

### ISSUE THREAD

**Issue by 55trucker** [justdan96/tsMuxer#349]
Hello:

came across an issue where version 2.6 will remove the h.264 writing library entry & also the encoder settings entry.
When viewed with Mediainfo the project *before* muxing & *after* muxing show this result.

Is there anything that can be done to correct this issue?

I use 2.6 for all of my *demuxing* needs but because of this behavior I have to use the older 1.10 to *remux* my projects to retain those 2 entries.

![Tsmuxer anomaly 1](https://user-images.githubusercontent.com/32821797/93712139-c83aa300-fb21-11ea-9766-db1fe07fba9e.jpg)

**Comment by jcdr428** [comment]
@55trucker please try [latest nightly](https://bintray.com/justdan96/tsMuxer/tsMuxerGUI-Nightly/_latestVersion#files), not 2.6.12.

**Comment by 55trucker** [comment]
Hello:

tried as you suggested, the latest nightly does precisely the same, removes both the writing library entry & the encoder settings entry.
This not something that is new, I first came across this anomaly when version 2.6 first appeared....what was it ...3 years ago?

**Comment by jcdr428** [comment]
@55trucker with the few files I've tries, Mediainfo shows these parameters for the ts muxed files.
So I need a 20-50 MB mkv sample of a problematic file to determine cause of issue. Thanks.

**Comment by 55trucker** [comment]
Well.......here's 2 screenshots of the same movie I have been working on....a before & after TsMuxer
![Bullitt before tsmuxer](https://user-images.githubusercontent.com/32821797/93767934-9dfee900-fbe6-11ea-897a-8ba3f5301aa2.jpg)
![Bullitt before tsmuxer](https://user-images.githubusercontent.com/32821797/93767952-a525f700-fbe6-11ea-8ced-83f8c5c6d817.jpg)

**Comment by jcdr428** [comment]
@55trucker as stated previously, I don't have this issue with any muxed ts/m2ts, see below example. So unless you provide a sample of a file having the issue I won't be able to help.
There might not be any problem with your file, but the bug could be specific to the file.

![Untitled](https://user-images.githubusercontent.com/56721609/93795797-32df0200-fc3a-11ea-9773-527301b19e07.jpg)

**Comment by 55trucker** [comment]
Ok, trying to send will be an issue ......the forum will not accept anything larger than 10mb.....the clip I made is 45mb.......but that's only 16secs long

**Comment by jcdr428** [comment]
@55trucker please just send a link eg onedrive, dropbox, wetransfer...

**Comment by 55trucker** [comment]
Let's try this.....haven't used Dropbox in years

https://www.dropbox.com/s/yqkhuxrl5lkfv8f/bullitt%20exerpt.mkv?dl=0

**Comment by jcdr428** [comment]
@55trucker Thanks, I have the sample. So the bug has something to do with the "insert SEI and VUI data if absent". I will look at it.
I always uncheck this option and the "continually insert SPS/PPS", for what purpose do you need to use this option?

**Comment by 55trucker** [comment]
Actually none, 
that is the default setting when installed.....I've never has reason to alter it.....apparently now I do.....lol

**Comment by 55trucker** [comment]
Cool! it worked!
I altered the *Insert SEI* to *Do not alter* & the issue is gone. I had no idea that this little alteration would solve this minor issue.

One other question.......the default size of the program window when opened is quite large, I can manually decrease the physical size but when one shuts down the program to come back to it later the default large window is there again. Is there a way to alter that?

**Comment by jcdr428** [comment]
@55trucker commit #352 should fix the bug. Once pushed, please test before closing the issue.
You'll have to open a new issue for the enhancement request (include window size info in init file).

**Comment by jcdr428** [comment]
@55trucker please confirm the issue has been fixed and close the issue, thanks.

**Comment by 55trucker** [comment]
Hello Dan:

issue appears to be resolved.......thx very much for your assistance

**Comment by justdan96** [comment]
Don't thank me thank @jcdr428 😀
