### ISSUE TITLE
Olympus Has Fallen - B-Pyramid now with 4K

### ISSUE THREAD

**Issue by Nemesh64** [justdan96/tsMuxer#356]
Have overhere the 4K version from Olympus Has Fallen.
Like the bug I previously reported for Cheat Blu-Ray,
I also get the same problem with this 4K.
The audio is not in sync.
Have made a screenshot: 

![Screenshot1](https://user-images.githubusercontent.com/23451125/94838997-ae993580-0416-11eb-924e-1927bcbba149.jpg)

l also added sample file (250MB): https://fil.email/3hGnsSEG

With much regards,

Nemesh

**Comment by jcdr428** [comment]
@Nemesh64 c139668 is 02/09 version, bug has been fixed 12/09. Simply use latest version.

**Comment by Nemesh64** [comment]
Got it.
Works fine now.
Downloaded the wrong version.
Best regards,

Nemesh

**Comment by jcdr428** [comment]
@Nemesh64 yes the b-pyramid message is normal.
Could you please close the issue, thanks.
