### ISSUE TITLE
Problem muxing files

### ISSUE THREAD

**Issue by Xavi1987** [justdan96/tsMuxer#357]
Hello,
I'm trying to mux 2 subtitle tracks and I get the following error.

I'm using macOS version

Thanks in advance.

![Captura de pantalla 2020-10-02 a las 17 22 53](https://user-images.githubusercontent.com/72267656/94941135-c800b700-04d4-11eb-9540-223b81ced246.png)

**Comment by xavery** [comment]
Have you tried a current version? The screenshot says you're using 2.6.11.

**Comment by xavery** [comment]
No reply for 10 days, closing.
