### ISSUE TITLE
shrink Tsmuxer window to smaller default size

### ISSUE THREAD

**Issue by 55trucker** [justdan96/tsMuxer#358]
Hello Dan:

how does one shrink the program window size to a something smaller & retain that smaller window size whenever one opens the program?, the older versions 1 have this ability.

In the attached pic is the *adjusted* window size, close the program & reopen it & the window is near twice the size.

thx 
![Tsmuxer window](https://user-images.githubusercontent.com/32821797/95014884-ecb17780-0617-11eb-8a3b-88d4b5c7a1d4.jpg)

**Comment by xavery** [comment]
Should be fixed by 03ecfba796215d0e9c97cd3453d8b27cba948693 , which will be included in tomorrow's nightly build.

**Comment by 55trucker** [comment]
Thx very much
