### ISSUE TITLE
Tsmuxer default output folder location

### ISSUE THREAD

**Issue by 55trucker** [justdan96/tsMuxer#363]
Hi there Dan:

the changes you've made have improved the user friendly flexibility of the program. I've come across one more small niggle, everything else functions great...

the default output folder that Tsmuxer processes the file into...... by default that would be the folder where Tsmuxer is actually placed.
The program has two alternatives for placing the completed work elsewhere  1. use the latest output folder name..(in other words ..the last folder that was used is now the default) 2. place output into an input (one has to manually select the input folder where the input file is actually sitting)
What we don't have is a selection where the default output folder is always the folder where the input file to be processed is presently placed. As of right now when starting a new project I have to continually tell the program to put the processed file into the same folder where the input file is sitting. The program will not do that by default.

**Comment by Viking55** [comment]
And to be picky, the **_a_** could be dropped in _a input folder._ If not, it should say **an**.
