### ISSUE TITLE
Custom chapters don't work when writing .mkv file to Bluray disc

### ISSUE THREAD

**Issue by craiglichtenstein** [justdan96/tsMuxer#366]
I'm producing a Bluray ISO from a single MKV file as input. In the Bluray tab, I am entering a list of 61 custom chapters. But when the ISO is produced and I play the m2ts file in VLC, no chapters are present. The arguments being used by tsmuxer (according to tsmuxer gui) are these:

MUXOPT --no-pcr-on-video-pid --new-audio-pes --hdmv-descriptors --blu-ray --vbr  --custom-chapters=00:00:00.000;00:02:34.000;00:05:04.000;00:08:45.000;00:10:58.000;00:15:36.000;00:18:05.000;00:22:46.000;00:24:42.000;00:28:14.000;00:31:25.000;00:34:49.000;00:37:46.000;00:41:06.500;00:43:39.000;00:47:31.000;00:51:32.000;00:55:52.000;00:58:23.000;01:01:53.000;01:05:16.000;01:09:48.000;01:12:52.000;01:16:25.000;01:19:06.000;01:23:14.000;01:27:35.000;01:30:36.000;01:33:15.000;01:37:26.000;01:40:56.000;01:46:10.000;01:48:35.000;01:52:14.000;01:54:18.000;01:59:38.000;02:03:04.000;02:08:26.000;02:11:30.000;02:15:11.000;02:19:07.000;02:22:57.000;02:26:04.000;02:28:53.000;02:33:00.000;02:36:30.000;02:38:39.000;02:42:59.000;02:46:18.000;02:49:52.000;02:52:37.000;02:55:44.000;03:00:54.000;03:05:29.000;03:09:23.000;03:13:14.000;03:15:19.000;03:17:55.000;03:21:24.000;03:25:15.000;03:28:45.000 --vbv-len=500
V_MPEG4/ISO/AVC, "F:\Videos\Yule Log Project\Movies\test5.mkv", track=1, lang=und
A_AC3, "F:\Videos\Yule Log Project\Movies\test5.mkv", timeshift=66ms, track=2, lang=und

This is on the latest build available from 10/07.

**Comment by jcdr428** [comment]
@craiglichtenstein strange... I've just tried on my side and it is working.
Just to make sure:
- you mount the .iso as a BD-ROM drive
- VLC Media ->Open Disk -> Blu-ray -> Play
- Change chapter in Media -> Chapter 
Is this correct ?

**Comment by craiglichtenstein** [comment]
When I tried that approach, I saw the chapter list in VLC. However, there are two problems:

1. Despite the video starting from the beginning, VLC's chapter menu (via Playback menu -> Chapter) shows the last chapter selected.
2. If I choose any chapter, the video just starts from the beginning.

**Comment by jcdr428** [comment]
@craiglichtenstein your mkv likely does not have AUD (access unit delimiters). Try to mux with insertSEI and contSPS and see if it works.

**Comment by craiglichtenstein** [comment]
The ISO worked with those settings. I'm burning the ISO to disc to see if it will playback in my LG Bluray player.

**Comment by craiglichtenstein** [comment]
To close the thread, the disc played perfectly. Guess the solution was a combo of updating tsmuxer to the latest build and the steps proposed by @jcdr428. @jcdr428  - thanks for the help.
