### ISSUE TITLE
Issue Adding Audio Track with Long Delay Time 

### ISSUE THREAD

**Issue by wang7000** [justdan96/tsMuxer#371]
感谢作者大大的辛勤工作，用这个软件很长时间了，非常感谢！！！
最近用这个软件为视频添加音轨的时候发现了一个问题：新添加的音轨如果延迟时间过长（大约是超过7842ms），视频合成后，添加的音轨无法被播放软件识别，提示是“some track not recognized”。

English translation: Thanks to the author for his hard work. I have used this software for a long time. Thank you very much! ! ! I recently discovered a problem when using this software to add audio tracks to videos: if the delay time of the newly added audio track is too long (approximately more than 7842ms), after the video is synthesized, the added audio track cannot be recognized by the playback software, and the prompt is " some track not recognized".

**Comment by justdan96** [comment]
Sorry @wang7000 I hope you don't mind but I translated your issue. Can you provide a sample under 20MB?

**Comment by jcdr428** [comment]
Closed due to lack of answer / sample.
