### ISSUE TITLE
tsMuxer removing file name after clicking "browse", leaving the box empty.

### ISSUE THREAD

**Issue by Viking55** [justdan96/tsMuxer#372]

**Comment by xavery** [comment]
Cannot reproduce : clicking the "Browse" button does not clear the input field where the file name is supposed to appear. The field is also not cleared when the "Save file" dialog is dismissed by clicking "Cancel".

**Comment by Viking55** [comment]
Hi,
even though you've closed the issue, I'd like to show you how it looks on my laptop.
Screenshot enclosed.
// Michael
Closed #372.

**Comment by xavery** [comment]
Please use the website to attach the screenshot, as it seems like mail attachments are ignored - nothing got attached to the issue. Thanks!

**Comment by Viking55** [comment]
Here's a screenshot of how it looks on my laptop.
![Save](https://user-images.githubusercontent.com/58627166/101478267-027a4a80-3983-11eb-8d89-afc6011319ab.jpg)

**Comment by xavery** [comment]
Thanks for the clarification - I honestly had no idea which box you meant in the original description. Should be okay now.

**Comment by Viking55** [comment]
Yes, it's ok now. Thanks. I should have included the screenshot to begin with of course. Next time, ok.
