### ISSUE TITLE
tsMuxeR failed to open TS files recorded by nextPVR

### ISSUE THREAD

**Issue by bernard0105** [justdan96/tsMuxer#374]
Hi,
I am testing nextPVR to replace WMC in my HTPC. NextPVR records TV shows in .ts files. Those files can be read by VLC, by Kodi etc. Mediainfo can also display the media structure within the files.
I plan to use tsMuxeR as a tool to cut begin and end of the record, and sometime also to join splitted records.
Unfortunately, tsMuxer is failling to open the files.
With those versions tsMuxer_w64-nightly-2020-09-23--02-23-55 and w64-nightly-2020-11-17--01-21-46.zip, it fails without any messages.
With the legacy version tsMuxeR_2.6.12, it fails with a popup error message :
`Error: Bitsream exception Unknown exception. It does not have to be`

Strangely, I have a 5mn records from nextPVR that can be openned by the R2.6.12 but not by the latest versions.
But in that case R2.6.12 failed to open the DVB subtitle tracks, with that Warning message : 
`Some tracks not recognized. This tracks was ignored`
I need to keep the subtitle in the target file.

Maybe it is a single problem related with the DVB subtitle tracks, or maybe it is 2 problems ?
I will put a link to the 5mn records and to a long record.
Thank you.

**Comment by bernard0105** [comment]
Here are the links on pCloud :
- [5mn video](https://u.pcloud.link/publink/show?code=XZd5iRXZz0SYET4zEozgi5cuA3Dei8dKwD0y)
- [long video](https://u.pcloud.link/publink/show?code=XZuJiRXZB3MCabYdaph2xM0W33UrazBmeESV)

**Comment by jcdr428** [comment]
Bonjour @bernard0105, aside from the fact that the detection of DVB subtitles does not work (yet), the error seems to be due to the DVB stream been falsely detected as a hevc stream, resulting in tsMuxer crashing without warning.
Please try again once the fix #380 has been merged, and report.
Merci !

**Comment by jcdr428** [comment]
@bernard0105 please try the latest bintray version and report, thanks.

**Comment by jcdr428** [comment]
@xavery despite @bernard0105 not coming back, I believe the patch fixed the issue and the issue can be closed. @bernard0105 can request to re-open if needed.
