### ISSUE TITLE
DV HEVC issue - secondary stream video frame timecode differs by xxxx ms

### ISSUE THREAD

**Issue by quinnmjcj** [justdan96/tsMuxer#379]
Using tsmuxer from 12/12/20 daily build (git-943a735) - but earlier builds exhibit this also.
Get a dolby video UDH 4K disk (doesn't matter - seems to happen on them all).
If you use makemkv to create an mkv - everything works fine.
Now - use tsmuxer and demux the 2 video streams.
Then - use tsmuxer to remux the 2 streams into a bluray disk.
Now use makemkv to extract an mkv from that disk - You get timecode errors - seems to always be at 47:47.573 where it starts, which is suspicious.

AV synchronization issues were found in file 'V:/Video/test1/title_t00.mkv' (title #1)
AV sync issue in stream 0 at 0:47:47.573 : video frame timecode differs by -0.1ms
AV sync issue in stream 0 at 0:47:47.573 : secondary stream video frame timecode differs by -83.511ms
AV sync issue in stream 0 at 0:47:47.739 : secondary stream video frame timecode differs by -0.1ms
AV sync issue in stream 0 at 0:47:47.739 : secondary stream video frame timecode differs by +41.611ms
AV sync issue in stream 0 at 0:47:47.906 : secondary stream video frame timecode differs by -0.1ms
AV sync issue in stream 0 at 0:47:47.906 : secondary stream video frame timecode differs by +166.733ms
AV sync issue in stream 0 at 0:47:47.906 : secondary stream video frame timecode differs by +83.322ms
AV sync issue in stream 0 at 0:47:48.240 : secondary stream video frame timecode differs by -0.1ms
AV sync issue in stream 0 at 0:47:48.240 : secondary stream video frame timecode differs by +41.611ms
AV sync issue in stream 0 at 0:47:48.407 : secondary stream video frame timecode differs by -0.1ms
AV sync issue in stream 0 at 0:47:48.407 : secondary stream video frame timecode differs by +166.733ms
AV sync issue in stream 0 at 0:47:48.407 : secondary stream video frame timecode differs by +83.322ms
AV sync issue in stream 0 at 0:47:48.740 : secondary stream video frame timecode differs by -0.1ms

All future frames have this "issue".
Unclear if this actually causes a DV problem but it seems really wierd.

**Comment by quinnmjcj** [comment]
Update - if I extract the streams (using tsmuxer) from this re-created bluray - they're exactly the same as the original streams that were used to mux the bluray (as one would expect).  So this means there's something slightly different about the muxed bluray that makemkv sees as timecode variances (I'm assuming somehow the timecodes of the 4K and the 1080p streams got out of sync), but how they're "fixed" on re-extraction is a bit bizarre.

**Comment by justdan96** [comment]
@quinnmjcj can you confirm this is still an issue with the latest build?

**Comment by quinnmjcj** [comment]
Seems to work ok - probably take a few more movies to be sure, but so far, so good.

**Comment by quietvoid** [comment]
This is still an issue on the 7dcca4876e7553d543dbb15020ee4bffbc7312a3 but to me it sounds like the bug is at MakeMKV, not here.
Someone else brought it back up over at MakeMKV so I'm bumping it here.

Quoting my post:
> I'm able to reproduce the issue and it's probably a MakeMKV bug.
The enhancement layer (second video stream in M2TS) is not being read properly, resulting in a truncated file and the timecode errors.

> Not sure what the cause is yet. The m2ts file produced by tsmuxer is fine and extracts to identical bitstreams using ffmpeg.
While using MakeMKV on the tsmuxer BD folder, the first video is slightly different and the second stream is truncated after that 47min timecode.

> 18,909,787,230 BL_orig.hevc
    18,910,513,800 BL_makemkv.hevc
    18,909,787,230 BL_tsmuxer.hevc

> 2,136,462,803 EL_orig.hevc
    1,787,196,925 EL_makemkv.hevc
    2,136,462,803 EL_tsmuxer.hevc

Though it is definitely strange that MakeMKV only behaves weirdly on tsmuxer BD folders.
