### ISSUE TITLE
TsMuxer muxing blu-ray iso

### ISSUE THREAD

**Issue by bairradino** [justdan96/tsMuxer#386]
I tried to get a Blu-ray iso from my UHD-HLG mp4 video file but when starting muxing I get "tsMuxer finished with error code -1073741819" error.
What am I doing wrong? Here the characteristics of my video file:

General
Complete name : E:\Blu-Ray\Casamento_UHD.mp4
Format : MPEG-4
Format profile : Base Media / Version 2
Codec ID : mp42 (isom/mp42)
File size : 16.2 GiB
Duration : 38 min 22 s
Overall bit rate mode : Variable
Overall bit rate : 60.4 Mb/s
Encoded date : UTC 2020-12-22 23:06:54
Tagged date : UTC 2020-12-22 23:06:54

Video
ID : 1
Format : HEVC
Format/Info : High Efficiency Video Coding
Format profile : Main@L5@High
Codec ID : hvc1
Codec ID/Info : High Efficiency Video Coding
Duration : 38 min 22 s
Bit rate : 60.2 Mb/s
Width : 3 840 pixels
Height : 2 160 pixels
Display aspect ratio : 16:9
Frame rate mode : Constant
Frame rate : 25.000 FPS
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Bits/(Pixel*Frame) : 0.290
Stream size : 16.1 GiB (100%)
Language : English
Encoded date : UTC 2020-12-22 23:07:04
Tagged date : UTC 2020-12-22 23:07:04
Codec configuration box : hvcC

Audio
ID : 2
Format : AAC LC
Format/Info : Advanced Audio Codec Low Complexity
Codec ID : mp4a-40-2
Duration : 38 min 22 s
Bit rate mode : Variable
Bit rate : 192 kb/s
Maximum bit rate : 521 kb/s
Channel(s) : 2 channels
Channel layout : L R
Sampling rate : 48.0 kHz
Frame rate : 46.875 FPS (1024 SPF)
Compression mode : Lossy
Stream size : 52.0 MiB (0%)
Language : English
Encoded date : UTC 2020-12-22 23:07:04
Tagged date : UTC 2020-12-22 23:07:04

**Comment by jcdr428** [comment]
@bairradino can you please give a link to download a sample  (20-50 MB is enough) of the hevc stream -not of the mp4 file.

Also, were the previous tsMuxer versions working ?

**Comment by bairradino** [comment]
I didn't try older versions.
I Demuxed the mp4 file with tsMuxer, and then tried to Mux to Blu-ray Iso.
Here the files:
https://1drv.ms/u/s!AuYcZ0yHv3DtbTSqlQUJnUbe55c?e=Y2M0CD

**Comment by jcdr428** [comment]
Ok. Thanks @bairradino for the sample, this is the first time I try a HLG stream with tsMuxer !

Should be fixed with #387 , please wait for it to be merged then report to confirm whether this has solved the issue.

**Comment by bairradino** [comment]
I must wait for the new release, right (not the one of today)?
Can I continue to use the GUI or I must use the command line (is not to friendly for me)?

**Comment by jcdr428** [comment]
Just watch #387 , when the top left green "Open" becomes a blue "Merged" then you can download the [Bintray nightly](https://bintray.com/justdan96/tsMuxer/tsMuxerGUI-Nightly/_latestVersion#files) (including GUI) the next morning.

**Comment by bairradino** [comment]
Wonderful.
Thanks.

**Comment by bairradino** [comment]
I tried with Bintray nightly of today, and didn´t work with samples I gave you.
Same error.

**Comment by jcdr428** [comment]
@bairradino you have to wait for the fix #387 to be merged by @xavery to the master branch.

**Comment by jcdr428** [comment]
@bairradino the patch has been merged, please try the Bintray 29-12 tomorrow.

**Comment by bairradino** [comment]
It seems to work.
I'm not sure about color rending but I will test it more careful when having material long enough.

**Comment by jcdr428** [comment]
Ok. @bairradino please close this issue, and you can open a new issue if there is a problem with the HLG color rendering.

**Comment by jcdr428** [comment]
@xavery this issue can be closed.
