### ISSUE TITLE
Bintray is shutting down

### ISSUE THREAD

**Issue by xavery** [justdan96/tsMuxer#397]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Bintray will not be accepting any new submissions (I'm assuming this also means new package versions) after the 28th of February.
We should probably move to use GitHub Releases for hosting the nightly builds : appropriate actions (for example [create-release](https://github.com/actions/create-release)) in the workflows can be configured to create a new release and upload the binaries. I have investigated this a bit when refactoring the nightly scripts, but finally decided to stick to Bintray since there were no real reasons not to.

Unless somebody has any objections or other suggestions, I'll work towards this in the following weeks, and make an official announcement on Doom9 when the move is done.

**Comment by xavery** [comment]
All nightly builds are now available as GitHub Releases. Each commit which was used as the source of a nightly build is also tagged with a `nightly-xxx` tag.

**Comment by jcdr428** [comment]
Very good.
We'll have the usual complaints and conspiracy theories on Doom9 regarding the fact that people need to log in to GitHub.

**Comment by xavery** [comment]
Actually, no. Downloading *releases* (as opposed to build artifacts from workflow runs) does not require an account on GitHub. Try going to the [tsMuxer releases site](https://github.com/justdan96/tsMuxer/releases) in incognito mode and see for yourself. :-)

**Comment by justdan96** [comment]
Great to see us resolving this so quickly! I thought we'd be looking at alternatives for ages :smile:

**Comment by xavery** [comment]
The builds failed due to a `Skip output 'upload_url' since it may contain secret` error, most probably caused by the repository's set of secrets. @justdan96 was notified about this, since he's the only one who can access and/or remove secrets.

**Comment by xavery** [comment]
The README now points to the GitHub releases page, and both builds yesterday passed - as such, this can be closed and we can now consider ourselves fully migrated.
