### ISSUE TITLE
Audio Conversion from E-AC3(DD+) to AC3 removes sound

### ISSUE THREAD

**Issue by nstephenh** [justdan96/tsMuxer#398]
This could be user error, but I've been trying to author a disk for a while now and VLC won't play any of the ISOs I've made. I decided to poke around in it a bit and the stream directory is populated as expected and the file plays properly, but there are no files in the playlist directory. Do I need to trigger the creation of these files somehow, or is this a glitch or a problem with my source files?

Thanks,
Noah 

Nightly 20201-02-04-01-46-17

**Comment by jcdr428** [comment]
@nstephenh can you please post a link for a sample of the source file ?

**Comment by nstephenh** [comment]
Update:
Video I ripped from youtube generates a playlist file, so its definitely a me/my file problem. Also, using folder mode and doing a failed conversion 
The file is encoded with E-AC3(DD+) audio. Apparently I was getting an error marked as "Unsupported media type 135 for AVCHD/Blu-ray muxing" which I assumed was a warning that it may not properly play on some players. This is apparently the reason that the playlist file wasn't being generated, though the log still writes the following and the only indication that it's a fail to me is the tone being played is different. As I hadn't heard the correct tone, I didn't know there was anything wrong. Perhaps printing a more straightforward failure indication might help avoid others making this mistake.
```
Creating Blu-ray stream info and seek index
Creating Blu-ray playlist
```

 After reading some info on the error, I enabled Down conversion. Unfortunately, this appears to remove the audio. Is there a recommended way to convert the audio in as lossless a way as possible?

Here's a piece of the file I've been trying to convert.
https://drive.google.com/file/d/1lNqq23s0D0QiTC2t1En3K9Pof1_pEYHX/view?usp=sharing

**Comment by jcdr428** [comment]
@nstephenh yes the problem comes from the fact that theBlu-ray spec does not support pure DD+ (E-AC3).
You would have to convert your pure DD+ to a DD+ with DD(AC3) core or to a DD, with ffmpeg or eac3to, before muxing with tsMuxer.

**Comment by nstephenh** [comment]
Alright then, I'll put my solution here for the next person to stumble across. This was just the first solution I found when googling, if there are settings I could change to get a better output result please let me know.

```
for file in *.mkv
do
ffmpeg  -hwaccel auto -y -i "${file}" -map 0 -c:s copy -c:v copy -c:a ac3 -b:a 640k "AC3 ${file}"
done

```

I do think the error should be made more distinct, and perhaps remove the output file so that someone like me doesn't try to use the unusable output.
Another thing would be a check to determine whether or not the audio will convert properly when you enable down conversion, so you don't get a successful dump with no audio.  

Thanks for your help.

**Comment by ValZapod** [comment]
> You would have to convert your pure DD+ to a DD+ with DD(AC3) core or to a DD,

BTW, does Atmos EAC3 on Blu-ray also use dependent streams? No, AFAIK.



> I'll put my solution

Alas, ffmpeg does not support 7.1 EAC3 encoding, only decoding, including with AC3 core. See: 
https://trac.ffmpeg.org/ticket/3595

**Comment by justdan96** [comment]
@jcdr428 is it detecting that the E-AC3 is present? If not is that something that would be straightforward to do?

**Comment by jcdr428** [comment]
@justdan96 pretty straightforward, fixed in commit 2aa293b

**Comment by ValZapod** [comment]
> BTW, does Atmos EAC3 on Blu-ray also use dependent streams?
> 
> >


Since we now have Atmos open source decoder, I verified Atmos in EAC3 is not dependent stream, it does not depend on AC3 in any way!! https://github.com/VoidXH/Cavern

**Comment by jcdr428** [comment]
> Edit: when pure E-AC3 (i.e. core 0Kbps), the "downconvert E-AC3 to AC3" should also be greyed out in the GUI. This is less straightforward and stil to be done. Leaving this issue open.

Fixed with commit 2c58285, closing.

**Comment by ValZapod** [comment]
BTW, I was after all wrong, I read some documentation and apparently AC3 is always present for Blu-ray. It is just part of EAC3 stream, you can understand that it is the case yby looking into mediainfo' mediatrace and looking into strmtup, if it is 1 you are looking into Blu-ray ac3+eac3 stream.

**Comment by jcdr428** [comment]
@ValZapod correct, strmtyp 1 just means dependent stream.
