### ISSUE TITLE
AVCHD same as UHD Blu-Ray option?

### ISSUE THREAD

**Issue by michaelsft** [justdan96/tsMuxer#403]
Hi there, sorry if this is totally the wrong place to ask this but I saw some screenshots on here that had an option to create UHD files but when I look at my copy of tsMuxer (a recent nightly build) it only has AVCHD. Is this the same thing? I've a 4k mkv that I want to put on a BDXL but getting it from mkv to UHD is challenging as the information I've found is a little hard to come by and vague. Lots of Blu-Ray 1080p talk and little else.

I guess if these BDMV and CERT files it spat out are right then the next step is burning them onto the disc. I've found some information about this and how UHD players tend to only read the first 2 layers but fortunately this mkv is less than 60GB so that shouldn't be a problem. Just need to find the right burning software to make a UHD compliant disc then...

**Comment by jcdr428** [comment]
@michaelsft AVCHD is a different format than Blu-ray.
Just select Blu-ray (ISO or Files) and it will detect UHD automatically.

**Comment by michaelsft** [comment]
Got it, thanks jcdr. I'll create a BD ISO and use ImgBurn and hopefully everything will work out just fine.

**Comment by jcdr428** [comment]
@michaelsft or @xavery please close the issue, thanks.

**Comment by xavery** [comment]
Closing as requested.
