### ISSUE TITLE
3D issue in 64bit Windows ver

### ISSUE THREAD

**Issue by cob66** [justdan96/tsMuxer#404]
There is a bug in 3D muxing. ISO file is played as 4K 2D instead of 1080 3D.
32bit version works well.

**Comment by jcdr428** [comment]
@cob66 I cannot reproduce. Can you please upload the buggy 64bit output iso and the working 32bit output iso.
Preferrably a small sample.

**Comment by jcdr428** [comment]
No sample provided, can't debug. Closing.
