### ISSUE TITLE
Force BD-ROM V3 - UHD Compliant

### ISSUE THREAD

**Issue by michaelsft** [justdan96/tsMuxer#406]
Hi there, I've been advised that by checking this box I can make my 4k MKV 'UHD Compliant' when exporting as either an iso or folders. I was also told it was make the iso UDF 2.60 but in ImgBurn it still comes out as UDF 2.50 and the video skips in my Panasonic UB450 (which can play BDXL discs). In ImgBurn I can add the folders in and set the UDF to 2.60 manually but the disc shows up as the folders and doesn't play on the Panasonic. So I can either burn 2.60 and see folders or burn 2.50 iso and play a stuttering video.

Is ticking this box meant to make a UDF 2.60 iso and if not, is there an option in tsMuxer to make it 2.60 that I'm missing?

**Comment by justdan96** [comment]
Can you attach the log from when you are creating the file?

**Comment by jcdr428** [comment]
@michaelsft You have to burn Blu-ray movies with UDF 2.5. Use 2.6 for file storage.
A UHD BD-Rom 100GB has a transfer rate of up to 128 Mbps, so you have to use BDXL with 4x read speed on the whole of the disk -not e.g. a 2x-4x which will achieve the 4x on the external side of the disk.
