### ISSUE TITLE
Bug with Nightly build from 2021-02-13-01-46-27

### ISSUE THREAD

**Issue by vandenk** [justdan96/tsMuxer#414]
Stereoscopic Player 2.5.1 sees no subtitle !
it's ok with versions tsmuxer64-2020-11-05--01-21-49 and tsmuxer64-2020-10-07--02-32-42 ... 

3D blu-ray remux.
Windows64.

**Comment by jcdr428** [comment]
@vandenk can you test various builds and identify which build created this bug ?

**Comment by vandenk** [comment]
Yes I download : https://www4.yggtorrent.li/torrent/film-video/film/331272-skyscraper+2018+multi+3d+full+bluray+1080p+avc+truehd+atmos+7+1-hodl

After download I put in DVDFab 11.0.8.5 (film principal) : save in .iso

Open the new .iso with tsmuxer64-2021-02-13-01-46-27 remove VFQ and add VFF (eac3) and remux : Stereoscopic Player 2.5.1 sees no subtitle.

I also opened the new .iso with tsmuxer64-2021-02-13-01-46-27 (nothing done) and remux : Stereoscopic Player 2.5.1 sees no subtitle.

tested both with tmuxer64-2020-11-05--01-21-49 and tsmuxer64-2020-10-07--02-32-42 : Stereoscopic Player 2.5.1 sees the subtitles.

On the other hand I took again the iso of tmuxer64-2020-11-05--01-21-49 and tsmuxer64-2020-10-07--02-32-42 remux with tsmuxer64-2021-02-13-01- 46-27 : the subtitles are OK ... 

The other iso works well ...

**Comment by jcdr428** [comment]
@vandenk most of us don't have 3D / Stereoscopic Player.
There are too many versions between 2020-11-05 and 2021-02-13.
Please download the tsMuxer versions on https://bintray.com/justdan96/tsMuxer/tsMuxerGUI-Nightly, and try to find out which version / commit resulted in the subtitles not working in the player.
E.g. version 2020-31-12 is working => try version 2021-01-15. Not working => try version 2020-12-15 etc until two successive versions give different results.
Thanks.

**Comment by justdan96** [comment]
If there is no reply I'll close due to aging
