### ISSUE TITLE
Is there a way to add the option "3d-pg-planes: 32" MVC ?

### ISSUE THREAD

**Issue by vandenk** [justdan96/tsMuxer#416]
PGS subtitle problem in 2D (iso 3D AVC MVC).

Reading the .mpls file we see that there is a problem with the MVC track, it is missing "3d-pg-planes: 32", the subtitles not the "plane #" option ...
![Tsmuxer1](https://user-images.githubusercontent.com/11425010/118166172-6e2a7d00-b425-11eb-8542-445832f411a6.png)
Same in the .ssif
![Tsmuxer2](https://user-images.githubusercontent.com/11425010/118166182-6f5baa00-b425-11eb-9b93-fcfdc40c403d.png)
A normal 3D blu-ray
![Tsmuxer3](https://user-images.githubusercontent.com/11425010/118166183-6f5baa00-b425-11eb-824b-0ab781d5c951.png)

Is there a solution ?

**Comment by jcdr428** [comment]
@vandenk as explained on doom9.org, the 3D planes are detected from the metadata in the clpi and in the m2ts. There is no point giving the option to select a plane number for which there is no corresponding metadata.

**Comment by vandenk** [comment]
Ok
