### ISSUE TITLE
Muxing stuck at 10.7%

### ISSUE THREAD

**Issue by DocteurLo** [justdan96/tsMuxer#440]
Hello,

While muxing a mkv 1080p file to a Blu-ray iso, the muxing stops at 10,7%.
It's a h264 video with 3 AC3 audio tracks and 2 subtitle tracks.
I tried many combinations: without subtitles, with only one audio track, without any audio and even without the video track.
I tried changing the vbv buffer size.

Whatever I did, the muxing stops around 10,7 or 10,9%.
I got this problem before and it was always because of the subtitle track, not encoded correctly.

This time, I really can't find where the problem is.

It's the first time I post here so please tell me if I did anything wrong.
I join some pics of the process. If there's some way to debug I would be glad to help.
I tried in the 'Console' app but couldn't find TSMuxerGui.

I use the last Mac version : mac-Nightly-2021-04-30-02-13-20

<img width="1486" alt="Capture d’écran 2021-06-01 à 23 58 27" src="https://user-images.githubusercontent.com/85199483/120395493-60398f00-c335-11eb-9d1d-aca73c6397e4.png">

<img width="877" alt="Capture d’écran 2021-06-01 à 23 50 07" src="https://user-images.githubusercontent.com/85199483/120395393-32ece100-c335-11eb-8f6b-b1125bcf3d88.png">

**Comment by jcdr428** [comment]
@DocteurLo can you please upload the mkv to a cloud service (e.g. your Google or Microsoft Drive) and provide the link ? I will have a look.

**Comment by DocteurLo** [comment]
OK. Meanwhile I give you some information about the media.
<img width="812" alt="Capture d’écran 2021-06-02 à 14 19 39" src="https://user-images.githubusercontent.com/85199483/120479192-f3161000-c3ad-11eb-93cd-88212fa6c703.png">
<img width="407" alt="Capture d’écran 2021-06-02 à 14 20 55" src="https://user-images.githubusercontent.com/85199483/120479194-f4473d00-c3ad-11eb-9437-141ed7b5b6bd.png">
<img width="532" alt="Capture d’écran 2021-06-02 à 14 21 02" src="https://user-images.githubusercontent.com/85199483/120479195-f4473d00-c3ad-11eb-8d4b-e86c0aaacb72.png">
<img width="319" alt="Capture d’écran 2021-06-02 à 14 21 12" src="https://user-images.githubusercontent.com/85199483/120479197-f4dfd380-c3ad-11eb-96b3-8a8e11dc1b33.png">
<img width="318" alt="Capture d’écran 2021-06-02 à 14 21 22" src="https://user-images.githubusercontent.com/85199483/120479198-f5786a00-c3ad-11eb-961c-77df49e6ff11.png">
<img width="291" alt="Capture d’écran 2021-06-02 à 14 21 35" src="https://user-images.githubusercontent.com/85199483/120479202-f6110080-c3ad-11eb-8678-828bf6362833.png">

**Comment by DocteurLo** [comment]
> @DocteurLo can you please upload the mkv to a cloud service (e.g. your Google or Microsoft Drive) and provide the link ? I will have a look.

It's a 10Gb file. It's uploading. 40 minutes to go...
I'll send you the link by PM.
Thanks.

**Comment by DocteurLo** [comment]
I don't want to put the link in public.
How can I send you a private message?  I don't see where I can send you a PM.

**Comment by jcdr428** [comment]
@DocteurLo you can PM me on doom9, user a5180007

**Comment by DocteurLo** [comment]
OK. I just created an account on doom9, but I'm still waiting for the activation email. It was half an hour ago so I'm worried I never receive it.
Furthermore, they say the new accounts remain limited for five days...
So we'll have to wait a little for this PM. :-/

**Comment by DocteurLo** [comment]
@jcdr428 Hi, the registering on doom9 doesn't seem to work. I didn't receive any email, so I cannot confirm it. And I don't see any way to ask to resend this verification email. May I message you otherwise ?

**Comment by jcdr428** [comment]
@DocteurLo please send me an email now on ikd43404@zwoho.com (10min. email).

**Comment by DocteurLo** [comment]
@jcdr428 ok, I sent you the link.
Please tell me when you're done with it, so I can delete it.
Thanks.

**Comment by DocteurLo** [comment]
@jcdr428 Hi, Do you think this bug is fixable?
How is it possible that the blocksize = 0 ? May I modify the file in a way that change this blocksize?
Thanks again for your help.

**Comment by jcdr428** [comment]
@DocteurLo yes the bug is fixed with the proposed patch, you just have to wait for the patch to be merged by @xavery -or compile yourself if you know how to do it.

**Comment by DocteurLo** [comment]
Ok, thanks for the info. Now I understand.
Do you know when the next release will be out?
Or do you have a link to "how to patch"?..
Or a Mac software name that could help me edit this "matroskaParser.cpp" according to the fix ? I tried XCode but without success...

**Comment by DocteurLo** [comment]
@jcdr428 Ok, I found the file already compiled in the bug thread. Sorry, I'm new to this. 
Thanks for the quick solving. It seems to work (muxing still going on). Thanks a lot!

**Comment by jcdr428** [comment]
@DocteurLo Avec plaisir. Thank you for reporting the bug !
