### ISSUE TITLE
Library not found on macOS

### ISSUE THREAD

**Issue by SubJunk** [justdan96/tsMuxer#443]
Hi, I'm trying to resolve a problem reported by users of Universal Media Server, which is this error on macOS:

```
Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
Referenced from: /Applications/Universal Media Server.app/Contents/Resources/osx/tsMuxeR
Reason: image not found
```

Is there a reason why these builds are not fully static, when the original ones were?

**Comment by justdan96** [comment]
There is a variable to turn on static linking, but from the looks of it "true" static linking isn't possible on Mac, see here: https://stackoverflow.com/questions/3801011/ld-library-not-found-for-lcrt0-o-on-osx-10-6-with-gcc-clang-static-flag

From the looks of the old Makefile for Mac the static freetype library was explicitly linked, this may be why there wasn't a dependency: 
https://github.com/justdan96/tsMuxer/blob/c9903966702a691f6be0cc57037de2c6bfa13dd3/tsMuxer/Makefile.mac

I'll try to see if we can get CMake to mimic this behaviour.

**Comment by SubJunk** [comment]
Ah yeah I remember the same thing when compiling MPlayer on macOS too, it is never fully static. But I managed to get to the point where the remaining dependencies are ones that are included with macOS. This is that build in case it's useful to compare:
http://sourceforge.net/projects/mplayer-sb/files/MPlayerMEncoder-SB67-macOS.zip/download

**Comment by justdan96** [comment]
I've figured out how to reduce the dependencies down to the below when compiling in osxcross:

```
# x86_64-apple-darwin19-otool -L bin/tsMuxeR
bin/tsMuxeR:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

To push this out requires a change to [the Docker container we are using](https://github.com/justdan96/tsmuxer_build), the CMakelist file for tsMuxer and the bash scripts for generating the builds - so it might take a little time to coordinate.

**Comment by SubJunk** [comment]
That's great, thank you! I will look forward to its release and will do a UMS release to coincide with it

**Comment by justdan96** [comment]
Please check if this artefact is working okay for you: https://github.com/justdan96/tsMuxer/actions/runs/1190840503

**Comment by SubJunk** [comment]
@justdan96 yes that seems to work for me. The output of `otool -L` is:

```
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

Thanks!

**Comment by SubJunk** [comment]
@justdan96 this is still happening in the latest releases. I'm downloading the assets from the GitHub releases page, is that the right source?
