### ISSUE TITLE
Missing subtitles since nightly-2020-04-26--02-12-05

### ISSUE THREAD

**Issue by Selur** [justdan96/tsMuxer#457]
I use the folloxing meta file:
```
MUXOPT --no-pcr-on-video-pid --new-audio-pes --vbr --vbv-len=500
V_MPEG4/ISO/AVC, "E:\Output\[Final8]Senyuu - 02 (BD 10-bit 1280x720 x264 AAC)[4ACE10B1]_2021-09-15@17_43_48_0110_03.264", fps=23.976, insertSEI, contSPS, ar=1:1 (Square)
A_AAC, "E:\Output\iId_3_aid_0_DELAY_9ms_2021-09-15@17_43_48_0110_01.aac", timeshift=9
S_TEXT/UTF8, "E:\Output\special characters.srt",font-name=Arial,font-size=60,font-color=0x00FFFFFF,font-charset=1,bottom-offset=16,font-border=1,text-align=center,video-width=1280,video-height=720,fps=23.976
```
and [special characters.zip](https://github.com/justdan96/tsMuxer/files/7171576/special.characters.zip) as subtitle file.
and this call: `tsMuxeR "E:\Output\tsMuxerMeta_2021-09-15@17_43_48_0110__04.meta" "E:\Output\[Final8]Senyuu - 02 (BD 10-bit 1280x720 x264 AAC)[4ACE10B1].m2ts"`

as output I get:
```
tsMuxeR version git-8474c6b. github.com/justdan96/tsMuxer
Decoding H264 stream (track 1): Profile: High@5.1  Resolution: 1280:720p  Frame rate: 23.976
B-pyramid level 1 detected. Shift DTS to 2 frames
Warning: PGS might not work without HDMV descriptors.
0.0% complete
H264 bitstream changed: insert nal unit delimiters
H264 bitstream changed: insert pict timing and buffering period SEI units
Decoding PGS stream (track 3):  Resolution: 1280:720  Frame rate: 23.976
Decoding AAC stream (track 2): Sample Rate: 48KHz  Channels: 2
Processed 6857 video frames
100.0% complete
Flushing write buffer
Mux successful complete
Muxing time: 1 sec
```
sadly the output does not show any subtitle streams in MPC-HC, using 

using: https://www.videohelp.com/download/tsMuxer_CLI_2.6.15.zip (2019-12-11) subtitles are there but all special characters are broken.

https://github.com/justdan96/tsMuxer/releases/tag/nightly-2020-04-24--02-11-34
has subtitles with proper characters.

but with "nightly-2020-04-26--02-12-05: Support for HDMV descriptors is now selectable at runtime (#282)" subtitles are gone,...

-> Am I missing some, now needed, parameter in the .meta file or is there a bug?

**Comment by jcdr428** [comment]
Hi @Selur, you need to leave the --hdmv-descriptor option checked -it is checked by default in m2ts mode.

**Comment by Selur** [comment]
> Hi @Selur, you need to leave the --hdmv-descriptor option checked 
I use tsMuxeR through the command line so there is nothing to uncheck.
> it is checked by default in m2ts mode.
that does not seem to be true when the command line is used,...

**Comment by jcdr428** [comment]
@Selur indeed the checkbox is in the GUI.
Just add --hdmv-descriptor after the --new-audio-pes in the command line.

**Comment by Selur** [comment]
Thanks! That helped!
