### ISSUE TITLE
Global Error on macOS 10.14.6

### ISSUE THREAD

**Issue by radioproektor** [justdan96/tsMuxer#458]
I got this pop-up error message window on file load:
```
dyld: Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
 Referenced from: /private/var/folders/ss/y_mbrf6j0_7cnxvljw_2_wv40000gn/T/AppTranslocation/5545471F-86BB-4CF3-A332-19888F0000D5/d/tsMuxerGUI.app/Contents/MacOS/tsmuxer
 Reason: image not found
```
![Screen Shot 2021-09-15 at 11 32 01 PM](https://user-images.githubusercontent.com/35053925/133517567-df6c4741-4b0e-4e26-b4e7-e0b9c042ca62.png)

I scrolled back and randomly checked few versions and seems they all produce same pop-up window. Is it some global mistake in releases from start? Or is it just my macOS 10.14.6 system unsupported anymore?

No any problem with tsMuxeR 2.6.12 from https://www.videohelp.com/software/tsMuxeR#otherdownload
No problem with mac-nightly-2020-09-25--02-25-44 and up to mac-nightly-2020-11-17--01-21-46

**Comment by justdan96** [comment]
Please see #405

**Comment by radioproektor** [comment]
If it helps here is a fix for form Selur:
https://forum.selur.net/thread-1495-post-13379.html#pid13379

Okay, I figured that out.
if you call 'oTool' it will reinstall it, it you use 'otool' it works,.. Angry

okay using:
install_name_tool -change /usr/local/opt/freetype/lib/libfreetype.6.dylib @executable_path/lib/libfreetype.6.dylib tsMuxeR
sadly did not work, it gives me:
dyld: Library not loaded: @executable_path/lib/libfreetype.6.dylib
  Referenced from: /Users/selur/workspace/Hybrid/Hybrid.app/Contents/MacOS/./tsMuxeR
  Reason: Incompatible library version: tsMuxeR requires version 25.0.0 or later, but libfreetype.6.dylib provides version 24.0.0
zsh: abort      ./tsMuxeR
when callling tsMuxer. So a newer libfreetype is needed :/

**Comment by justdan96** [comment]
The tsMuxer binaries created through osxcross are statically linked now, so it won't look for those libraries at all. Check the binary created here: https://github.com/justdan96/tsMuxer/actions/runs/1215042189

**Comment by radioproektor** [comment]
Ok. Version from that link works well.
