### ISSUE TITLE
Static linking of zlib and freetype libraries for MacOS

### ISSUE THREAD

**Issue by jcdr428** [justdan96/tsMuxer#462]
The zlib and freetype libraries are statically linked in the docker builds, however are not statically linked in the builds made directly from the code.

**Comment by justdan96** [comment]
I may change the release scripts for MacOS so the command line executable is created from Docker and the GUI is created from native MacOS.

**Comment by xavery** [comment]
zlib is system-provided and there's no reason why we shouldn't use it. In fact, homebrew has been issuing a warning about this for some time now, which led me to remove the `brew install zlib` line from the native build script.

Anyhow, #495 contains the solution to this, though admittedly not the best there is : it just builds freetype and libpng (freetype's dependency) before building tsmuxer, installs them to a local prefix, and then instructs cmake to link against packages in that prefix. This leads to a tsmuxer package whose dependencies are as follows : 
```
$ otool -L tsMuxeR 
tsMuxeR:
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```
i.e. there are no non-system dependencies, and the binary will run without installing anything extra on current macOS systems.

**Comment by justdan96** [comment]
I've done some initial testing on an M1 Mac and hopefully soon I can update the build instructions for Mac as it was a bit more involved than in the docs. Also I received the crash when using Homebrew's Qt5 so there does seem to be a code signing issue there, again I need to update the documentation on how to get Qt5 installed from the official repo. 

Regarding the PR, Homebrew installs statically linked versions of the libraries, I believe with a few commands and a small change to the CMakeLists we could reduce down the dependencies on Mac. I'll try to do some more testing soon.

**Comment by xavery** [comment]
I wish I had known that yesterday, as it pretty much makes my changes completely unnecessary. #496 contains a better approach which uses the installed static libraries.
