### ISSUE TITLE
symlink ttf fonts are not recognized

### ISSUE THREAD

**Issue by jcdr428** [justdan96/tsMuxer#463]
For MacOS and Linux systems, the ttf fonts in the font folders are not recognized by tsMuxer.

**Comment by jcdr428** [comment]
@justdan one solution is to replace in textSubtitlesREnderFT.cpp:
`m_fontNameToFile[fontFamily] = fileList[i];`
with :
`m_fontNameToFile[fontFamily] = std::filesystem::canonical(fileList[i]).string();`

However this supposes to move MacOS SDK to 10.15 for the `canonical` method.
Plus Linux is ok with `std::filesystem::`, however MacOS requests `std::__fs::filesystem::`

**Comment by justdan96** [comment]
I thought the SDK in the Docker container was at 10.15 already but I can check and see if we can make a code change.

**Comment by jcdr428** [comment]
@justdan96 yes no problems to change to 10.15 in the .sh files.
Any idea how to sort out the MacOS std::__fs::filesystem:: vs Linux std::filesystem::  thing ?

**Comment by justdan96** [comment]
It should just be a DEFINE, same as we use elsewhere - I think `#if defined(__APPLE__) && defined(__MACH__)` is the line we use.

**Comment by jcdr428** [comment]
@justdan96 Thanks.  Linux build not working, `undefined reference to 'std::filesystem'`.
From what I read I need to "link with `-lstdc++fs`" : how do I do that ?

**Comment by justdan96** [comment]
Are you including the header file `<filesystem>`?

**Comment by jcdr428** [comment]
Yes I did. I've also tried `<experimental/filesystem>` and `<boost/filesystem>` libraries, no luck.

**Comment by justdan96** [comment]
It looks like those are a part of C++17, I need to check how we can enable that.

**Comment by jcdr428** [comment]
I've been trying to upgrade to C++17 but I am struggling with the new std::byte conflicting with the Windows byte type.
