### ISSUE TITLE
Introduce a uniform formatting style

### ISSUE THREAD

**Issue by xavery** [justdan96/tsMuxer#47]
It would be nice to have all the files in the repository formatted in a uniform way. Unfortunately, currently the sources are a mix of everything, with tabs sometimes occurring alongside spaces, different indenting widths and brace styles. I didn't even have to look far : [`Base64::decode`](https://github.com/justdan96/tsMuxer/blob/master/tsMuxer/base64.cpp#L59) is a good example.

I find that the best course of action would be to introduce a clang-format file (or a similar tool's configuration, this is just the one I personally use) and just mass-modify all source files in the repository once there are no outstanding pull requests.

**Comment by justdan96** [comment]
I completely agree - I just did this for some of the tsMuxerGUI sources. I'd be fine to run clang-format across all the cpp and h files to make it all uniform.

**Comment by justdan96** [comment]
I've created a new branch for experimenting with the right formatting - you can compare against how Base64::decode used to look before against with the updated formatting: https://github.com/justdan96/tsMuxer/blob/c2f802306ebe7bd3d991dcd631d47d7ea8f9aaac/tsMuxer/base64.cpp#L56

If there is anything else you think we should be setting please let me know.

**Comment by xavery** [comment]
Looks good to me. I'm not used to indenting with width equal to 3, but I don't mind. The only thing that stands out is the fact that `Standard` can be set to `Cpp14` now :smiley: .

**Comment by justdan96** [comment]
When I tried to set that to `Cpp14` it kept saying it was invalid! Tried a few variation but nothing seemed to work.  I can take the single quotes out, certainly.

**Comment by jcdr428** [comment]
Can we please keep indenting equal to 4 -as used by most editors?

**Comment by justdan96** [comment]
Sure, I did some research online and I think this configuration should give us nice looking results:
```
BasedOnStyle: Google
Standard: Cpp11
TabWidth: 4
UseTab: Never
IndentWidth: 4
BreakBeforeBraces: Allman
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
ColumnLimit: 0
```
I'm thinking to introduce a line limit of 80 characters as well - it seems like a lot of people like that - but I'm open to suggestions.

**Comment by xavery** [comment]
I've always found the 80-character limit a bit too restrictive - especially when dealing with C++ code - and considered 120 to be a nice compromise.

**Comment by justdan96** [comment]
Makes sense, I'll edit the file in that branch. There are some options in GitHub for ensuring each pull request is correctly formatted I want to look into as well.
