### ISSUE TITLE
Fail to detect all streams for ISDB-Tb

### ISSUE THREAD

**Issue by wtuemura** [justdan96/tsMuxer#499]
tsMuxer fails to detect all streams, it detects video but not audio (and other streams). This is a [raw TS](https://mega.nz/file/m9AQkLrY#ukIITgIlIXtS_6DPPgLK7WwgBC1vQDr9lQdHyEBy3lA) capture and this is the [full ISDB-Tb specs](https://mega.nz/file/nwJExBgK#r8w4GLH0_rwpUrywmfXD8R6vSw6hwVOn2-JHCjVy_j0) in english.

Extra info about the raw ts:
[PSI-SI.txt](https://github.com/justdan96/tsMuxer/files/7653906/PSI-SI.txt)
[mux-data.txt](https://github.com/justdan96/tsMuxer/files/7653907/mux-data.txt)

**Comment by jcdr428** [comment]
@wtuemura tsMuxer does not detect multiplexed (LATM) AAC, nor ARIB captions.
Somebody might include these codecs in tsMuxer if he is interested.

**Comment by wtuemura** [comment]
Thank you for your feedback @jcdr428.
The file structure from #494 is different, my file is a full dump from the FTA service, it includes PAT/PMT among others, anyway.

Looking forward for tsMuxer to be able to demux the streams.

Thank you.

**Comment by jcdr428** [comment]
@wtuemura the issue in #494 is actually the same -the video stream is detected despite the absence of PAT/PMT, the real issue is non-detection of LATM AAC and ARIB captions.
Anyway yes let's hope somebody will work on the issue in a near future.

**Comment by justdan96** [comment]
Closing as this is a duplicate of #494
