### ISSUE TITLE
FEATURE REQUEST: Add option to encrypt channel

### ISSUE THREAD

**Issue by frakman1** [justdan96/tsMuxer#513]
Given a key, allow user to encrypt a channel including the correct MPEG headers/PIDS that describe an encrypted channel.

**Comment by xavery** [comment]
Do you want us to use Nagravision, Conax, or Viaccess?

**Comment by frakman1** [comment]
Thank you for following up.
Is each one a completely different implementation or just a difference in the headers?
I was thinking of the one corresponding to CA-ID 0xE00. Formerly Scientific Atlanta, currently Synamedia.

**Comment by xavery** [comment]
As far as I'm aware, the specifications for encryption parameters and algorithms used by CA systems are not public. Furthermore, the TS spec does not define the content of the CA descriptor (according to Table 2-61 of ISO/IEC 13818-1:2021) contains just `private_data_byte`s, so there's not much to work with.

Unless you can supply the specification for your CA, I'm afraid this cannot move any further.

**Comment by xavery** [comment]
[tsduck](https://github.com/tsduck/tsduck) is apparently capable of producing scrambled streams, perhaps look into it for what you need.
