### ISSUE TITLE
Support for *.ec3 file extension [E-AC3]

### ISSUE THREAD

**Issue by GrzeWier** [justdan96/tsMuxer#533]
Hi
Please add .ec3 file extension to the dropdown for "AC3/E-AC3"
.ec3 is the "proper" extension for E-AC3 files as defined by Dolby in their mp4muxer
https://github.com/DolbyLaboratories/dlb_mp4base
(.eac3 or .ddp is not recognized at all)

Demuxed E-AC3 files should be given .ec3 extension as well.

Side note:
When "All supported media files" is selected .ddp files are not included

**Comment by xavery** [comment]
Thanks, feel free to reopen if you're not satisfied with the solution. The `2022-01-03` nightly will include these changes.
