### ISSUE TITLE
Library not found on macOS

### ISSUE THREAD

**Issue by SubJunk** [justdan96/tsMuxer#539]
This problem has resurfaced which makes the macOS release not work unless the machine also has freetype installed. It got fixed last year but maybe that fix didn't make it into the releases or something, the previous issue is at https://github.com/justdan96/tsMuxer/issues/443

**Comment by xavery** [comment]
The documentation now explicitly requests macOS users to install Freetype via Homebrew.

There is a [pull request](https://github.com/justdan96/tsMuxer/pull/496) which will make the binary 100% static without any external dependencies but it's still pending review and approval.

**Comment by SubJunk** [comment]
@xavery thanks for your response. Is there anything I can do to help that PR move forward? I'm a developer of a media server that bundles tsMuxeR so it's not that practical to get our users to run a Homebrew command

**Comment by xavery** [comment]
@justdan96 Do you mind having a look?

**Comment by xavery** [comment]
@SubJunk Dan seems to be missing in action, so I went ahead and merged that PR seeing how it's blocking an actual issue.

The changes will be incorporated into today's nightly build, or you can try out the [per-commit build](https://github.com/justdan96/tsMuxer/suites/4909690497/artifacts/141305394) if you don't want to wait. Please test and report back.

**Comment by justdan96** [comment]
Sorry the only M1 Mac I have access to is my partner's and she has been using it a lot recently! I'll check if the finished build still works okay on her M1 Mac.

**Comment by SubJunk** [comment]
Thanks guys, I really appreciate this :)

**Comment by justdan96** [comment]
I'm seeing this output from latest Mac binary on M1 Mac:

![tsmuxer_mac_screenshot](https://user-images.githubusercontent.com/503722/149325904-7c3770d0-2e96-4c6e-bb8d-9be396dec5d0.jpg)

**Comment by justdan96** [comment]
I think we are okay to close.

**Comment by SubJunk** [comment]
Thanks again!
