### ISSUE TITLE
Some files with Dolby TrueHD audio report track unknown error.

### ISSUE THREAD

**Issue by GrzeWier** [justdan96/tsMuxer#540]
Hi
When opening in the GUI some files with Dolby TrueHD audio report "track unknown" error.
Any such file is fine (it plays in all common media players) and can be processed in other AV tools (like eac3to, MKVToolnix, ffmpeg) without issues.
One thing in common for all such cases seems to be: there is no core AC3 track inside the TrueHD track.

Sample of such file:
https://www.demolandia.net/downloads.html?id=48882118

**Comment by jcdr428** [comment]
@GrzeWier please try [this fix](https://github.com/jcdr428/tsMuxer/suites/5006139587/artifacts/146949189) and confirm it works as expected.

**Comment by jcdr428** [comment]
Fixed by be590646

**Comment by GrzeWier** [comment]
Yes it is fixed, thanks
