### ISSUE TITLE
Missing "UHD .. " options in GUI

### ISSUE THREAD

**Issue by medikoo** [justdan96/tsMuxer#541]
I've just downloaded latest nightly release and I don't see "UHD Blu-ray ISO" and "UHD Blu-ray folder" options in GUI.

What do I miss?

<img width="1132" alt="Screenshot 2022-01-11 at 10 11 30" src="https://user-images.githubusercontent.com/122434/148913872-b7af9caa-c2ca-4892-8853-06fd6329a15a.png">

**Comment by medikoo** [comment]
@xavery great thanks for clarifications! That's good news.

In light of that it'll be probably good to update the screenshot in the main readme, and add some notes about such detection (?)

**Comment by justdan96** [comment]
That's a good suggestion, should be easy enough to make those changes. You even supplied an updated screenshot for us to use! :)

**Comment by xavery** [comment]
I updated the README to point to the new screenshot. Also added a note about GUI usage and `--blu-ray-v3`.

**Comment by jcdr428** [comment]
Hi @xavery, actually the V3 is automatically set when detecting HEVC. It might or might not be UHD...
The manual option is left if somebody wants to mux AVC or MEPG-2 to V3. E.g. many blurays include main movie in hevc and bonuses in avc, however all files must be V3 format.

**Comment by xavery** [comment]
Corrected, thanks.
