### ISSUE TITLE
can't Use Nightly build from 2022-01-15-02-09-45 on Ubuntu 20.04 LTS 

### ISSUE THREAD

**Issue by ted423** [justdan96/tsMuxer#545]
Nightly build from 2022-01-13-02-13-31 worked
tsmuxer can't run
and I use  2022-01-15-02-09-45's tsMuxerGUI-938eefb-x86_64.AppImage with  2022-01-13-02-13-31's tsmuxer still show can't find tsmuxer.

**Comment by justdan96** [comment]
Can you please paste the full error logs?

**Comment by ted423** [comment]
> Can you please paste the full error logs?

the tsMuseR show no such file or folder when I run.but the old one show the command line help
the gui worked , but when select mpls it show can't find tsMuseR

**Comment by andrej-peterka** [comment]
@justdan96 I believe this is a problem for linux builds. I'm having the same issue. See logs below.

I suspect this is because the binary is now dynamically linked. I think previously it was static?

```
➜  tsmuxer curl -LO https://github.com/justdan96/tsMuxer/releases/download/nightly-2022-01-26-02-08-33/lnx.zip

...

➜  tsmuxer unzip lnx.zip
Archive:  lnx.zip
   creating: bin/lnx/
  inflating: bin/lnx/tsMuxeR
  inflating: bin/lnx/tsMuxerGUI-6c8e72e-x86_64.AppImage

➜  tsmuxer docker run -it -v $(pwd):/work ubuntu:20.04 bash
root@6d5b3ac5cd33:/# /work/bin/lnx/tsMuxeR
bash: /work/bin/lnx/tsMuxeR: No such file or directory

root@6d5b3ac5cd33:/# file /work/bin/lnx/tsMuxeR
/work/bin/lnx/tsMuxeR: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld64.so.1, BuildID[sha1]=5d26f28f0d6bbfd4793d7bac2029c2994835aacc, for GNU/Linux 3.2.0, not stripped
```

**Comment by andrej-peterka** [comment]
Fyi, as a workaround I had to do:

```
ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld64.so.1
apt install libpng16-16
```

Then I can run it. I found a hint to this here: https://stackoverflow.com/a/13990567

**Comment by justdan96** [comment]
I'm assuming the builds from OBS are working okay? I'll have to check our latest Linux build logs to see if something isn't working quite right.

**Comment by andrej-peterka** [comment]
What is OBS? Where can i test them?

**Comment by andrej-peterka** [comment]
If i build via docker, e654d6331fbaebde3d1da42fefb15eba02020328 is the latest that works for me.

**Comment by ted423** [comment]
here the Nightly build from 2022-01-26-02-08-33 can't work too
libpng16-16 installed before

**Comment by ted423** [comment]
worked after use
`ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld64.so.1`

**Comment by gacopl** [comment]
i have built by latest docker and still had the issue ln -s fixed it thank you !!!!

**Comment by justdan96** [comment]
Sorry for the long delay on this one - I will do some testing and let you know where the issue is.
