### ISSUE TITLE
inconsistent language information detected

### ISSUE THREAD

**Issue by lonecrane** [justdan96/tsMuxer#549]
Hi, I have obtained a bd source, whose information detected by tsMuxeR is different from those reported by other tools.
Track ID: 0x1102

Potplayer reports that the language of this track is 'Chinese', as expected.
![Untitled1](https://user-images.githubusercontent.com/36885830/150915545-74dd9ba7-60d9-4eb4-9801-ab3e4ed66f1e.png)

BDinfo also reports 'Chinese', as expected.
![Untitled2](https://user-images.githubusercontent.com/36885830/150915552-236edcdb-b0d2-44fe-93a0-1715a55c9a56.png)

However, tsMuxer reports 'English'.
![Untitled3](https://user-images.githubusercontent.com/36885830/150915557-a2d6a1a7-2759-4791-b14f-18c2bbd6afbf.png)

The sample file has been uploaded to [here](https://www.mediafire.com/file/2fbe5lkit7cazaf/sample.zip/file).
The lastest version makes no difference.
Thanks in advance for any help.

**Comment by jcdr428** [comment]
@lonecrane there are language descriptors in the m2ts (just open the m2ts file with an Hex editor, you will see the "eng" at the beginning). For blu-rays, there should be no language descriptor in the m2ts so the blu-ray files are not compliant.

This said, I would have thought that if there was language in both the m2ts and the mpls, tsMuxer would default to the mpls: this is obviously not the case.
