### ISSUE TITLE
Video artifacts in last 3 relases (24-30 Jan)

### ISSUE THREAD

**Issue by cob66** [justdan96/tsMuxer#554]
Video artifacts in UHD DV mux. The January 23 release is the last good one (without these artifacts). I also noticed periods of silence in the audio (DTS-HD) on the example of the movie The Piano (UHD DV)

**Comment by j68k** [comment]
I'm also seeing errors in files produced with the latest nightly acde33a/nightly-2022-01-30-02-00-52

Testing my output streams with ffmpeg is showing corrupt packets warnings like:
```[mpegts @ 000001e2d3b38800] Packet corrupt (stream = 0, dts = 44866082)..39x```
which are then followed by various errors in the hevc/truehd decoders

If you happen to have the UHDBD disc of _Back to the Future Part II_ available then you can repro with the [attached meta file](https://github.com/justdan96/tsMuxer/files/8088995/BTTF2test.zip):
```tsMuxeR.exe BTTF2test.meta BTTF2test.m2ts```
and then test the file with
```ffmpeg -i BTTF2test.m2ts -f null -```

and you should see warnings and errors starting at around time=00:08:15.

I have the European release of that title, but I don't know if the disc is the same in other regions. If you don't have that disc I believe the errors will probably show up in many others. I've been remuxing all my DV rips recently for playback on a hardware player, and have had playback problems which I had assumed were problems with the player or the rips and didn't think until now to test the streams.

Thank you very much @cob66 for identifying the last working release. I have done one remux with the January 23 release so far and the output does pass the ffmpeg test (I haven't actually tested playback yet).

**Comment by jcdr428** [comment]
Hi @j68k , can you please post the full ffmpeg log with errors ?

**Comment by j68k** [comment]
Hi, here's the -report log:
[ffmpeg-20220218-114138.zip](https://github.com/justdan96/tsMuxer/files/8097118/ffmpeg-20220218-114138.zip)

Thanks very much. Please let me know if there's anything else useful I can provide.

**Comment by jcdr428** [comment]
@j68k @cob66 please try https://github.com/justdan96/tsMuxer/suites/5380077077/artifacts/169106760 (win64 version) -or wait for tomorrow's release-, and confirm whether it is fixed.

**Comment by j68k** [comment]
Thank you very much for the fix @jcdr428. I re-did my _Back to the Future Part II_ ffmpeg test, and it passed with zero errors, and only the expected warnings at the beginning of the file that also happen on the original stream from the disc.

Just a heads up that the upload of last night's nightly builds seems to have failed (apart from the macOS build) so please re-trigger that build if possible.

Thanks again!

**Comment by jcdr428** [comment]
Hi @justdan96 @xavery, any way to manually launch the nightly release ?

**Comment by justdan96** [comment]
Once I am home I can try to re-trigger those jobs.

**Comment by xavery** [comment]
Yup, that [worked](https://github.com/justdan96/tsMuxer/releases/tag/nightly-2022-02-22-18-30-10). For future reference, if a build fails, you can trigger a new one by going to Actions, selecting the latest or failed "Nightly Releases" workflow run, clicking on it and selecting "Re-run all jobs".
Before you do that, though, you need to remove the already existing (incomplete) tag and release - otherwise, the workflow will run but quit immediately due to the freshest tag matching the tip of the repository.

**Comment by jcdr428** [comment]
Thanks @xavery, I did try the re-run but I didn't know I had to remove the former jobs.
