### ISSUE TITLE
Dolby vision only for M2TS, not in Bluray folder option

### ISSUE THREAD

**Issue by Cedvano** [justdan96/tsMuxer#556]
Hi,
When I remux a MKV to M2TS, I have: 
_Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible_

But when I create a Bluray folder, I have only : 
_SMPTE ST 2086, HDR10 compatible_

He lost the Dolby Vision with the last release **nightly-2022-02-22-18-30-10** · Commit: **f4fa419**

Thanks.

**Comment by Cedvano** [comment]
@jcdr428 same result with other version.

**Comment by jcdr428** [comment]
@Cedvano with Blu-rays the Dolby Vision info is in the mpls/bdmv files, not in the m2ts.

**Comment by Cedvano** [comment]
@jcdr428 same result in mpls and test clpi too. Not playable in Dolby Vision.

**Comment by jcdr428** [comment]
@Cadvano can you please test an original Blu-ray rip and advose of any difference.

**Comment by Cedvano** [comment]
I tested with the original bluray and it works. But impossible with an MKV. However, impossible to determine if this is due to my LG UP970 player (which is not the best). So I'm going to do it differently. Thank you for your help.

**Comment by ValZapod** [comment]
> impossible with an MKV.

Yes, because there is no official support for mkv. Only mp4, it works, including FEL on C9. mkv Dolby spec was created by mkver.
