### ISSUE TITLE
2in1? or ADD vs Join?

### ISSUE THREAD

**Issue by droopified** [justdan96/tsMuxer#558]
i have a bluray that has theatrical and alternative endings. i know the two playlist but instead of having to demux them 1 at a time, should i do a ADD or JOIN? not sure if i understand what the difference.

**Comment by jcdr428** [comment]
@droopified not sure to understand: do you want to remux each movie in separate m2ts, or do you want to demux the elementary streams ?

**Comment by droopified** [comment]
trying to remux a bluray disk which has two playlist (theatrical, alternative ending) into 1 mkv with two video streams.

**Comment by jcdr428** [comment]
Have you tried Xin1generator ? Just does what you want (mkv ordered chapters).
