### ISSUE TITLE
No length/duration info in mux

### ISSUE THREAD

**Issue by kingpost** [justdan96/tsMuxer#561]
Hi, great software, I use it often -- thanks for making it. My possible issue is this:

I did a mux with the latest W64 nightly build, 2022-02-27* to a Blu-ray folder output. Checking the resulting .m2ts file in MediaInfo, I noticed it does not report the length of any of the contained video or audio streams, as I normally expect to find.

Specifically, for video, there is no "Duration" or "FrameCount" listed. For audio, no Duration, FrameCount, or SamplingCount.

I went back and tried nightly builds 2022-02-22 and 2022-01-30 and found the same result. My last mux that shows the length information in MediaInfo as normal was made with 7d58796 / 2021-12-12.

Is this a bug with tsmuxer? Are the newer builds not correctly writing A/V length information?

\* BTW, there is no w64.zip for 2022-03-07. Not sure if that is an issue as well.

**Comment by jcdr428** [comment]
@kingpost can you please try the latest nightly 2022-03-28 and report whether the bug has been solved ?

**Comment by jcdr428** [comment]
@kingpost please confirm whether the bug has been fixed.

**Comment by jcdr428** [comment]
No answer, assumed fixed. Can be reopened upon request.
