### ISSUE TITLE
Demuxed channels cannot be muxed again

### ISSUE THREAD

**Issue by medikoo** [justdan96/tsMuxer#562]
I'm re-muxing now some Studio Ghilbi BD's from Japan, and they have some special characteristics which introduce errors in an app.

When I demux BD and I try to remux exactly same channels I get following error:

<img width="610" alt="Screenshot 2022-03-17 at 08 51 51" src="https://user-images.githubusercontent.com/122434/158762414-c3352f90-5df5-4f31-b877-e3d0bd2654a3.png">

But when I try to mux same channels, but taking them directly from original `m2ts` file, all works well.

I suspect there's some issue with demuxing if it produces files that report errors on muxing attempt.

If needed I can share the m2ts file for testing

**Comment by jcdr428** [comment]
@medikoo can we please have a sample (50 MB) of the m2ts.

**Comment by medikoo** [comment]
> @medikoo can we please have a sample (50 MB) of the m2ts.

You mean starting 50MB of `m2ts`?

**Comment by medikoo** [comment]
@jcdr428 you can download it from here: https://home.medyk.org/sharing/nGMA8b4HI

If you need larger file, let me know

**Comment by jcdr428** [comment]
@medikoo I can reproduce the bug, I'll have a look.
In the mean time, you don't need to use insertSEI and constSPS options with Blu-rays.

**Comment by medikoo** [comment]
> @medikoo I can reproduce the bug, I'll have a look.

Thanks @jcdr428!

> In the mean time, you don't need to use insertSEI and constSPS options with Blu-rays.

Thanks, I'll turn it off. Still, this option is on by default (I've never set it, and I even don't understand what it does). Maybe in such a case, it'll be good to have it off by default?

**Comment by jcdr428** [comment]
@medikoo indeed: with commit [5421531](https://github.com/justdan96/tsMuxer/commit/54215310a09e15f1448670b54d5aa39bee6a2c08) option is now off by default.

**Comment by jcdr428** [comment]
@medikoo should be fixed, please try tomorrow's release.
