### ISSUE TITLE
not enough buffer for parse video stream

### ISSUE THREAD

**Issue by wolflopnew** [justdan96/tsMuxer#563]
Here is the message txmuxer gives me

[[](url)](https://abload.de/img/screenshot2022-03-15229ks9.jpg)

Hope you can fix this or give me a help to solve the problem...

wolflop

**Comment by jcdr428** [comment]
@wolflopnew we need the mkv to reproduce the bug and be able to debug. Please see whether you can post a link.

**Comment by wolflopnew** [comment]
the MKV file to be processed is 73 GB in size. I cannot upload this size.

**Comment by justdan96** [comment]
You can cut the source video into smaller parts using HxD on Windows or the `head` command on Linux or Mac.

**Comment by wolflopnew** [comment]
I have  smal sample.iso of the file 7GB Size. Where can send the link?

**Comment by justdan96** [comment]
7GB is still pretty large - is there any way to cut it down further or compress it? If it isn't possible you would have to try uploading the sample to a site that allows files that large - you can check the list from here: https://multiup.org/en/upload/from-computer

**Comment by jcdr428** [comment]
@wolflopnew if you use Windows just use your OneDrive.

**Comment by wolflopnew** [comment]
Hello here is the google drive link
https://drive.google.com/file/d/1adrTWeVeJx3rXXnrwYtdOL_bCAw8Vp0b/view?usp=sharing

wolflop
Meet Google Drive – One place for all your files<https://drive.google.com/file/d/1adrTWeVeJx3rXXnrwYtdOL_bCAw8Vp0b/view?usp=sharing>
Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.
drive.google.com

________________________________
Von: jcdr428 ***@***.***>
Gesendet: Donnerstag, 7. April 2022 07:25
An: justdan96/tsMuxer ***@***.***>
Cc: wolflopnew ***@***.***>; Mention ***@***.***>
Betreff: Re: [justdan96/tsMuxer] not enough buffer for parse video stream (Issue #563)


@wolflopnew<https://github.com/wolflopnew> if you use Windows just use your OneDrive.

**Comment by jcdr428** [comment]
@wolflopnew you should have received an email from OneDrive to give me access.

**Comment by wolflopnew** [comment]
Did you found something.  Have the same problem with another movie. No muxxable parse error.  If found  a solution may be is it the Audio file (aac) i removed when i still had it in the mux there is no parse error but an othe info "m2ts may be not playable"
Hope this help for finding the error.

**Comment by jcdr428** [comment]
@wolflopnew please resend a link, the previous link is not working anymore.

**Comment by wolflopnew** [comment]
Same problem with the next movie
[url=https://abload.de/image.php?img=screenshot2022-04-2809uku5.jpg][img]https://abload.de/thumb/screenshot2022-04-2809uku5.jpg[/img][/url]
Cant upload smaler file because of the error

**Comment by wolflopnew** [comment]
Further information: The original file is an mp4 with AAC sound. When I just create an iso with AAC I get an error saying it might not be playable, but it runs. But if I add the sound files (DTS:X sound and PCm sound, the parse message comes up... Hope that helps with the misfinding. I attach the small film file with AAC sound.

**Comment by wolflopnew** [comment]
Here´s the file 
https://1fichier.com/?y8w5nxqfc5th618826st

**Comment by wolflopnew** [comment]
By the way. Had often the problem that movies start in the player at 0.00 Min. it starts at 1. Min. Where is the bug?

**Comment by wolflopnew** [comment]
Still the same problem. Next movie

Not enough buffer for parse video stream. Current frame num 0

**Comment by jcdr428** [comment]
I can't download 1fichiercom as it requests registration, and the OneDrive dile has disappeared. Please repost aOneDrive link, thanks.

**Comment by wolflopnew** [comment]
heres is another link
https://1drv.ms/u/s!AifiITtpdjN1h2Bnr7hIvncnxLA0?e=1Yrxy9

**Comment by wolflopnew** [comment]
Again the problem
[url=https://abload.de/image.php?img=screenshot2022-05-012zqkr1.jpg][img]https://abload.de/thumb/screenshot2022-05-012zqkr1.jpg[/img][/url]

**Comment by jcdr428** [comment]
@wolflopnew I downloaded the full 2GB file and the m2ts muxes fine in tsMuxer ??

**Comment by wolflopnew** [comment]
It's not synonymous the complete film only 2GB.
and you can see from the screenshots of various films that the problem occurs again and again.
[[url=https://abload.de/image.php?img=screenshot2022-05-012zqkr1.jpg][img]https://abload.de/thumb/screenshot2022-05-012zqkr1.jpg[/img][/url]](https://abload.de/image.php?img=screenshot2022-05-012zqkr1.jpg)

**Comment by wolflopnew** [comment]
i have testet it with smal iso of the film. Its working... With the whole film - error at the end 99,4 %. Whats the problem?

**Comment by jcdr428** [comment]
You should have posted the faulty part, no point posting a working part...
The fault probably comes from the fact that an hevc frame is bigger than the temp buffer. I have increased the max buffer size, please try the release tomorrow. If it does not work, you won't have the choice but to cut the last 1GB from the m2ts (with e.g. HXD hex editor) and post it.

**Comment by wolflopnew** [comment]
Thank you jcdr428. The problem is solved. Great!! 
Only the reported Problem mit burned disc is still open...

**Comment by jcdr428** [comment]
Good. Closing !
