### ISSUE TITLE
Set output folder as same as source folder

### ISSUE THREAD

**Issue by 775405984** [justdan96/tsMuxer#564]
Can you guys set output folder as same as source folder? Just like HandBrake:

![image](https://user-images.githubusercontent.com/7196377/159150068-2e3585a8-1743-4301-ae9d-a3b66ae95115.png)

**Comment by imhh1** [comment]
We can already do that unless I misunderstand you?
https://i.ibb.co/Cn2tHTV/Capture.jpg

**Comment by 775405984** [comment]
> We can already do that unless I misunderstand you? https://i.ibb.co/Cn2tHTV/Capture.jpg
Switch to Demux, see what happens. It automatically change output folder to program folder.

https://user-images.githubusercontent.com/7196377/159385773-d5d22ebc-864b-49a7-afb2-c8baa770feda.mp4

**Comment by imhh1** [comment]
ha, yes, you have to import the file first, then select demux.

**Comment by 775405984** [comment]
> ha, yes I forgot about that. you have to import the file first, then select demux.

thank you.

**Comment by jcdr428** [comment]
@775405984 until the input file is selected, tsMuxer has no way to know the output folder and selects the program folder by default. I close, if somebody has a suggestion for better behavior he can request re-opening of the issue.
