### ISSUE TITLE
Add more languages

### ISSUE THREAD

**Issue by CAPRICORNX10X** [justdan96/tsMuxer#567]
for example I would like the Hebrew language

**Comment by justdan96** [comment]
If you would like to add Hebrew please have a look at https://github.com/justdan96/tsMuxer/tree/master/tsMuxerGUI/translations to see how others have added a new language. We rely on volunteers to provide translations.

**Comment by CAPRICORNX10X** [comment]
I just want to change the caption of the subtitles.
Instead of English - the word in the Hebrew language
Instead of Hebrew - the word in the Hebrew language
![‏‏צילום מסך777 (15)](https://user-images.githubusercontent.com/102700898/162479508-6f5f5d97-c24c-45fd-9e4f-556da21393cc.png)

**Comment by justdan96** [comment]
We have a full Hebrew translation as #581 - but more translations are always welcome!
