### ISSUE TITLE
Bitstream exception std::exception Error

### ISSUE THREAD

**Issue by FilipeAmadeuO** [justdan96/tsMuxer#572]
When opening the 00504.m2ts from the UHD movie Knives Out i get the following error 

![image](https://user-images.githubusercontent.com/28999876/161965945-626e5a50-e176-4431-be82-0a044af8486d.png)

When demuxing at 87,5% i get the error:

Bitstream exception std::exception. It does not have to be! Please contact application support team for more information.

What can be the problem ?
Thanks

**Comment by justdan96** [comment]
Would it be possible to extract the original video from 85% to 90% duration? Just so we can try to test that section in isolation.

**Comment by FilipeAmadeuO** [comment]
Please download here the complete file. Maybe it´s better to check
https://www.dropbox.com/s/33x2ad5sevz3v3k/00504.m2ts?dl=0

**Comment by justdan96** [comment]
Can you also please paste everything from the "meta file" pane?

**Comment by FilipeAmadeuO** [comment]
> Can you also please paste everything from the "meta file" pane?

CLPINF and MPLS files ? Included here: 
https://www.dropbox.com/s/1wx3qql5pygwwf5/00504.zip?dl=0

**Comment by jcdr428** [comment]
Hi @FilipeAmadeuO , when demuxing the second hevc stream with ffmepg `ffmpeg.exe -i 00504.m2ts -map 0:1 -c:v copy output.hevc`, ffmepg reports: 
```
Invalid delta in scaling list data: -1
missing picture in access unit with size 532
```
so basically the dv hevc stream is corrupt, which creates the bitstream exception due to bad parsing of the hevc stream.

**Comment by justdan96** [comment]
Is this still reproducible?

**Comment by GabeBlincoln** [comment]
I just got it out of nowhere while batch-transcoding / modifying a bunch of bluray extras to HDR10 + DoVi 8.1.  I'm investigating since it didn't happen to the next file in the batch which was transcoded and modified by dovi_tool in exactly the same way and the same framerate and resolution (those are the only oddities over what I normally do, it's 480i deinterlaced to 60000/1001 fps 480p).

**Comment by jcdr428** [comment]
@justdan96 there is still work to be done, tsMuxer should show a message "Bad frame detected - skipping frame" rather than aborting due to bitstream exception.
