### ISSUE TITLE
tsMuxer reports strange error on my `.ts` file, but FFmpeg and PotPlayer can normally handle it

### ISSUE THREAD

**Issue by ipid** [justdan96/tsMuxer#575]
I recently had to deal with a '.ts' video clip that was recorded from a Japanese TV channel. I tried to use tsMuxer for demuxing but found that the `.ts` file is unable to open in the tsMuxer GUI. It reports such an error: 

![tsmuxer-nightly-error](https://user-images.githubusercontent.com/5251264/162379004-5f7e4d36-af56-4d3d-a045-fe6695372f2a.png)

However, I found that I can playback the file in PotPlayer as usual, and with FFmpeg I can demux the file correctlly.

I used [the latest tsMuxer release](https://github.com/justdan96/tsMuxer/releases/tag/nightly-2022-04-06-02-38-04). However, I found that I can play the video with PotPlayer as usual, and with FFmpeg I can demux the file correctlly.

The `.ts` file (full version):

Mega: https://mega.nz/file/71tBHSJR#PDckQqWDVtQ2lzTDB1iYPZERINQ7u9rIs6hxaXgwzfo

Google Drive: https://drive.google.com/file/d/1Q9enkHzhvZ3RxtCnop-tEs3YOynrWMvm/view?usp=sharing

File checksum (SHA256): `18372f88253391cab312cbcfd59342dbf4a0ea8e25bb3b81f94cab2ebde6d593`

Feel free to contact me for a smaller sample.

**Comment by MINIXJR** [comment]
I also can confirm this, but it's not a problem of the latest version, I have seen this before with Debian packages from deb-multimedia.org.
The version "2.6.16~20210801.git2aa293b" is still working for me.
The files I'm using are records done with [VDR](http://www.tvdr.de/)
Error git76ce1e6:
```
/usr/bin/tsmuxer 220406-m-on-liyuu-1st-live.ts 
tsMuxeR version 2.6.16-dev. github.com/justdan96/tsMuxer
free(): double free detected in tcache 2
Abgebrochen
```
Working git2aa293b:
```
/usr/bin/tsmuxer 220406-m-on-liyuu-1st-live.ts 
tsMuxeR version 2.6.16-dev. github.com/justdan96/tsMuxer
Track ID:    4110
Stream type: MPEG-2
Stream ID:   V_MPEG-2
Stream info: Profile: Main@4. Resolution: 1440:1080i. Frame rate: 29.97 (pulldown)
Stream lang: 

Track ID:    4174
Stream type: AAC
Stream ID:   A_AAC
Stream info: Sample Rate: 48KHz  Channels: 2
Stream lang: 
Stream delay: -75

Track ID:    4622
Can't detect stream type

Track ID:    7185
Can't detect stream type

Duration: 01:00:16.203
```
If you need additional samples, please let me know.
Just a guess, the error appear very quick, so it's maybe a problem with the file header.

**Comment by jcdr428** [comment]
@ipid thanks for highlighting the bug. Can you please try tomorrow's release and report.

**Comment by ipid** [comment]
> @ipid thanks for highlighting the bug. Can you please try tomorrow's release and report.

It works like a magic! Thank you!
