### ISSUE TITLE
add a minor translation

### ISSUE THREAD

**Issue by CAPRICORNX10X** [justdan96/tsMuxer#576]
I just want to change the caption of the subtitles.
Instead of English - the word in the Hebrew language
Instead of Hebrew - the word in the Hebrew language
![162479508-6f5f5d97-c24c-45fd-9e4f-556da21393cc](https://user-images.githubusercontent.com/102700898/162754083-3b914ce3-7dc2-47d8-8bb3-cfe3fc02a5d6.png)

**Comment by justdan96** [comment]
We have a full Hebrew translation now as #581

**Comment by CAPRICORNX10X** [comment]
Wow thank you !
But what about the image i sent? The language display for subtitle and audio.
Its also translate?

השג את Outlook עבור Android<https://aka.ms/ghei36>
________________________________
