### ISSUE TITLE
BD-Folder gets corrupted when converting Dolby Vision m2ts or mkv with merged single layer BL+EL+RPU

### ISSUE THREAD

**Issue by HoffmannTom** [justdan96/tsMuxer#586]
Hello,
I have issues with creating a BD-Folder with tsMuxer.
I already have a suitable m2ts-File with 4k/UHD/HEVC Video and a TrueHD Audio with AC3-Core + Atmos.
The m2ts file plays well (e.g. in VLC) and I wanted to convert it into a BluRay-Folder so I can play it with a standalone player.
After converting the m2ts-file into a BD-Folder, neither the folder, nor the m2ts file will play anymore (PowerDVD crashes, VLC doesn't show video).
The m2ts-file has still the same size, but it won't play anymore. Replacing the m2ts-file within the STREAM-folder with the original file, doesn't work either. The BD-folder is not playable.

I tried the last nightly build from 2022-04-25-02-56-30 in order to have the latest fixes.

How can I track down the issue? Any help is appreciated.

I stripped the movie down to a 140 MB file and can reproduce the issue. Stripping it down further (cutting), corrupts the audio file unfortunately.

Thanks in advance!

**Comment by jcdr428** [comment]
@HoffmannTom please give the link for the 140MB BDMV faulty folder.
Has there been any old tsMuxer release working with this sample ?

**Comment by HoffmannTom** [comment]
Hello @jcdr428 ,
the m2ts file was truncated with tsMuxeR_2.6.12 before. The resulting m2ts was playing fine.

The conversion to BD-folder was done with the recent nightly build, mentioned above.
Here is the link: https://temp.sh/PcLMV/BDMV.7z  (3 days valid)
PW: tsMuxeR

If I can assist somehow, just let me know.

Thanks in advance for taking a look at it!

**Comment by HoffmannTom** [comment]
Just a short update:
I tried all processing steps (truncating, extract THD, add AC-3 core, mux to m2ts, create BD) again.
Same result with 2.6.12 and the mentioned nighly build 2022-04-25-02-56-30.
m2ts file works, created BD-folder was not playing and m2ts-file inside broken too.

**Comment by jcdr428** [comment]
@HoffmannTom can you please also provide the original m2ts. I need to compare both hevc streams.

**Comment by HoffmannTom** [comment]
Short update:
I extracted the BL stream of Dolby vision and created a blu-ray folder with txMuxer. That worked well and produced a playable folder.
I also tried with another Dolby vision video with a different DV profile (Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU).
This showed the same problem when converting to blu-ray folder (video corrupted).

Thus the issue seems to be related to Dolby vision (at least with profiles 7 + 8) and using "blu-ray-folder" mode.
As muxing works perfectly when using m2ts-mode, I hope the issue solve.

If I can support somehow, just let me know. 
Thanks!

**Comment by HoffmannTom** [comment]
Hello @jcdr428 
I can see that the DOVI Header in the generated m2ts file is missing in blu-ray mode.
It is skipped on purpose, as far as I can read the source code.
In hevcStreamReader.cpp there is a method getTSDescriptor(..) containing 2x the condition:
`if (!blurayMode && m_hdr->isDVRPU) ...`

So the DOVI-Header is not written on purpose when creating a blu-ray disc. I don't know why(?)

I copied the DOVI-Header from the source file to the m2ts-file within the STREAM-folder (via HEX-Editor).
Afterwards, the m2ts-file was playable again but the blu-ray folder was not playing e.g. in PowerDVD.
PowerDVD crashed when opening the blu-ray folder. Maybe the meta-files contain some kind of checksum
or need some additional information about dolby digital(?)

I hope this helps to narrow down the issue.

Greetings,
Thomas

**Comment by jcdr428** [comment]
@HoffmannTom the DOVI header is not written in Blu-raymode because the DV mode is detected from the mpls/clpi: same as original UHD Blu-rays.

I downloaded both versions, I'll have a look when I have time.

**Comment by HoffmannTom** [comment]
Thanks for the information! 😊
It is quite hard to find readable documentation about all the involved formats.

**Comment by HoffmannTom** [comment]
BDInfo shows a hidden  video track in the playlist. Maybe it's a hint in the right direction.

**Comment by jcdr428** [comment]
@HoffmannTom a DV Blu-ray m2ts is composed of two hevc streams, one which contains the non-DV (BL) BaseLine Layer, the second which contains the DV (EL) Enhanced Layer and the RPU.

The two were fusioned in your original into a single hevc stream containing all BL+EL+RPU, via "hacking" tools e.g. Makemkv, so that they can be read on android players having a single DV chip. You cannot create a Blu-Ray m2t from this original, you have to first re-separate the BL and EL+RPU into two hevc streams.

**Comment by HoffmannTom** [comment]
Hello @jcdr428 
thank you very much for looking up the cause!
I already separated the layers. How can I proceed with these two files?
Can I just add the two streams in TsMuxer and it will create a DV/HDR blu-ray out of these two streams?
Is the RPU-file with the meta-information obsolete?
Thank you in advance!

**Comment by jcdr428** [comment]
@HoffmannTom normally yes, if you recreated the two original BL and EL+RPU streams, you can successfully mux them with tsMuxer.
The double to single to double layer process shouldn't have changed anything in the RPU.

**Comment by HoffmannTom** [comment]
Hello @jcdr428 
the muxed file is playing on my Sony-Player. Unfortunately, it only shows 8 Bit Color-Depth on TV.
Blu-Ray Player and AV-Receiver both support DV, TV supports HDR10.
Playing with Kodi+Shield shows 10 Bit. So currently I am not sure if there is something wrong with my setup / settings.
If you have any idea, how I can check, whether the Blu-Ray folder is properly set to DV, just drop a line.
The only tools I found are from the manufacturers and more affordable for millionairs :) 

The only thing I have left otherwise would be a little enhancement:
txMuser shows a warning if adding a TrueHD audio without AC-3 core. This helps a lot.
If it's possible, it would be great to have a similar warning, if merged DV-streams are detected which are not compatible to BluRay, as far as I got to know.

Thank you very much for your support and efford!
Thomas

**Comment by jcdr428** [comment]
@HoffmannTom I can add the warning, this should be easy to implement.

**Comment by HoffmannTom** [comment]
@jcdr428 
Great :)
The same problem happens for BL+RPU streams.
The above case was BL+EL+RPU.

**Comment by jcdr428** [comment]
@HoffmannTom I've pushed the fix with the warning, please check if ok.

**Comment by HoffmannTom** [comment]
Hello @jcdr428 
I tested with different containers / videos:

1) mkv: Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU
Warning! MLP codec is not standard for BD disks, the disk will not play in a Blu-ray player.

2) mkv: Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU
Warning! Dolby Vision Double Layer Single Tracks are not standard for BD disks, the disk will not play in a Blu-ray player.

3) m2ts: Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU
Warning! Dolby Vision Double Layer Single Tracks are not standard for BD disks, the disk will not play in a Blu-ray player.

4) mkv: V_MPEG4/ISO/AVC
no warning

Looks good to me!

I would have one last question: 
I also have a video with "Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU"
I can remove the RPU and everything works great with tsMuxer.
BL+RPU now shows a warning in tsMuxer.
Do you know any way how to preserve the RPU data but still be BluRay compliant?
As the video doesn't have an EL stream, I don't know if the RPU data can be used / muxed in some way to preserve DV.

Thanks for your quick help and adjustments!
Thomas

**Comment by jcdr428** [comment]
The only Blu-Ray compliant DV is double track 07.06 with BL in one track and EL+RPU in the other. Any other profile might not be read by the DV chip.

**Comment by quietvoid** [comment]
> The only Blu-Ray compliant DV is double track 07.06 with BL in one track and EL+RPU in the other. Any other profile might not be read by the DV chip.

Apparently not anymore: https://forum.makemkv.com/forum/viewtopic.php?p=122075#p122075

**Comment by HoffmannTom** [comment]
Being possible doesn't necessarily mean it's compliant ;) 
Let's see if there is more information in the future about that. Thanks for the link!

**Comment by jcdr428** [comment]
Anybody can share a sample ? It seems a fake to me: which distributor in its right mind would keep the x265 encoding parameters in the stream ?

**Comment by quietvoid** [comment]
> Anybody can share a sample ? It seems a fake to me: which distributor in its right mind would keep the x265 encoding parameters in the stream ?

Here's the first 5s trimmed using tsmuxer (video only): https://0x0.st/omsn.7z
I'm not sure how else the original folder can be trimmed down.

**Comment by jcdr428** [comment]
@quietvoid could you please post a sample ( say 10MB) of the original m2ts ? Just cut the m2ts with an hex editor eg HxD -select all after 00A0 0000, hit delete and save under new name.

**Comment by jcdr428** [comment]
@quietvoid are these the original .mpls/.clpi in your link, or are these the ones from tsMuxer ?

**Comment by quietvoid** [comment]
> @quietvoid are these the original .mpls/.clpi in your link, or are these the ones from tsMuxer ?

They are from tsMuxer.

**Comment by jcdr428** [comment]
Can I please have the original BDMV (witout the m2ts files) ? I'll see whether the DV flags are set.

**Comment by quietvoid** [comment]
Sure, there you go: https://0x0.st/omox.7z

**Comment by jcdr428** [comment]
So the mpls definitely does not show any DV layer in the STN / the SubPath / the ExtensionData, as if it were a standard HDR10.
There are indeed some RPU nals in the hevc stream, but IMO the standalone Blu-ray players should read the BD-ROM as a standard HDR10.

![Lamb](https://user-images.githubusercontent.com/56721609/167256709-446507e2-4eed-4e73-bd99-b8dffa011224.jpg)
