### ISSUE TITLE
Small correction Translation Language German

### ISSUE THREAD

**Issue by Ser-vie** [justdan96/tsMuxer#587]
@justdan96 
Thank you very much for the quick work! :-)
Sorry
I have corrected a translation error in the "about_de" file.
I had not translated the first sentence, at the tab "About".
Here is the new file.
[about_de.zip](https://github.com/justdan96/tsMuxer/files/8650384/about_de.zip)

**Comment by Ser-vie** [comment]
@justdan96 
#587 and #597
Wrong is
![grafik](https://user-images.githubusercontent.com/83694141/167382205-229ece97-831d-43d2-8c4b-e4adc069bd4f.png)
and correct is
" – Das Programm dient zur Erstellung von TS- und M2TS-Dateien für das IP-Streaming und die Wiedergabe auf Videogeräten (z. B. Dune HD Ultra, Sony Playstation, Smart TVs u. a.)."
[about_de.zip](https://github.com/justdan96/tsMuxer/files/8650440/about_de.zip)

**Comment by xavery** [comment]
Fixed in 24ae93589c64fe9a7b11559801a2fa4a3677c928.
