### ISSUE TITLE
fix 100 % translation of tsmuxer

### ISSUE THREAD

**Issue by CAPRICORNX10X** [justdan96/tsMuxer#591]
Is it possible to translate the language after you add mpls (audio and sub)? I have seen that it has not been translated in any other translation. Always stays in English
![(20)](https://user-images.githubusercontent.com/102700898/165925315-48c79808-3cbc-4259-8b41-19368f0a7a9f.png)

**Comment by CAPRICORNX10X** [comment]
Why does no one answer the question?
If it is not possible to allow translation for this part. Please indicate this ....

**Comment by justdan96** [comment]
The simple answer is that it may be possible but it would require any translators to translate the name of every language into their own language, which would be quite a lot of work.

**Comment by CAPRICORNX10X** [comment]
I definitely volunteer to do so.  Happily.  Do not think this is such a serious problem.  How many names lang are there?

השג את Outlook עבור Android<https://aka.ms/ghei36>
________________________________

**Comment by jcdr428** [comment]
About 500 languages in ISO 639-2.

**Comment by CAPRICORNX10X** [comment]
Why do need to change the code 639-2 language?  Will only the full word be changed to the in the native language?  possible?

השג את Outlook עבור Android<https://aka.ms/ghei36>
________________________________

**Comment by xavery** [comment]
The language names are now translatable, have fun.

**Comment by CAPRICORNX10X** [comment]
Thank you

השג את Outlook עבור Android<https://aka.ms/ghei36>
________________________________
