### ISSUE TITLE
Movie starts later not at the Beginning

### ISSUE THREAD

**Issue by wolflopnew** [justdan96/tsMuxer#593]
Film created with Tsmuxer only starts burned on UHD from 1.02. Min. Original chapters are included.
The film only starts on the player at 1 min.
Please help with troubleshooting. Original file is an Mp4 Upscale with 80 GB.

**Comment by jcdr428** [comment]
@wolflopnew can you please identify latest working version.

**Comment by wolflopnew** [comment]
Its the last nightly verion of Tsmuxer and all versions of the last 5 nightly

**Comment by wolflopnew** [comment]
I dont know a latest working version....

**Comment by jcdr428** [comment]
Ok, so the problem likely always existed. Can you please share the BDMV folder (preferably use your OneDrive), no Zip please as I can't download GBs. Never managed to download your previous files.

**Comment by wolflopnew** [comment]
Thanks for your help . I made a rar file on 1fichier only 41kb without the 81 GB streamfile.
Hope this works...
https://1fichier.com/?jkyl32a8xj4slbe544o1

**Comment by jcdr428** [comment]
@wolflopnew please I need the BDMV folder, not the .iso.
With the .iso -same as a zip- I have to download the whole file, which I don't manage to do.
With the folder I can select to download only part of the m2ts.

**Comment by wolflopnew** [comment]
Heere is the folder link
https://1drv.ms/u/s!AifiITtpdjN1h3n8wJ3m_tBToWsC?e=FEbI7l
Can also help withe parse bug i reportet?

**Comment by jcdr428** [comment]
@wolflopnew I don't have any Blu-ray player, but on my PC with WinDVD and PowerDVD the video starts from the beginning.
Timings in the clpi and the mpls are the same and correct.
So I can't help...

**Comment by wolflopnew** [comment]
Film also starts normally with me s.PC. Only when I burn to CD does the film not start from the beginning.
However, if I compress the film to 45 Gb with DVD Fab and burn Blu-ray, the playback works.

**Comment by ValZapod** [comment]
> Only when I burn to CD does the film not start from the beginning.

To dvd you mean? But that reencodes?

**Comment by wolflopnew** [comment]
Not to DVD. with the DVDfab UHDCreator.

**Comment by wolflopnew** [comment]
I tried another 4k upscale today. the same here again, if I burn the generated disc to Blu-ray, the film only starts from 1 minute. If I shrink the iso generated with Muxer with DVDFab, the film can be played without any problems from 0 minutes.

**Comment by wolflopnew** [comment]
Still the problem... with the next movie...

**Comment by jcdr428** [comment]
Issue redundant with #596n closing.
