### ISSUE TITLE
Box character drawn at the end of line when rendering subtitles in W64 build

### ISSUE THREAD

**Issue by shag00** [justdan96/tsMuxer#598]
Using any release from 1/3/20 or later results in subtitles being muxed incorrectly. Every line of every subtitle has a box drawn at the end as shown in the attachment Using the W64 version.

How something like this can go unnoticed for such a long period of time can only be attributed to your prolonged refusal to actually release a release version of this software. Do you not understand that the vast majority of people are not interested in daily builds, they want well used and stable releases that meet their needs. Version 2.6.12 (which I understand is the last stable release) from 2014 is not that. This only came to my attention because I fresh installed my OS.

I have not tested UHDs yet.

![Tsmuxer](https://user-images.githubusercontent.com/37562304/167376081-bcb58de2-ad98-4d95-be15-97e4ba16e0a1.png)

**Comment by Randrianasulu** [comment]
just a wild guess: may be this box represent undisplayable (with current font) character?

**Comment by Randrianasulu** [comment]
aftervlittle digging I found this commit, but  it looks  a bit invasive for (temporary, for testing) reverting...

https://github.com/justdan96/tsMuxer/commit/9670fd6b19599efb44b66f5c70dc43d112119bd1

@shag00 can you try and check srt files themselves - are they having unix or windows line endings? Also, installed fonts might play a role, as well as active codepage (on older Windows?)

**Comment by shag00** [comment]
Wild of the mark is what you mean. The same raw files muxed with MKVToolnix or TSMuxer release earlier than 29/2/20 work perfectly. The srt file used for the subtitle has been checked and has no issues. In any case, even assuming you are correct it would not affect every line of every srt file. As a final check to my reply I just downloaded a TV show from the internet which works fine, I demuxed it and remuxed the streams and the problem of the box is still there.

**Comment by shag00** [comment]
@Randrianasulu 
not sure what you are asking or how to check. All my subtitles are produced by a program called subtitle edit which I have been using since about 2014 without issue. As I can shown the muxing with MKVToolnix works fine and pin point when TSMuxer started having problems is it not resonable to assume that TSMuxer is the problem? I download 2 versions of the same program issued 1 day apart and 1 works and 1 does not on the same system, that's not a line ending issue.

**Comment by shag00** [comment]
Further investigation reveals further problems with the 1/3/20 release, which were subsequently corrected at some point, there is no sound when the streams are muxed as .ts though .m2ts is not affected.

**Comment by Randrianasulu** [comment]
by line endings I mean

[diff between windiws and unix on how to signal end of line](https://en.m.wikipedia.org/wiki/Newline)

**Comment by shag00** [comment]
OK, I understand, how to check?

**Comment by Randrianasulu** [comment]
it might be line ending issue in tsmuxer... at least from symptoms it looked like one.

yeah, some bugs fixed in new version - old version (w/o bug) not as useful as one hoped.. anyway, thanks for testing (i replied via email but apparently this email not yet arrived here..)

**Comment by Randrianasulu** [comment]
@shag00  this [answer](https://stackoverflow.com/questions/32255747/on-windows-how-would-i-detect-the-line-ending-of-a-file) suggest notepad++ (I am on linux, so midnight commander shows those windows line endings by default)

**Comment by shag00** [comment]
Tell me how to find end of line that you want

![tsmux](https://user-images.githubusercontent.com/37562304/167392616-df498784-864f-4892-8ff6-e1f2c47f4dfd.png)

**Comment by Randrianasulu** [comment]
i just pressed f4 (edit) and if there big ^m at every line end - its windows)

**Comment by shag00** [comment]
seems it's linux then

**Comment by Randrianasulu** [comment]
@shag00 are you usung WSL2 on Win10, or this is different ubuntu install? (just asking because hopefully compiling cli version of tsmuxer on linux should be a bit easier than on user-oriented Windows.. if you have time you can try to build latest tsmuxer on ubuntu and see if problem exist there too..)

**Comment by Randrianasulu** [comment]
also, you can try to manipulate line endings with dos2unix and unix2dos cli utilites..

**Comment by shag00** [comment]
I have a dual boot system. I have no idea what WSL2 is. On Kate in ubuntu I can change line endings between windows mac and linux though.

**Comment by Randrianasulu** [comment]
@ WSL2 is new way of running Linux commands (or even whole distro!) on Windows 10

[Microsoft says](https://docs.microsoft.com/en-us/windows/wsl/install)

**Comment by shag00** [comment]
tested this by changing line ends to windows, ending rectangle still shows up

**Comment by Randrianasulu** [comment]
( then it was not it... sorry.

**Comment by shag00** [comment]
I hate to say i told you so but the evidence is pretty overwhelming. If the problem was with the input srt then it would also be apparent when muxed with earlier versions of TSMuxer or MKVtoolnix. The whole problem arises because there is no release version available for most people to use. Everyone testing their own daily version does not work because there are not enough users, even windows with hundreds of millions of users and no doubt a very large pool of testers gets their releases wrong.

Can you reproduce the same results I am getting?

**Comment by Randrianasulu** [comment]
if you can pit small srt/video par and meta for running tsmuxer I can try on Termux and Slackware...

right now release might be not very good idea, see other recent issues and 'ts buffer management problem'. May be beta? And then series of RCs... (without major changes) 

just my (non-dev) opinion..

**Comment by shag00** [comment]
What do you call small, 1TB, 100MB or something else?

It is very hard for me to take your opinion seriously when the last stable release was released in 2014. It's now 2022. By what logic or means do you justify to yourself that that is reasonable? I don't mean to give you a hard time it's just that I am very surprised you would say that.

**Comment by Randrianasulu** [comment]
100 mb should be enough? (just enough for seeing few subtitle lines)

I mean some recent bugs on Mac/arm... are you prefer release with known bugs? (this may hapoen, but then  it should be stated in release notes)

tsmuxer was only 'recently' open sourced (2019) so a lot of time between 2014 and 2019 no one touched it..

**Comment by Randrianasulu** [comment]
[issue 579](https://github.com/justdan96/tsMuxer/issues/579)  for example..

**Comment by Randrianasulu** [comment]
bug/issue about releasing:
https://github.com/justdan96/tsMuxer/issues/502

**Comment by shag00** [comment]
My retort would be that the release of 29/2/20 appears to be stable and works. It could have been released as a stable build and most people who use TSMuxer would be using it and be happy. A stable release does not mean a perfect release, especially in relation to new hardware (Apple ARM). What is does mean is that proven hardware (X86 processors) and software (Windows 10) can do what the software is designed to do which in essence is to demux and mux raw audio/visual streams fro/to a number of containers, mainly .ts and .m2ts.

Apple has about 12% of the PC market and M1 ARM processors would account for maybe 10% of that which accounts for three tenths of two fifths of fuck all and for this no stable release is released? Yes, you are quite correct, known bugs should be advised via the release notes. What, for example, that means is that I can download Ubuntu 22.04 and use it knowing that I cannot dual boot without a work-around but pretty much everything else works and in many cases better than they did in the previous release.

**Comment by shag00** [comment]
I cut a file down to 5 minutes but it's still 189MB, any good?

**Comment by Randrianasulu** [comment]
yes, ivll try to download it

**Comment by Randrianasulu** [comment]
you can't put it on google drive or mucrosoft drive? (like other examples in issues)?

you can send link to me directly but then other devs here will not see it....

**Comment by justdan96** [comment]
@shag00 please be aware we have a code of conduct and we are a team of volunteers, your issue won't be looked at any quicker or more thoroughly by swearing. 

Releases is something we have been looking at but as I mentioned we are all volunteers and for me in particular I haven't had much free time at all recently. Please be patient with us.

As for how the regression was missed we rely on the community to test releases and report issues, we don't have any sort of automated testing infrastructure and I'm not sure how we would go about creating some. Any suggestions on that are very welcome.

Can you confirm your choice of font for us please?

**Comment by shag00** [comment]
@[Randrianasulu](https://github.com/Randrianasulu)
can you give me a clean e-mail address to use to send you the link.

**Comment by Randrianasulu** [comment]
@shag00 randrianasulu@gmail.com

**Comment by shag00** [comment]
@justdan96 

congratulations on your code of conduct. If you look more closely I am not swearing, I am using an old saying which contains what some people deem a swear word. I am most certainly not swearing at @Randrianasulu ! There is no need to swear at him because he has done nothing wrong to me or mine. I am as pleased as punch you guys decided to take up this project and all kudos and thanks to you. What I am talking about is the UX.

The rest of your comment falls on deaf ears, we are after all talking about 8 years. When you make these comments do you stop to think about what the listener is thinking or hearing? Even if you have only been involved since say 2019, do you think it makes a difference? I am not suggesting you are lazy or anything of sort. It appears to me you are waiting for a perfect product (which is a bit of a pipe dream) which causes you to delay and delay which ends up causing you even more problems, as is the case here, where a very old error has been uncovered because the bulk of your users are not using dailies and won't upgrade until there is a stable release or they run into some type of problem. It is not as if a stable release has not been requested.

**Comment by shag00** [comment]
@Randrianasulu 
link sent

**Comment by shag00** [comment]
@justdan96 
You might consider that I have spent the last 3 hours predominately on this issue and have sort advise from @Randrianasulu  to provide the information he was after. This is not something a malcontent would do, is it? I have a working TSMuxer, I don't need you to do anything to allow me to carry on my merry way, no doubt, very much the same position you are in. My motives are similar to yours, to provide a better product.

**Comment by shag00** [comment]
sorry, the font i am using is ariel

**Comment by Randrianasulu** [comment]
@shag00 I looked at provided file with mpv and ffplay (2.8.15! so quite old) and mediainfo.. it seems to be PGS subtitle (as intended after tsMuxer?) and.. it looks correct? At least I can't see those little squares you showed in screenshot...

**Comment by justdan96** [comment]
@shag00 perhaps try using Noto Sans or another Unicode font and see if the same squares appear? I don't have a Windows machine to test on but it's possible a Unicode character is being added to the output which can't be handled by your chosen font. Subtitles are handled differently on Windows and Unix, which may explain why others can't see the same.

**Comment by shag00** [comment]
@Randrianasulu 
sorry I have sent a replacement file with srt subtitles

**Comment by shag00** [comment]
Here is my attempt to use Nato Sans. As you can see it is produces little rectangles in the editing software, Subtitle Edit. In each case the little rectangles are used in place of musical notes, "♪".

![tsmux1](https://user-images.githubusercontent.com/37562304/167506371-9fea4ab0-b324-44c8-a5a2-ed8e56862bd9.png)

**Comment by jcdr428** [comment]
@shag00 can you please post the .srt (or part of it) so that I can see what tsMuxer replaces the music symbol with.

**Comment by Randrianasulu** [comment]
I used this meta file (tsmuxer do not read eac3 sound from mkv for some reason - might be user error on my side! Ah, sure, wrong type of audio! I construct those in mcedit not in tsmuxer's GUI)

```
guest@slax:~$ cat /mnt/sdb2/tmp/bd.meta
MUXOPT --hdmv-descriptors --auto-chapters=1
V_MPEG4/ISO/AVC, /mnt/sdb2/tmp/test_file_001.mkv, track=1, contSPS
A_LPCM, /mnt/sdb2/tmp/test_file_001.mkv, track=2
S_TEXT/UTF8, /mnt/sdb2/tmp/test_file_001.mkv, track=3 font-size=64 default=force, video-width=1920, video-height=1080, fps=23.976, font-name="/usr/lib/cin/plugins/fonts/arial.ttf"

guest@slax:~$
```

and I still can't see squares? But if they appear instead of some (unicode) characters - this point at font/locale/encoding interplay.. I think?

**Comment by shag00** [comment]
[srt.zip](https://github.com/justdan96/tsMuxer/files/8656156/srt.zip)

**Comment by shag00** [comment]
@jcdr428 
re the music symbol, I suspect we may have crossed wires here, the music symbol issue relates to Subtitle Edit which is a completely different issue to the TSMuxer issue. Even though Subtitle Edit can not display a music symbol using Noto Sans TSMuxer still recognises it and displays it correctly. 

The issue is that TSMuxer is appending something to the end of each line contained in an .srt file. It may be the carriage return that is the issue, I don't know. The whole test was merely to see if unicode font was an issue, which we now know is not the case. 

Quite clearly, whatever the problem is is contained in whatever commit(s) was added after 29/2/20 to create the release of 1/3/20. I still don't know if anyone else can reproduce the same error?

**Comment by shag00** [comment]
> I used this meta file (tsmuxer do not read eac3 sound from mkv for some reason - might be user error on my side! Ah, sure, wrong type of audio! I construct those in mcedit not in tsmuxer's GUI)
> 
> ```
> guest@slax:~$ cat /mnt/sdb2/tmp/bd.meta
> MUXOPT --hdmv-descriptors --auto-chapters=1
> V_MPEG4/ISO/AVC, /mnt/sdb2/tmp/test_file_001.mkv, track=1, contSPS
> A_LPCM, /mnt/sdb2/tmp/test_file_001.mkv, track=2
> S_TEXT/UTF8, /mnt/sdb2/tmp/test_file_001.mkv, track=3 font-size=64 default=force, video-width=1920, video-height=1080, fps=23.976, font-name="/usr/lib/cin/plugins/fonts/arial.ttf"
> 
> guest@slax:~$
> ```
> 
> and I still can't see squares? But if they appear instead of some (unicode) characters - this point at font/locale/encoding interplay.. I think?

Just mux without sound

**Comment by Randrianasulu** [comment]
@shag00 it works on Slackware with provided srt (even misic sign show up!)

I already fixed my meta file for using AC3 sound


![IMG_20220510_095114](https://user-images.githubusercontent.com/40185805/167566992-8db6bfcb-3e71-4138-868f-1e5a3e38645b.jpg)

**Comment by shag00** [comment]
@Randrianasulu 
S_TEXT/UTF8, /mnt/sdb2/tmp/Outlander.ENG.srt, track=3, font-size=56 default=force, video-width=1920, video-height=1080, fps=23.976, font-name="/usr/lib/cin/plugins/fonts/arial.ttf"

This is telling me you have not muxed the file with TSMuxwer?

**Comment by Randrianasulu** [comment]
@shag00 I do not have any other software to turn srt into pgs...

May be I butched this line, still tsmuxer worked and ffplay too...

what caught your eye?

**Comment by shag00** [comment]
@Randrianasulu 

You have totally confused me with, "I do not have any other software to turn srt into pgs...". That is part of what TSMuxer does, turn .srt files into .pgs files. .srt files are a valid input to TSMuxer and have been for almost 20 years. You do not need any other software.

To confirm what we are doing, we are combining an H264 video file with a .ac3 audio  file and an .srt subtitle file with TSMuxer. Another format of sound file can be used without affecting the finished product. Once those files have been created no other is used. 

If you are using some other program to create a .pgs file from the .srt file then you likely won't have a succeeding rectangle in your text display because the error is in TSMuxer converting the .srt file to a .pgs file.

What caught me eye? - .m2ts containers do not support srt streams.

**Comment by Randrianasulu** [comment]
> What caught me eye? - .m2ts containers do not support srt streams.

well, this is how tsmuxer wirks for me - it takes few streans (stand alone or muxed into mkv, or mux of two methods) and while just muxing audio and video it also turn srt into pgs stream, to mux into final ts.

**Comment by shag00** [comment]
Addressing your EDIT,
 You appear to be creating a BD ISO (my lack of technical knowledge may have led me to the wrong conclusion), this is not what I am doing. I am just creating a simple .m2ts file.

**Comment by Randrianasulu** [comment]
![1652173928658](https://user-images.githubusercontent.com/40185805/167593528-d5f5365b-4238-44ca-96c4-9d3d49d60ea3.jpg)

well, using latest tsmuxer/win32 under wine-5.5 (I do not have Arial font for some reason, so I used Dejavu Sans) - still no artefacts?

**Comment by Randrianasulu** [comment]
![1652174164171](https://user-images.githubusercontent.com/40185805/167594337-6bcce067-22dd-43b1-b885-ce3ddaaa49ec.jpg)

this is how my subtitle settings looks like

**Comment by shag00** [comment]
Which of the 6 asset releases are you using?

**Comment by Randrianasulu** [comment]
@shag00
https://github.com/justdan96/tsMuxer/releases/download/nightly-2022-05-05-02-59-07/w32.zip

w32.zip

**Comment by shag00** [comment]
OK, so I setup this 32 bit file and the result did not change. Some other errors are apparent but I won't cloud the issue with them.

**Comment by shag00** [comment]
If I run the appimage version the problem is solved.

**Comment by justdan96** [comment]
It has to be with the specific code used for the Windows subtitle management, I might have a Windows VM somewhere to try to test this on, but we I think have to analyse the SRT output from Linux and Windows to compare.

**Comment by shag00** [comment]
@justdan96 
thanks, as you appear to have pin-pointed where the issue is I will explain the other error in using today's release. In addition to the rectangle issue some of text is coloured black, appears to be totally random and does not affect every line.

**Comment by justdan96** [comment]
Actually we can just compare SRT output from before 2020-01-03 with after as well, if that is easier.

@xavery would you be able to check if this commit may have changed the string handling - either it includes the LF character or is adding a /0 char or something like that? 
https://github.com/justdan96/tsMuxer/commit/9670fd6b19599efb44b66f5c70dc43d112119bd1#diff-9d4045e9c9ad4aa5a29bd9b2120977356ecb5820319dd5f17dc790a078e692a7

**Comment by shag00** [comment]
@jcdr428 
I have a file, it is 4.2 GB, do you want that or a much smaller one (5 min only)? I use both VLC and MPV, both display the same thing.

**Comment by shag00** [comment]
Please also give me a clean email address to send it to.

**Comment by jcdr428** [comment]
@shag00 5min. is enough.
jcdr428.github@gmail.com

**Comment by shag00** [comment]
link sent

**Comment by jcdr428** [comment]
Link not received as of this morning 7am. Can you please send from another email address ?

**Comment by shag00** [comment]
I re-sent the file with a copy to myself and I have received it. As it's from one drive I cannot change the sending address.

**Comment by jcdr428** [comment]
> In addition to the rectangle issue some of text is coloured black, appears to be totally random and does not affect every line.
Actually it is not random, color always changes after letter 'u'.
So you have specific letters that create specific actions: \x75 ('u') changes color, \x0A (return) displays a square.

Other than that I have no idea what could create this in commit https://github.com/justdan96/tsMuxer/commit/9670fd6b19599efb44b66f5c70dc43d112119bd1

**Comment by shag00** [comment]
@jcdr428 
the colour issue only applies to very recent releases not the 1/3/2020 release referred to in this bug report, please ignore.

**Comment by jcdr428** [comment]
@shag00 can you please identify the latest release working without the color issue ?

**Comment by shag00** [comment]
@jcdr428 
Re the colour issue, I have tested all the way back to the first release, 16/12/19 and find even it is affected. I can confirm that it occurs after a line that contains the letter "U" is encountered. The remainder of the line after the "U" is coloured black. The next line returns to normal (white) colour.

As the last time I clean installed my PC was early 2020 I cannot recall what version or from what source I acquired TSMuxer from but I have been using it on a daily basis since before that time and the issue was not present. I suspect it was a patched version from DOOM9 or something as I do remember I did not become aware that you had taken up this project until some time after you had taken it up. I think the colour problem should be a separate ticket.

**Comment by xavery** [comment]
Yup, my bad. Even though I wasn't able to reproduce the issue directly, there is a problem in the `GraphicsPath::AddString` call in the Win32 subtitle renderer.

**Comment by xavery** [comment]
@shag00 Please retest and reopen if the issue is still not resolved. You can use the following builds to test : 

Windows 64 : https://github.com/justdan96/tsMuxer/suites/6505476418/artifacts/241783524
Windows 32 : https://github.com/justdan96/tsMuxer/suites/6505476416/artifacts/241783538

Just replace the `tsMuxeR.exe` you're currently using with the one from the archive and re-run the mux.

**Comment by jcdr428** [comment]
> I think the colour problem should be a separate ticket.

@shag00 Can you please open the issue (as I suppose it is still an issue) ?

@xavery glad to see you back. That must have been hell to find this bug !

**Comment by shag00** [comment]
My result is that neither player, VLC or MPV, detect a subtitle stream. Though viewing the file with Media Info returns the following for the text section:
Text
ID                                       : 4608 (0x1200)
Menu ID                             : 1 (0x1)
Format                               : PGS
Codec ID                            : 144
Delay relative to video       : 3 s 41 ms

**Comment by jcdr428** [comment]
@shag00 can you please upload a sample of the m2ts ?

**Comment by xavery** [comment]
Worksforme with Big Buck Bunny and the following metafile, both with TS and M2TS output. 
```
MUXOPT --no-pcr-on-video-pid --new-audio-pes --hdmv-descriptors --vbr  --vbv-len=500
V_MPEG4/ISO/AVC, "bbb_sunflower_1080p_30fps_normal.mp4", track=1, lang=und
A_MP3, "bbb_sunflower_1080p_30fps_normal.mp4", track=2, lang=und
A_AC3, "bbb_sunflower_1080p_30fps_normal.mp4", track=3, lang=und
S_TEXT/UTF8, "Outlander.S06E08.I.Am.Not.Alone.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb_Subtitles01.ENG.srt",font-name="Cascadia Code",font-size=24,font-color=0xff55aa7f,font-underline,font-strikeout,bottom-offset=24,font-border=5,text-align=center,video-width=1920,video-height=1080,fps=30
```
[vlc screenshot here](https://user-images.githubusercontent.com/127875/168424022-30bf5525-0bf6-447d-bcc5-149ec65e540d.png)

Share your metafile maybe?

**Comment by shag00** [comment]
sent incorrect file, sending correct one now

**Comment by shag00** [comment]
@xavery 
how to obtain the metadata info you want?

**Comment by xavery** [comment]
@shag00 If you're using the GUI, just copy and paste the bottom part of the window. If you're using the commandline, it's the first file that you pass to the application, i.e. if you call tsmuxer as `tsmuxer myfile.meta output.ts`, then what we're looking for is the contents of `myfile.meta`.

**Comment by shag00** [comment]
MUXOPT --no-pcr-on-video-pid --new-audio-pes --hdmv-descriptors --vbr  --cut-end=300000ms --vbv-len=500
V_MPEG4/ISO/AVC, "/mnt/data1/A/Halo.S01E08.Allegiance.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb_Video01.UND.h264"
A_AC3, "/mnt/data1/A/Halo.S01E08.Allegiance.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb_Audio01.ENG.eac3"
S_TEXT/UTF8, "/mnt/data1/A/Halo.S01E08.Allegiance.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb_Subtitles01.ENG.srt",font-name="Arial",font-size=30,font-color=0xffffffff,bottom-offset=24,font-border=5,text-align=center,video-width=1920,video-height=960,fps=24

**Comment by shag00** [comment]
AH! think I found it seems I choose aerial, works with other font

**Comment by shag00** [comment]
can re-close

**Comment by shag00** [comment]
@justdan96 
colour problem is also fixed.

**Comment by Randrianasulu** [comment]
On Monday, May 9, 2022, shag00 ***@***.***> wrote:

> @Randrianasulu <https://github.com/Randrianasulu>
> not sure what you are asking or how to check. All my subtitles are
> produced by a program called subtitle edit which I have been using since
> about 2014 without issue. As I can shown the muxing with MKVToolnix works
> fine and pin point when TSMuxer started having problems is it not resonable
> to assume that TSMuxer is the problem? I download 2 versions of the same
> program issued 1 day apart and 1 works and 1 does not on the same system,
> that's not a line ending issue.
>


well, thank you for pinpointing faulty version.. I am not developer enough
for seeing problem in code, I just saw sometimes codepage/font/locale/line
endings interplay  can give all sort of bugs.

I have no doubt you can reproduce problem on your machine/system - but it
might be specific to your Windows installation, or some type of install or
some setting ...
