### ISSUE TITLE
Demux THD Stream from MKV

### ISSUE THREAD

**Issue by Mipeli** [justdan96/tsMuxer#600]
Testing I'm found out that the at some movies at demux THD stream (without embedded AC3) from MKV file behind using TSMuxer this THD stream (without embedded AC3) isn't consistent with demux THD stream (without embedded AC3) behind using MKVExtract. How find out, which of these demux THD streams (without embedded AC3) is the correct and consistent with original, when original I don't have. Eventually it is possible somehow find out why are these two demux THD streams (without embedded AC3) different? Which app then use to demux THD streams (without embedded AC3) whether TSMuxer or MKVExtract?

Thank for fix.

**Comment by jcdr428** [comment]
@Mipeli on the few trials I've done, tsMuxer and MKVExtract output the same file / CRC32.
Can you please upload a sample mkv for which this is not the case.

**Comment by Mipeli** [comment]
Current have not nope MKV, but once some again this bug will have so write. Maybe was error in MKV Toolnix, is about to be updated to the latest version so I'll see if with bug will appear.

**Comment by jcdr428** [comment]
@Mipeli did you find any mkv sample where mkvextract output is different from tsmuxer output ?

**Comment by jcdr428** [comment]
Closing -can be reopened upon request when a sample is available.
