### ISSUE TITLE
Can't remux MP4: “MP4/MOV error: Invalid SRT frame”

### ISSUE THREAD

**Issue by rkjnsn** [justdan96/tsMuxer#607]
I have an MP4 file that I'm trying to remux into an MP4 file. If I try to add it to the GUI, nothing happens. Running the command-line tool in track detection mode, however, I get 

    tsMuxeR version git-d3c495d. github.com/justdan96/tsMuxer
    Error: MP4/MOV error: Invalid SRT frame at position 2240905

The file plays fine, however, and I was able to remux it into an MKV and import that into tsMuxer. It'd be nice to avoid the extra step, though. If there's an error with one of the tracks, it seems like it would make more sense to skip it with a warning instead of refusing to work with the file altogether.

**Comment by jcdr428** [comment]
@rkjnsn can ypu please provide the mp4 provoking the bug.

**Comment by rkjnsn** [comment]
Attached a small segment that demonstrates the problem.

https://user-images.githubusercontent.com/7364197/170848014-2a39d784-fddf-42a3-8018-3914b90c5648.mp4

**Comment by jcdr428** [comment]
@rkjnsn no video attached (message "No video with supported format and MIME type found"). Can you please provide a link ?
Or if the srt is enough to provoke the bug in tsMuxer, please upload the srt in github.

**Comment by rkjnsn** [comment]
Agh. Looks like Github decided to make things complicated by embedding the link as a video. You can still right click it and select copy video link (on my browser, at least), but here's the URL directly: `https://user-images.githubusercontent.com/7364197/170848014-2a39d784-fddf-42a3-8018-3914b90c5648.mp4`

**Comment by jcdr428** [comment]
@rkjnsn there are some text modifiers that tsMuxer does not seem to parse correctly.
I have applied a quick patch, can you try tomorrow.
The modification of the SRT according to the modifier (in this case, italics on part of the subtitle) is still to be done.

**Comment by rkjnsn** [comment]
With the May 31st Linux build, I get

    tsMuxeR version git-d77bf22. github.com/justdan96/tsMuxer
    double free or corruption (out)

**Comment by jcdr428** [comment]
@rkjnsn indeed I tested the fix with Windows, I forgot that with Linux the subtitles were going through freetype.
Anyway MP4 subtitles with inline modifiers seem to be rare enough, I'll wait for your sample.

**Comment by jcdr428** [comment]
@rkjnsn I have pushed a fix to fully remove the parsing of the tx3g modifiers until it is implemented. Please try tomorrow or try https://github.com/justdan96/tsMuxer/suites/6731994755/artifacts/256788981.

I am still interested by your samples, I could not find any mp4 sample using tx3g modifiers on the net.

**Comment by rkjnsn** [comment]
The 2022-06-02 build does indeed process the file without crashing. As expected, however, all italics are lost unless I first use an external tool to convert them to an external .srt file and add that.

I'm having trouble extracting a sample that reproduces the `double free or corruption (out)` crash on 2022-05-31. The full file is about 10 GiB. Is there a good way to get that to you?

**Comment by jcdr428** [comment]
For 10GB the best would be to create a bittorrent link with an open tracker.

**Comment by rkjnsn** [comment]
Alright, I sent you an e-mail. Let me know if there's a better way to get it to you.

**Comment by justdan96** [comment]
Mega.co.nz gives you 20GB free storage, Google Drive gives you 15GB I think.

**Comment by jcdr428** [comment]
@rkjnsn please try tomorrow's release, thanks.
