### ISSUE TITLE
About wav files with missing channel layouts

### ISSUE THREAD

**Issue by MayaOzz** [justdan96/tsMuxer#613]
I am trying to MUX a m2ts file containing Dolby TrueHD with tsMuxer after extracting the audio part and converting it to PCM. According to the corresponding track information in MediaInfo, the channel layout is "L R C LFE Ls Rs Cb".
However, if you convert this file to wav with xrecode3, the channel layout information is lost and tsMuxer displays the following warning:.
> Warning! Multi channels WAVE file for stream 3 do not contain channels configuration info. Applying default value: L R C BL BR SL SR

Is there any way to change the default value of tsMuxer or add information to the wav file?

**Comment by jcdr428** [comment]
@OmniSoundsLab you cannot do this with tsMuxer, you'll have to use a hex editor to write the channel information.

**Comment by OmniSoundsLab** [comment]
@jcdr428 Oh ...... All right. You mean you need to edit the layout information before loading it into tsMuxer. Thank you for your reply.
