### ISSUE TITLE
HEVC video - Track was not recognized and ignored

### ISSUE THREAD

**Issue by HoffmannTom** [justdan96/tsMuxer#615]
Hello,
I used ffmpeg to do a 2-pass encoding of a clip. The clip is HDR10 compliant and plays well on VLC.
MediaInfo doesn't show any hints to me and DVDFab is also importing the HEVC-mp4 file.
However, tsmuxer shows the error "track 1 was not recognized and ignored". After this error, the video track is shown in tsmuxer as usual. Also working with the file seems to be fine after this error message.

It looks like tsmuxer is searching something within the mp4 file and can't find the information in the stream.
I also added the AUD fields as NAL to be BD compliant.
I could strip it down to a 160 kb sample: https://temp.sh/tvKHm/snippet.mp4 (valid for 3 days)

Could you kindly take a look at it?
Thank you in advance!

**Comment by jcdr428** [comment]
Hi @HoffmannTom , the cli command gives:
```
tsMuxeR version git-7165e3b. github.com/justdan96/tsMuxer
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
B-pyramid level 1 detected. Shift DTS to 2 frames
Track ID:    1
Stream type: HEVC
Stream ID:   V_MPEGH/ISO/HEVC
Stream info: Profile: Main10@5.1 Resolution: 3840:2160p  Frame rate: 23.976
Stream lang: und

Track ID:    2
Can't detect stream type

Duration: 02:35:26.609
```
So actually this is the second track which is not recognized, not the HEVC track.
It is misleading, but tsMuxer reports unrecognized tracks from track 0, independently of actual PID.

**Comment by jcdr428** [comment]
@HoffmannTom I've pushed a fix to make the warning clearer by also showing the TrackId.
`Track 1 (TrackID 2) was not recognized and ignored.`

**Comment by HoffmannTom** [comment]
Great! Thanks a lot 👍 😃
