### ISSUE TITLE
Some mp4 files' video/audio are out of sync after being muxed to ts

### ISSUE THREAD

**Issue by TheSpider12** [justdan96/tsMuxer#617]
As the title says. This is the name of one of the movie files where I noticed the above issue: Loki.S01E02.The.Variant.2160p.WEB-DL.DDP5.1.DoVi.HEVC-L0L. Actually, most, if not all, of those Loki season 1's movie files have this issue. The original mp4 file is ok, but after being muxed to ts/m2ts, the video/audio are out of sync.

**Comment by jcdr428** [comment]
@TheSpider12 please try https://github.com/justdan96/tsMuxer/suites/7049463120/artifacts/277706307 (put tsMuxer.exe with your usual tsMuxerGui.exe)

**Comment by jcdr428** [comment]
@TheSpider12 please try with other movie files, and if you confirm no issues I will push the fix to the main tsMuxer.

**Comment by TheSpider12** [comment]
I tested with another movie and saw no issues. Please include the exe in the latest release. Thanks.

**Comment by jcdr428** [comment]
@TheSpider12 done.
