### ISSUE TITLE
SRT subtitles out of sync after demux

### ISSUE THREAD

**Issue by TheSpider12** [justdan96/tsMuxer#621]
The recent release of tsmuxer fixed the "Can't demux srt subtitles" bug (#616) I reported a few weeks ago but I realize today that the demuxed srt subtitles are out of sync if I reattach it to the original mkv/mp4 movie file and mux it as ts/m2ts. The out of sync issue gets worse as the movie plays. You can try the first episode of Obi-Wan.Kenobi.S01.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.MKV.x265-KOGi[rartv]. Movie files that have pgs subtitles do not seem to suffer from this issue.

Edit: I notice that the original fps of the subtitles is 24 fps like the video track. After demuxing, it becomes 23.976 fps. When reattach it to the original video track, the fps is converted from 23.976 to 24 to match the video. Is that the cause of the issue?

_Demuxing srt sub from the original file:_
![Capture](https://user-images.githubusercontent.com/107785238/177156186-6d4b4c73-3582-404b-b007-dd067be4c837.PNG)

_Muxing the demuxed srt sub with the original file as ts/m2ts:_
![Capture](https://user-images.githubusercontent.com/107785238/177156261-c8401067-091d-4c78-9de8-7e848c496ca8.PNG)

**Comment by jcdr428** [comment]
@TheSpider it should be fixed in tomorrow's release.

**Comment by jcdr428** [comment]
@TheSpider12 if the original was in 24fps and you demuxed in 23.976fps / remuxed in 24fps, just remux the m2ts with the 24fps video but with subtitle fps = 24000/1001.

**Comment by jcdr428** [comment]
@TheSpider12 you have to save the .meta file, edit the sub fps manually in the .meta file, and use the command line tsMuxer.exe file.meta output.m2ts

**Comment by TheSpider12** [comment]
> @TheSpider12 you have to save the .meta file, edit the sub fps manually in the .meta file, and use the command line tsMuxer.exe file.meta output.m2ts

So I tried this but when I edited the file and put 24000/1001 into sub fps, running the command line displayed an error - sth along the line of "the framerate is not standard". So I tried changing it to 23.976 instead and it successfully ran but the the output file still has out of sync subtitles.
