### ISSUE TITLE
Subtitles not appearing after muxing

### ISSUE THREAD

**Issue by TheSpider12** [justdan96/tsMuxer#625]
The latest release of tsmuxer fixed my previously reported issue #621. However today I came across this mp4 file: [edited]. After demuxing the subtitles, reattaching them to the video and muxing as m2ts, the subtitles do not appear. Other episodes seem fine, just this episode has this issue. I checked the original file and the subtitles appear just fine.

**Comment by jcdr428** [comment]
@TheSpider12 please provide a sample, thanks.

**Comment by TheSpider12** [comment]
> @TheSpider12 please provide a sample, thanks.

What's the best way to provide a sample? The mkv file is pretty large so is there a way to extract a small clip from it with all the video/audio/subtitles intact and give you a link to that clip?

**Comment by jcdr428** [comment]
@TheSpider12 please create a torrent file with an open tracker address and send me the torrent file on jcdr428.github @ gmail com

**Comment by jcdr428** [comment]
@TheSpider12 Please try tomorrow's release.

**Comment by jcdr428** [comment]
@TheSpider12 please confirm the bug is fixed.

**Comment by TheSpider12** [comment]
> @TheSpider12 please confirm the bug is fixed.

Hi. It's fixed. Thank you.
