### ISSUE TITLE
About the setting of "default track"

### ISSUE THREAD

**Issue by meitp** [justdan96/tsMuxer#626]
After adding the main playlist of the Blu-ray disc to tsMuxer, the default audio track and default subtitle track will be automatically displayed under "Default Track". The default audio track and default subtitle track shown here are just the first audio track and the first subtitle track of the imported Blu-ray original disc, not the real "default track". In the case of not changing the "default track", play the folder generated by MUX, the actual default audio track and subtitle track are not exactly the same as the default audio track and default subtitle track under "default track", but It is exactly the same as the default audio track and subtitle track of the original disc, and the subtitle track is basically closed. Hope the two will be consistent.

**Comment by jcdr428** [comment]
@meitp assessing which default audio/subtitle applies to which playlist would be difficult, as the info is generally buried in the bdjo files or the hdmv commands. When no default track is selected in tsMuxer, there is simply no default track selected in the output Bluray.
