### ISSUE TITLE
Bad frames detected during Demux

### ISSUE THREAD

**Issue by ferindel8783** [justdan96/tsMuxer#628]
Sorry in advance if this problem has already been reported, but I didn't find any trace of it when searching for it.

I have been using tsMuxer to demux streams from BluRay disks several times without any problem. However, I encountered problems while trying to demux two BluRay disks today. For these, I get the following message in the tsMuxer output window:

Decoding DTS-HD stream (track 1): bad frame detected at position NN:NN:NN,NNN. Resync stream.

This happens only with DTS-HD streams, and not with AC3 ones. I muxed the resulting streams and got an MKV file. There are indeed some frame problems at the positions identified (some artefacts in the image), and I think that the audio is not synchronized anymore after that.

Could someone please tell me how to solve this problem.

Thank you in advance,
ferindel

**Comment by jcdr428** [comment]
@ferindel8783 no way to tell without testing the faulty files. Please give a link to download the files on jcdr428.github@gmail.com

**Comment by ferindel8783** [comment]
Actually, it happens with all the BluRay disks that I'm downloading from one website, so I think that there's a problem with the resources that they are providing, and I'm going to try to find other BluRay disks. Thank you for your help anyway.

**Comment by donnafaye0323** [comment]
> @ferindel8783 no way to tell without testing the faulty files. Please give a link to download the files on jcdr428.github at gmail com
 
This is a screenshot of this error:
![Screenshot from 2023-10-10 14-24-08](https://github.com/justdan96/tsMuxer/assets/40868495/02096ed0-59e1-4a76-a0a0-5c5d46fabcf3)
