### ISSUE TITLE
Downconvert option should NOT be active for audio tracks that have no core stream embeded

### ISSUE THREAD

**Issue by GrzeWier** [justdan96/tsMuxer#630]
Hi
Downconvert option should NOT be active for audio tracks that have no core stream embedded.
Resulting file will not have audio when this option is used.
I guess this primarily applies to EAC3 ?

![downconvert](https://user-images.githubusercontent.com/96982951/183312554-3837668f-c822-438d-9469-e043bd03e805.jpg)

**Comment by jcdr428** [comment]
@GrzeWier Please try tomorrow's release.

**Comment by jcdr428** [comment]
Closing. Can be reopened upon request.
