### ISSUE TITLE
Problem to start tsMuxer on Linux Mint

### ISSUE THREAD

**Issue by DeVlaamseLeeuw** [justdan96/tsMuxer#631]
Hello,
I installed the last version (tsMuxer v2.6.12) on my Linux Mint.
When I try to launch tsMuxer, I have this message : **_./tsMuxerGUI: error while loading shared libraries: libQtGui.so.4: cannot open shared object file: No such file or directory_**
I tried to install the package **_libqtgui4:i386_** but it's not working :
**_The following packages contain unmet dependencies:
 libqtgui4:i386: Depends on: libmng2:i386 (>= 1.0.10) but will not be installed
                  Depends: libqt4-declarative:i386 (=4:4.8.7+dfsg-7ubuntu1) but will not install
                  Depends: libqtcore4:i386 (=4:4.8.7+dfsg-7ubuntu1) but will not install
                  Recommend: qt-at-spi:i386 but will not install
E: Unable to fix problems, bad packages are in "keep as is" mode._**
I need your help to solve the problem.
Thank you.

Chris

**Comment by justdan96** [comment]
Did you try the latest binary from the Releases page? https://github.com/justdan96/tsMuxer/releases

**Comment by DeVlaamseLeeuw** [comment]
Hi Dan,
Thank you for your answer.
Unfortunately, I didn't use the last binary. It works now !!!!!!
Thank you.
Best regards.

Chris
