### ISSUE TITLE
apparent 48KHz/32 bit AAC audio file error

### ISSUE THREAD

**Issue by jt207** [justdan96/tsMuxer#635]
I'm trying to process video files from a Canon pro HD camera, and all files generate an error message in tsMuxer when added as input files. The error message is "Error: Invalid AAC frame for track #2 at position 540236" and the position is always 540236, regardless of input file.
The audio files are 48KHz, 32 bit AAC which is listed as a supported input format. The video is H.264 MPEG4 AVC part 10.

tsMuxer 2.6.12

![tsmuxer](https://user-images.githubusercontent.com/113696698/190649839-edd4e347-466f-4158-9381-d09127f3276e.jpg)
![mediainfo](https://user-images.githubusercontent.com/113696698/190649842-11888b93-22fb-4952-82ce-39bbc5cec86d.jpg)

**Comment by dts24436** [comment]
Yeah, just as it shows, most AAC audio tracks aren't recognized by this tsMuxer at all, M4A-packed files at least, and I'll have to use other tools to have them muxed into MPEG-2 TS files then dumped into tsMuxer.

**Comment by jt207** [comment]
Thanks for the reply. I checked a handful of short video files from my phone, and VLC seemed to think they were the same audio format (AAC, 48KHz, 32 bit) and same video format (but different frame rate). So I dropped some of those into tsMuxer and it appeared to like them.  I'll try some additional tools.

**Comment by jcdr428** [comment]
@jt207 tsMuxer 2.6.12 is obsolete. Please try latest version and report.
