### ISSUE TITLE
one film not properly muxing from mp4 to ts

### ISSUE THREAD

**Issue by galactic76** [justdan96/tsMuxer#636]
Hi! I found 1 film that not properly muxing from mp4 to ts
It says FPS error, try to mux it till aprox 25%, and then give the error
its The.Railway.Children.Return.2022
im not sure if can name source here , but its pretty good for googling
So, if you can fix it I will be very appreciated
Thank in advance

**Comment by jcdr428** [comment]
@galactic76 please try tomorrow's release, thanks.

**Comment by galactic76** [comment]
Unfortunatelly I already demux video and audio separately and the remux it together
The issue was that sound was for a 0.0XX sec longer than the video

**Comment by galactic76** [comment]
Who can tell me where I can make a request for a developing this programm?

The thing is that itwill be extremely usefull if the program make a separate srt file in the same try taht we remux mp4 to ts., cause i need to find englsh subtitles in opensub org and then translate it with translatesubtitles.com or with subtitle edit. And I wonder why you do not add to thi programm google translate of the subtitles in any requested language and mux it together. it will be superhelpfull :)

**Comment by jcdr428** [comment]
Hi @galactic76 , I close the issue.
You can make a feature request by opening a separate issue.
