### ISSUE TITLE
When creating the BR folder structure (both Blu-ray folder and Blu-ray ISO), the BACKUP/JAR folder is missing

### ISSUE THREAD

**Issue by RonerCodes** [justdan96/tsMuxer#637]
I've used this program for many years and I've noticed some players don't care if the /BDMV/BACKUP/JAR folder is missing, but on my current Sony BR player, it will not play the disc if it is missing that JAR folder.  The only obvious work-around is using the blu-ray folder output option and manually adding the folder later.  Thanks!

**Comment by jcdr428** [comment]
@RonerCodes Blu-Ray specs:
![image](https://user-images.githubusercontent.com/56721609/192059625-ebf5f7f8-70d7-4175-a560-e93372fc6272.png)

Anyway, I have added the optional BACKUP/JAR directory.

**Comment by RonerCodes** [comment]
Thank you @jcdr428 !   Yeah -- even earlier versions of PowerDVD did not play the disc without that specific folder existing.  Later versions are fine without it.
