### ISSUE TITLE
problem remixing UHD BD DV - black screen instead film

### ISSUE THREAD

**Issue by cob66** [justdan96/tsMuxer#642]
Nightly build from 2022-10-22-03-25-47 issue:
Tried remixing UHD DV BD structure (Bumblebee 2018). Process ended with success, but only black screen on Chinoppo.
This same remux on Nightly build from 2022-09-25-03-42-04 without problem :)
I haven't tested the releases 2022-10-18/19

**Comment by jcdr428** [comment]
@cob66 is it working with 2022-10-18 or2022-10-19 release ?

**Comment by jcdr428** [comment]
@cob66 can you please test 10-18 and 10-19 releases, or provide sample.
The commits since 09-25 should not have modified hevc muxing.

**Comment by cob66** [comment]
Something strange happened. Today I remuxed several times with the last version of tsmuxer  and each time with complete success. I don't understand, and unfortunately I successfully deleted that broken remux. I cannot repeat the problem. Sorry for the confusion.

**Comment by jcdr428** [comment]
@cob66 no worries, I close and if there is still an issue you can request to repoen.
