### ISSUE TITLE
Multiplexed stream in UHD quality in UHD is lighter than the original one

### ISSUE THREAD

**Issue by sfuma888** [justdan96/tsMuxer#645]
I converted blu-ray m2ts files to m2ts using the latest nightly build of tsmuxer dated 24-10-24-03-55-50 2022. the original disc is slightly darker. Working version w64-nightly-2020-09-25 --02-25-44, converts well.

**Comment by jcdr428** [comment]
@sfuma888 is the muxed m2ts duration shorter than the original m2ts duration (i e. the video is cut ) ?

**Comment by sfuma888** [comment]
> @sfuma888 is the muxed m2ts duration shorter than the original m2ts duration (i e. the video is cut ) ?

No. The whole movie.

**Comment by jcdr428** [comment]
@sfuma888 can I please have a link to download the input.

**Comment by sfuma888** [comment]
No. I am converting UHD Blu-ray discs from my home collection, removing unnecessary audio tracks and subtitles.

**Comment by jcdr428** [comment]
Then it will be difficult to see where the issue comes from...

**Comment by sfuma888** [comment]
I have tested almost all releases and I liked the nightly release the most-2020-01-01 --01-10-57. Recent releases suffer from low contrast and unsaturated picture color.

**Comment by jcdr428** [comment]
@sfuma888 the only commit pushed for next 03-Jan-20 release (https://github.com/justdan96/tsMuxer/commit/fa9962276f9066f0caa714432a4c4dca476e96a1) is very minor and does not affect colors. Are you certain that 2020-01-01 is the latest unaffected release ?

**Comment by jcdr428** [comment]
Closing. Can be reopened upon request.
