### ISSUE TITLE
Demux error code -2

### ISSUE THREAD

**Issue by kdantas** [justdan96/tsMuxer#647]
Hi, could someone give a solution to the problem below?

![TSMuxer Error](https://user-images.githubusercontent.com/19543277/198860988-38db94dd-09bc-47c9-8b65-e745d085a0b2.JPG)

**Comment by jcdr428** [comment]
@kdantas version 2.6.12 is obsolete. Please use the [latest release](https://github.com/justdan96/tsMuxer/releases).
