### ISSUE TITLE
Demuxing HEVC stream from MKV results in truncated output

### ISSUE THREAD

**Issue by FlaTechNole21** [justdan96/tsMuxer#649]
Here are results from a demux I recently did with three different release versions (latest, first with issue, last without issue):

**Nightly build from 2022-10-24-03-55-50**:
tsMuxeR version git-1d46cb6. github.com/justdan96/tsMuxer
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
B-pyramid level 1 detected. Shift DTS to 2 frames
**Processed 157426 video frames**
Flushing write buffer
Demux complete.
Demuxing time: 20 sec

**Nightly build from 2022-05-25-03-00-55**:
tsMuxeR version git-748f442. github.com/justdan96/tsMuxer
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
B-pyramid level 1 detected. Shift DTS to 2 frames
**Processed 157426 video frames**
Flushing write buffer
Demux complete.
Demuxing time: 20 sec

**Nightly build from 2022-05-16-02-41-35**:
tsMuxeR version git-24ae935. github.com/justdan96/tsMuxer
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
B-pyramid level 1 detected. Shift DTS to 2 frames
**Processed 157445 video frames**
Flushing write buffer
Demux complete.
Demuxing time: 20 sec

157445 frames is correct and what ffmpeg and MediaInfo report.

**Comment by jcdr428** [comment]
@FlaTechNole21 Please try tomorrow's release, thanks.

**Comment by FlaTechNole21** [comment]
Tested the W64 version and it no longer truncates, thanks!
