### ISSUE TITLE
Small UI issues

### ISSUE THREAD

**Issue by FRtranslator** [justdan96/tsMuxer#650]
Some text in French is truncated:

On Mac, Start muxing button is too small, on Windows it's OK.
![Mac](https://user-images.githubusercontent.com/27890322/200419980-abd387a9-57e6-447d-8180-ee648a961f28.png)
![Windows](https://user-images.githubusercontent.com/27890322/200420023-b4a76cdd-abe1-4338-818d-9842e36e56e2.jpg)

The Track number and Language column headers are also truncated (Windows and Mac):
![List](https://user-images.githubusercontent.com/27890322/200420105-cfb09d90-3f64-4dbe-b2dc-00489c444871.jpg)

Can you adjust the size of these items (maybe it can automatically be done)?

**Comment by FRtranslator** [comment]
@jcdr428 Will do, thanks.

BTW, still in UI enhancements: in the About tab, the text is very small, it would be good to set a larger text size.
Also, but I'm note sure, the "tsmuxer" at the beginning is a link to the website? If yes, clicking on it doesn't open the browser, it does nothing.

![About](https://user-images.githubusercontent.com/27890322/200541933-b101fd39-07c0-476f-8268-f360032412c6.png)

**Comment by FRtranslator** [comment]
@jcdr428 Buttons are OK, thanks!
The column header didn't change.
The About text is still too small.

**Comment by jcdr428** [comment]
Ok, I've tried something else for the column headers: please try tomorrow.
I've increased size of "About" text from 8pt to 9pt.
The underlined blue "tsMuxer" is a reminiscence of the old tsMuxer, no hyperlink...

**Comment by FRtranslator** [comment]
That's better, thanks ;)
