### ISSUE TITLE
封装SUP字幕

### ISSUE THREAD

**Issue by wer767** [justdan96/tsMuxer#653]
封装SUP字幕放到大屏字幕边缘有锯齿，字体边缘不圆润。

Edit translate: When encapsulated SUP subtitles are placed on a large screen, the edges of the subtitles are jagged, and the font edges are not rounded.

**Comment by jcdr428** [comment]
@wer767 which OS (Linux, Windows, MacOS) ?

**Comment by wer767** [comment]
Windows
