### ISSUE TITLE
cant adding One film for muxing 

### ISSUE THREAD

**Issue by galactic76** [justdan96/tsMuxer#655]
I see this before, but never write - now this is happens again - film She said DV MP4 form DVSUX cant adding

Just white space, and thats all :(

**Comment by jcdr428** [comment]
@galactic76 audio is EAC3 Atmos, or is it AC3 ?

**Comment by jcdr428** [comment]
Message in tsMuxer CLI is "Error: MP4/MOV error: invalid stts index for SRT track #5 at position 76333101".
I have not fond the reason for this error yet.

**Comment by galactic76** [comment]
is there any chance to remove that subtitles to open that file and remux it to TS?
Any other prog?

**Comment by galactic76** [comment]
Guys, can anyone tells me any other program to separate video and audio from she said

**Comment by jcdr428** [comment]
@galactic76 you can use ffmpeg.

**Comment by galactic76** [comment]
is ffmpeg have any GUI like tsmuxerGUI?

**Comment by galactic76** [comment]
thanks! i use clever ffmpeg gui separately for audio and video and it works!

**Comment by jcdr428** [comment]
@galactic76 please try tomorrow's release.
