### ISSUE TITLE
Detecting hevc stream has a bug

### ISSUE THREAD

**Issue by chbtime** [justdan96/tsMuxer#656]
Here is a sample,
https://1drv.ms/v/s!AhxDVD5Lr_39gQdrgpVazQK4r5VM?e=hNkt8m

tsmuxer can't decect hevc video stream.

When vod_common.h
const static int DETECT_STREAM_BUFFER_SIZE = 1024 * 1024 * 64; modified to 1024 * 1024 * 70, it will be fine.

**Comment by jcdr428** [comment]
@chbtime please check tomorrow's release.
