### ISSUE TITLE
E-AC3 out of sync

### ISSUE THREAD

**Issue by Gactnvl** [justdan96/tsMuxer#659]
For 4k bluray such as Thor 1 to 4 or latest kingsman’ i am getting an out of sync for the french Track While the english track in Atmos is in sync 
I have tried with the latest night build 
I am using tsmuxer to delete unecessary track or subtitle and reorder the french track on top of the english one - i am not downconverting track
Older 4k doesnt have such delay - star wars for exemple …
Anything i am doing wrong ,?

**Comment by jcdr428** [comment]
@Gactnvl please try tomorrow's release and report, thanks.

**Comment by Gactnvl** [comment]
Good morning It seems working fine nowI ve tested quickly on one movie at the beginning of it and it seems in sync nowI will do further test later on on all the recent ones for which I detected the issue and in I will report backThank you so much for such a quick responseEnvoyé à partir de l'app mail mobile sur 01/01/2023 le 20:36, jcdr428 écrivit:
                
            
            
                
                    De: "jcdr428" ***@***.***>Date: 1 janvier 2023à: "justdan96/tsMuxer" ***@***.***>Cc: "Gactnvl" ***@***.***>,"Mention" ***@***.***>Objet: Re: [justdan96/tsMuxer] E-AC3 out of sync (Issue #659)
                
                
@Gactnvl please try tomorrow's release and report, thanks.
