### ISSUE TITLE
Blu-ray ISO Audio Problems To Be Fixed-A Bug

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#660]
Hello would you like to fix Blu-ray audio issues to be fixed so they can be played on my Sony Blu-ray disc player? It only plays Dolby digital an DTS audio standards. Thank you.

**Comment by jcdr428** [comment]
@donnafaye0323 can you please clarify what is the bug reported ? Which audio codec does not play in your Sony player ?

**Comment by jcdr428** [comment]
@donnafaye0323 a Blu-ray player can play AC3, EAC3 and TrueHD (with legacy AC3), DTS, LPCM but is not supposed to play AAC.
