### ISSUE TITLE
Insert SEI and VUI data if absent

### ISSUE THREAD

**Issue by Nemesh64** [justdan96/tsMuxer#661]
This option was set to default (in previous versions) to: Do not change SEI and VUI data
However, I noticed recently that as of 12-25-2022 the option has been set back to: Insert SEI and VUI data if absent
As I use TsMuxer only for Blu-Ray muxing, I always set this to: Do not change SEI and VUI data.
Can this be set again to default when TsMuxer starts?
Or that we can make a choice with option to set as default?
With regards,

Nemesh

**Comment by jcdr428** [comment]
@Nemesh64 AddSEI and AddSPS have been moved to ini settings, please try tomorrow's version.

**Comment by Nemesh64** [comment]
Many, many thanks JCDR that you grant my request.
Will try it a.s.a.p.
Have first some 'domestic jobs' to do overhere.
Otherwise 'The Big Chief' get angry.

**Comment by Nemesh64** [comment]
Had visitors yesterday evening, hence the late respons.
The new version works fine.
This topic can be closed
