### ISSUE TITLE
"Insert SEI & VUI data" and "Continually insert SPS/PPS"

### ISSUE THREAD

**Issue by kirscheee** [justdan96/tsMuxer#666]
"Insert SEI & VUI data"  and "Continually insert SPS/PPS"

Both of these options

should be turned off at default mode?

because it's not useful in the vast majority of cases

I am so sorry to mention this

or should put the disable mode be built into the software?

**Comment by Nemesh64** [comment]
I also openend a topic regarding this.
So I support your request.
When starting TsMuxer, both should be turned off.

**Comment by kirscheee** [comment]
> I also openend a topic regarding this. So I support your request. When starting TsMuxer, both should be turned off.

Thank you for your support, dude

**Comment by jcdr428** [comment]
@kirscheee AddSEI and AddSPS have been moved to ini settings, please try tomorrow's version.
