### ISSUE TITLE
another bug while remuxing - MP4/MOV error: Invalid H.264/AVC frame at position 6561988608

### ISSUE THREAD

**Issue by galactic76** [justdan96/tsMuxer#668]
Film Coast DV MP4 DVSUX -  bug while remuxing - MP4/MOV error: Invalid H.264/AVC frame at position 6561988608

**Comment by galactic76** [comment]
UPD
1. Get video and audio separately, combine and it works fine now

**Comment by ValZapod** [comment]
> UPD
> 
> 1. Get video and audio separately, combine and it works fine now

So there is no bug? Or you mean extracting first works?

**Comment by galactic76** [comment]
yes, only extracting first work.
remux to ts ending with error

**Comment by jcdr428** [comment]
@galactic76 Film Coast DV : isn't that movie HEVC Dolby Vision ?

**Comment by ValZapod** [comment]
> @galactic76 Film Coast DV : isn't that movie HEVC Dolby Vision ?

It is hevc, yes. Coast.2021.2160p.WEB-DL.DD5.1.DV.MP4.x265-DVSUX

**Comment by ValZapod** [comment]
Tested it, it works: https://github.com/justdan96/tsMuxer/actions/runs/4524281203

Why does mpv says [ffmpeg] pgssub: Bitmap dimensions (1920x72) invalid.

when you add subtitles? It warns with .sup files, but if you rename to .srt it opens good, no warning...

**Comment by jcdr428** [comment]
@ValZapod Do you refer to the Coast DV movie ?
IMO the ffmpeg error means that the video width is below the subtitle width.

**Comment by ValZapod** [comment]
Oops, no, wrong issue.

**Comment by jcdr428** [comment]
@galactic76 tsMuxer muxes `Coast.2021.2160p...DVSUX.mp4` without problems. Can you please clarify the issue ?

**Comment by galactic76** [comment]
> @galactic76 Film Coast DV : isn't that movie HEVC Dolby Vision ?

I already answer before 

The file name is Coast.2021.2160p.WEB-DL.DD5.1.DV.MP4.x265-DVSUX file

**Comment by ValZapod** [comment]
I suppose the problem is why it says 'H.264/AVC" if it HEVC.

**Comment by jcdr428** [comment]
Yes, 1. the error says H.264/AVC, and 2. I don't have any issues muxing Coast DV x265 DVSUX. So nothing I can do.

**Comment by galactic76** [comment]
speaking of subtitles - Im asking for a long time ago to add a feature "extcact subtitle to a separate file" sululatiously when main muxing, When you can add this feature? Thanks,

**Comment by jcdr428** [comment]
@galactic76 please dont mix the issues - your connent should go to the related issue.

 You'll have to wait for somebody interested to work on this.

**Comment by jcdr428** [comment]
@galactic76 please dont mix the issues - your comment should be made on the related issue.

 You'll have to wait for somebody interested to work on this.

**Comment by galactic76** [comment]
I already delete it.

You can find it by name 

Coast.2021.2160p.WEB-DL.DD5.1.DV.MP4.x265-DVSUX

**Comment by jcdr428** [comment]
@galactic76 the issue is unclear, you cannot have a "Invalid H.264/AVC" message with an HEVC stream. Unless you can provide the .meta file and the screenshot of the error, the issue cannot be investigated.
