### ISSUE TITLE
Problems With M2TS Video Files Copied on Sony Blu-Ray Recorder

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#671]
I have a Sony VBD-MA1 Blu-ray recorder and it says "No Recording videos Found on my SD Card.

Here is some information: This Blu-Ray recorder only supports AVCHD video files and MPEG-2 video copying files-NO MPEG-4 video formats. "You can copy HD (High Definition) videos taken in AVCHD format with various cameras to a Blu-ray Disc or DVD media. HD (High Definition) videos can be copied in HD (HighDefinition) image quality." That's what this manual says.
 Can you fix this bug about converting mpeg-4 files to avchd.m2ts? Thank you!

**Comment by jcdr428** [comment]
Closing, can be reopened upon request.
