### ISSUE TITLE
AAC Codec Not Standard For BD Disks

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#672]
I made a Bl-ray ISO, but it says "Warning! AAC codec is not standard for BD disks, the disk will not play in a Sony Blu-ray player." It  only supports **Dolby Digital, DTS and LPCM audio.** Would you help us fix this bug, and add more supported audio codecs?
Also, would you add an audio conversion tool as well?  Thank you for all your help:

Here's some information that can help us learn more;
https://www.sony.com/electronics/support/home-video-blu-ray-disc-players-recorders/ubp-x800/articles/00029663

**Comment by jcdr428** [comment]
@donnafaye0323 can you please clarify what is the bug reported ?
AAC audio is not supported by Blu-ray players, as shown in your Sony link.

**Comment by jcdr428** [comment]
@donnafaye0323 can we close the issue ?

**Comment by jcdr428** [comment]
Closing, can be reopened upon request.
