### ISSUE TITLE
Mono truehd+ac3 is extracted correct, but does not allow proper remux in m2ts

### ISSUE THREAD

**Issue by ValZapod** [justdan96/tsMuxer#674]
So when you have stereo truehd when you extract ac3 and thd tracks with ffmpeg their sizes together add up to interleave stream extracted by txmuxer, but not with mono.

See: https://drive.google.com/file/d/10gEr7OQCRmApDPE-u_wLpMQ1ihFjay9w/view

3rd audio track is mono and when extracted is bigger than ac3 separate from thd extracted with ffmpeg and does not allow proper remuxing to m2ts (on extract it will be a different file).

**Comment by ValZapod** [comment]
I also found the thdmerge.exe wfanfva.thd wfanfva.ac3 cancfafcva.thd

that produces the same file as ​https://easyupload.io/dzt1pl here: http://rationalqm.us/board/viewtopic.php?f=16&p=15406#p15406 (http://rationalqm.us/misc/thdmerge.zip)

So maybe no bug in interleave code itself.

**Comment by jcdr428** [comment]
@ValZapod I have checked the mono TrueHD+AC3 (track 0x1102) in the file on your drive, it is correctly demuxed.

**Comment by ValZapod** [comment]
>it is correctly demuxed

It is, try remuxing it to m2ts, it produces bug file that will then demux wrong. Next remux will break it.

**Comment by jcdr428** [comment]
@ValZapod so the remux is in cause. Although I suspect the problem is with the stream, not with tsMuxer.

**Comment by ValZapod** [comment]
> @ValZapod so the remux is in cause. Although I suspect the problem is with the stream, not with tsMuxer.

I still do not get it why the size of thd stream + ac3 stream is smaller than thd/ac3 interleave. That is not the case in stereo thd. (Extracted thd and ac3 with ffmpeg.)

**Comment by ValZapod** [comment]
> @ValZapod so the remux is in cause. Although I suspect the problem is with the stream, not with tsMuxer.

You can verify that by checking all the frames are there. Right?

**Comment by jcdr428** [comment]
@ValZapod 
tsMuxer demuxes 00001.track_4354.ac3+thd, size 98,948,444 bytes.
ffmpeg.exe -i 00001.m2ts -map 0:5 -acodec copy output.thd => size 81,482,972 bytes.
ffmpeg.exe -i 00001.m2ts -map 0:6 -acodec copy output.ac3 => size 17,465,472 bytes.
81,482,972 + 17,465,472 = 98,948,444.

I can remux / redemux 00001.track_4354.ac3+thd file in tsMuxer, it still gives the same file with CRC32=A84B61A2.
So I don't understand what is the issue ?

**Comment by ValZapod** [comment]
>output.ac3 => size 17,465,472 bytes.

No what I get. For ac3 I get 14 417 920 bytes with ffmpeg.

See: https://trac.ffmpeg.org/ticket/667#comment:21

**Comment by jcdr428** [comment]
@ValZapod I've tries with the latest x64 build on https://github.com/BtbN/FFmpeg-Builds/releases and ffmpeg works as it should.
Anyway the problem is linked to ffmpeg and not tsMuxer: as advised, I have no problems demuxing / remuxing the ac3+thd with tsMuxer.

**Comment by ValZapod** [comment]
I can remux thd+ac3 or ac3 only with TsMuxer. How to demux only THD? I understand that you do not want to create invalid for Blu-ray files...

I will recheck everything with PTS fix https://github.com/justdan96/tsMuxer/pull/686 in two hours.

**Comment by ValZapod** [comment]
Yep. I also got 17 465 472 bytes. I also still had old files, and it was still 17 465 472 bytes. Dunno how I made the mistake.

And the problem does not happen with multiple demuxes, the thd+ac3 files are bitperfect. Sorry fot the noise.
