### ISSUE TITLE
File extension for demuxed core audio stream is incorrect

### ISSUE THREAD

**Issue by GrzeWier** [justdan96/tsMuxer#676]
Hi
When demuxing the core audio stream from eac3/DD+ source - the resulting file is given **ec3** extension.
This is incorrect.
The core stream is meant to provide compatibility for old devices that are unable to utilize the full 'enchanced' track.
Core stream is a regular Dolby Digital and should be given **ac3** extension.

**Comment by jcdr428** [comment]
@GrzeWier please try tomorrow's release. When the stream is interleaved ac3/ec3, the demuxed file will have extension ac3+ec3.

**Comment by jcdr428** [comment]
Closing, can be reopened upon request.
