### ISSUE TITLE
Incorrect PTS value

### ISSUE THREAD

**Issue by moveman** [justdan96/tsMuxer#677]
The video ES to mux has frame rate of 30000/1001 fps. 
The PTS difference between two consecutive frames (in presentation order) should be 3003 tick in 90k Hz. 
However, we found that one 3002 tick PTS difference in the muxed TS. 

Please find the file to reproduce this issue:
https://drive.google.com/drive/folders/11TfUSrX-TOs-dLJP0duDKAJD5azy2Enb?usp=sharing

To generate the muxed TS, run:
`tsMuxeR 1.meta 1.ts`

In 1.ts, strange PTS diff with 3002 is found at frame 8334 (0 base):
```
FrammeIdx: 8333	byte_pos: 424428 PTS: 25149899
FrammeIdx: 8334	byte_pos: 424721 PTS: 25152901
PTS_diff: 3002
```

**Comment by jcdr428** [comment]
@moveman this could be investigated but is it worth it ? It is a difference of 11 microseconds.

**Comment by moveman** [comment]
Hi @jcdr428, this is very important to us, we need the PTS to be exact such that PTS of of the IDR frame of each stream in MBTS could be aligned. This is essential in OTT application.

**Comment by moveman** [comment]
Hi @jcdr428, we have written a sample program to illustrate the precision problem:
```
// Example program
#include <iostream>
#include <string>

const unsigned PCR_FREQUENCY = 90000;
const static int64_t INTERNAL_PTS_FREQ = 1000000000;
const static double INT_FREQ_TO_TS_FREQ = INTERNAL_PTS_FREQ / (double)PCR_FREQUENCY;

int main()
{
  double fps = 60000 / (float)1001 / 2; // time_scale / (float)num_units_in_tick / 2
  int64_t m_pcrIncPerFrame = (int64_t)((double)INTERNAL_PTS_FREQ / fps);
  
  int64_t prevDts90k = 0;
  int64_t m_curDts = 0;
  for(int i = 0; i < 100000000; i++) {
    auto dts90k = (int64_t)(m_curDts / INT_FREQ_TO_TS_FREQ + 0.5);
    m_curDts += m_pcrIncPerFrame;
    if (dts90k - prevDts90k != 3003) {
      std::cout << "idx: " << i << " DTS diff: " << (dts90k - prevDts90k) << "\n";
    }
    prevDts90k = dts90k;
  }
}
```
Console output:
```
idx: 0 DTS diff: 0
idx: 8334 DTS diff: 3002
idx: 25001 DTS diff: 3002
idx: 41667 DTS diff: 3002
......
There is precision error on m_pcrIncPerFrame. We have tried changing INTERNAL_PTS_FREQ from 1000000000 to 27000000, INTERNAL_PTS_FREQ / fps will not have remainder and m_pcrIncPerFrame will be precise, DTS difference will then always be 3003. Do you think changing INTERNAL_PTS_FREQ to 27000000 is a valid fix? Thanks.

**Comment by ValZapod** [comment]
>The video ES to mux has frame rate of 30000/1001 fps.

No, it does not, it has no fps inside annex b signal.

>We have tried changing INTERNAL_PTS_FREQ from 1000000000 to 27000000

Can you sumbit a patch? Such errors are of course bad! For now you can use ffmpeg.

**Comment by jcdr428** [comment]
> Do you think changing INTERNAL_PTS_FREQ to 27000000 is a valid fix?
All tsMuxer code is based on nanoseconds (hence the 1,000,000,000), I think there would be many more changes to be done.
The ideal would be to totally give up the "double" FPS to use a numerator denominator tuple.

**Comment by moveman** [comment]
Hi @jcdr428, @ValZapod, I created a Pull Request, please take a look. We are currently using this patch happily.

**Comment by ValZapod** [comment]
BTW, FYI you can just use:

ffmpeg -i before.ts -vf vfrdet -f null -


[Parsed_vfrdet_0 @ 000001f8c39752c0] VFR:0.000109 (2/18417) min: 3002 max: 3003 avg: 3002

ffmpeg -i after.ts -vf vfrdet -f null -


[Parsed_vfrdet_0 @ 0000024222007c80] VFR:0.000000 (0/18419)
