### ISSUE TITLE
latest version of tsmuxer have problems on vlc.

### ISSUE THREAD

**Issue by Shay2242** [justdan96/tsMuxer#678]
i downloaded the portable newest version of tsmuxer (Nightly build from 2023-02-03-02-25-21) and when try to mux mkv to .m2ts it give me this info:
tsMuxeR version git-d187dfd. github.com/justdan96/tsMuxer
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
B-pyramid level 1 detected. Shift DTS to 2 frames
Decoding E-AC3 (DD+) stream (track 2): Bitrate: 768Kbps (core 0Kbps) Sample Rate: 48KHz Channels: 5.1

And after its finishing i try to open the file with vlc and i hear the sound but i don't see any video, then i tried to use an older version (Nightly build from 2023-01-02-02-15-09) and after it finished and i try to open it with VLC everything works just fine.
Btw first time here, Thanks for creating such a tool it Helps me Alot!.
:

**Comment by jcdr428** [comment]
@Shay2242 can you please identify the latest working version.

**Comment by Shay2242** [comment]
The latest working version is :
Nightly build from 2023-01-02-02-15-09
every nightly build after this one isn't working.

**Comment by jcdr428** [comment]
@Shay2242 please try tomorrow's release, thanks.

**Comment by Shay2242** [comment]
i Will, Thank you!.

**Comment by Shay2242** [comment]
Fixed, Thank you!.
