### ISSUE TITLE
Request: Dark Mode

### ISSUE THREAD

**Issue by Nemesh64** [justdan96/tsMuxer#679]
Hello JCDR428,

Is it possible to give TsMuxer a dark mode?
Or that we can choose between dark or white mode?
My desktop (Windows 10) is set to black, and the white color from TsMuxer is very bright against this black desktop.
With regards,

Nemesh

**Comment by jcdr428** [comment]
@Nemesh64 duplicate with issue #537 => closing.
Personally I don't know how to do this.
