### ISSUE TITLE
Subtitle offset feature not working

### ISSUE THREAD

**Issue by seplant** [justdan96/tsMuxer#681]
Hello.  I used tsMuxeR version 2.6.12 to add subtitles to a 1080P video, but I wanted to adjust the vertical position of the subtitles to be on top of the 2.35:1 video image rather than under the video within the bottom black bar.  However, no matter what value I enter into the "Vertical position: Bottom offset, pixels" section of the Subtitles tab, the subtitles in the video output from tsMuxeR do not change where they are positioned.

**Comment by jcdr428** [comment]
@seplant it is not working in the current release, or in 2.6.12 only ?

**Comment by seplant** [comment]
> @seplant it is not working in the current release, or in 2.6.12 only ?

That was the latest version I could find.

**Comment by jcdr428** [comment]
@seplant can you please test latest release https://github.com/justdan96/tsMuxer/releases/tag/nightly-2023-03-08-02-33-38 and report.
