### ISSUE TITLE
EAC3 muxing is not working correctly in newer versions

### ISSUE THREAD

**Issue by DreckSoft** [justdan96/tsMuxer#682]
This will be a longer issue. I try to include all the information needed.

Short version:
BD-Discs containing (only) EAC3 audio created with tsMuxeR 1.10.6 work, those with the current nightly do not.

Long version:
Prequel:
I'm trying to find a way, to create UHD BD with free tools. The idea was to create a BD in MultiAVCHD and then replace the streams with the 4k ones and fix everything in BDEdit. It kinda works but I do not get any audio on my hardware player (works in PowerDVD). So to do one step at a time I did go back to the 1080p files and create a properly working BD first.

I did the BD version in MultiAVCHD. The disc plays with sound in my player. However, I had issues with seeking (fast forward / jump to chapter). I don't know why as it worked with other files before using the same method. 
The I remuxed all the files with a recent version of tsMuxeR (MultiAVCHD uses 1.10.6). Now seeking works but there is no audio at all.
The audio tracks are 640kbit EAC3 files without AC3 core. Yes, I know that is not standard compliant but as you can see it works with an old version of tsMuxeR (if I mux the files manually and replace them also without seeking issues). 
I did several tests and created various discs with just tsMuxeR, so just one title, no menus.
H264 video stream 1920x1080
2 EAC3 640kbit audio tracks
2 subtitle tracks

1. Muxing with 1.10.6 as BD and burn on BD => works
2. Muxing with Nightly as BD and burn on BD => no audio
3. Muxing with Nightly as BD and burn on DVD => does not play at all
4. Muxing with Nightly as AVCHD and burn on BD => no audio
5. Muxing with Nightly as AVCHD and burn on DVD => works (this is strange)

I have no clue why (5) works. 

Seems I have a very picky player (Panasonic DP-UB824) but I don't have anything else to test. In PowerDVD it works.

2nd test
1st audio track is now AC3
1. Muxing with Nightly as BD and burn on BD => AC3 plays, no audio after switching to EAC3 and the player takes ages to react to any key presses after that
2. Muxing with 1.10.6 as BD and burn on BD => works (all tracks)

**Comment by jcdr428** [comment]
@DreckSoft 
Is 2.6.12 working ?
Is any release of tsMuxer open source working ?

**Comment by DreckSoft** [comment]
2.6.12 completely messes up EAC3:

`Network Optix tsMuxeR.  Version 2.6.12. www.networkoptix.com
Decoding H264 stream (track 1): Profile: High@4.0  Resolution: 1920:1080p  Frame rate: 24
H.264 muxing fps is not set. Get fps from stream. Value: 24
B-pyramid level 1 detected. Shift DTS to 2 frames
0.0% complete
H264 bitstream changed: insert nal unit delimiters
H264 bitstream changed: insert pict timing and buffering period SEI units
Decoding E-AC3 (DD+) stream (track 2): Bitrate: 640Kbps (core 0Kbps) Sample Rate: 48KHz Channels: 0
Decoding E-AC3 (DD+) stream (track 3): Bitrate: 1817211Kbps (core 1817199Kbps) Sample Rate: 0KHz Channels: 116.1
Decoding PGS stream (track 4):  Resolution: 1920:1080  Frame rate: 24
Decoding PGS stream (track 5):  Resolution: 1920:1080  Frame rate: 24
H264 bitstream changed: insert SPS/PPS units
91.1% complete
Processed 75199 video frames
100.0% complete
Flushing write buffer
Creating Blu-ray stream info and seek index
Creating Blu-ray playlist
Mux successful complete
Muxing time: 40 sec`

![BDEdit](https://user-images.githubusercontent.com/68750712/222378160-db2040dc-02a1-4010-951e-de89f9b4a121.png)

**Comment by DreckSoft** [comment]
The difference must be in the M2TS, not the MPLS or CLPI. I edited the two files in BDEdit changing the audio to DD, save and change it back to DD+. The old mux (1.10.6) still works, the newer still won't. I then copied the M2TS from the old version into the directory of the newer version, having all files except the M2TS from the newer version and it still works. It breaks seeking cause the CLPI won't match the M2TS but the audio is there. So the old version must use a different descriptor, stream id or something similar than the newer version. The file size of the M2TS also differs by about 40MB using a 100% identical input.

**Comment by DreckSoft** [comment]
I just compiled a patched version which sets the format_identifier to AC-3. This does not work either. However, I have issues compiling an unmodified version of tsMuxeR in Windows. 

I need to add `#include <cstring>` to lpcmStreamReader.cpp but that seems to lead to some strange issue that some descriptors are not set correctly. See:
https://github.com/justdan96/tsMuxer/issues/675

[Patch.txt](https://github.com/justdan96/tsMuxer/files/10870462/Patch.txt)

**Comment by DreckSoft** [comment]
The main difference between the two versions seems to be the ID. It is 1 (0x1) in the old version and 0 (0x0) in the new version. Does anyone know where this ID is set? I couldn't find it with a shot search.

**Comment by jcdr428** [comment]
The ID is set in tsMuxer.cpp lines 230-242 and 264.
The ID for pure EAC3 might need to be different for each AVCHD, TS, M2TS, Bluray V2 and Bluray V3.

**Comment by DreckSoft** [comment]
Thanks but I did not mean the codec ID, I found those.

`General
Count                                    : 333
Count of stream of this kind             : 1
Kind of stream                           : General
Kind of stream                           : General
Stream identifier                        : 0
Inform                                   : BDAV: 2.87 GiB, 52 min 13 s
ID                                       : 0
ID                                       : 0 (0x0)
`

That's from MediaInfo. I want to change the ID 0 (0x0) to 1 (0x1) like the old tsMuxeR. This is likely not compliant but I just want to get it working (again) even if it is not up to specs.

**Comment by jcdr428** [comment]
Ok, so it might be the PAT transport_stream_id, set to 0 at line 1141 of tsMuxer.cpp
H.222 2.4.4.6 says "_Its value is defined by the user_".
Bluray specs say "_This field has no meaning in the HDMV TS and may take any value_".
Its value is set to 0 in all Blu-rays I've checked. But as you say, a Blu-ray with pure EAC3 does not exist...

**Comment by DreckSoft** [comment]
Thanks. First test was also unsuccessful though. Now I'll try to combine the patches to make the TS look as much as possible like 1.10.6. But I fear that the newer versions have some fundamental changes to the TS structure.

**Comment by DreckSoft** [comment]
I now patched everything to look as close to 1.10.6 as possible but still no luck. I'm out of ideas.

**Comment by jcdr428** [comment]
@DreckSoft what is the difference you are seeking, is it EAC3 AVCHD mux 1.10.6 vs latest ?

**Comment by DreckSoft** [comment]
Yes. 
It works in my player when I mux with 1.10.6 but won't with any open source version. As I'm also trying to create 4k discs I need a newer version that works.

**Comment by jcdr428** [comment]
@DreckSoft you probably just need to trick the player by changing the EAC3 descriptor back to an AC-3 descriptor. 
Try commenting out line 71 of ac3streamreader.cpp (`// if (isAC3()`)

**Comment by DreckSoft** [comment]
Thanks but I already tried that too. It does not make a difference (just re-tested). 

I saw several subtypes defined in AC3StreamReader::writePESExtension. I'm not sure if those are correct. First 0x72 should be E-AC3, then the same magic number is TrueHD. But I don't have any clue what exactly is set there. 

Would it help if I provide two example BD structures from old and new tsMuxeR?

**Comment by jcdr428** [comment]
Yes please provide, i'll have a look.

**Comment by DreckSoft** [comment]
Hier:
https://anonfiles.com/acZ4R2c4z1/multiAVCHD_Out_7z

**Comment by DreckSoft** [comment]
I just tried remuxing the 00000.m2ts using tsRemux: https://github.com/antiochus/tsremux
After that, EAC3 playback works (again). 
I also did adjust the packet size in the clpi with BDEdit.

Settings:
Keep all streams
Output Format: M2TS
Bypass Audio Alignment: Off
Use async I/O: On

I would really like get rid of the two extra steps. And it will not work with UHD/HEVC video cause tsRemux won't recognize those.

**Comment by DreckSoft** [comment]
tsRemux seems to do it differently from old tsMuxeR versions. It sets E-AC3 codec ID to 129 instead of 131. However, changing this in recent tsMuxeR versions won't help either.

**Comment by jcdr428** [comment]
> Here it is: https://anonfiles.com/acZ4R2c4z1/multiAVCHD_Out_7z

You did not use the latest release to output the Example_TSMuxerNightly. As advised four days ago, I pushed a change to keep the AC-3 descriptor instead of the EAC3 one in Bluray/AVCHD mode.

**Comment by DreckSoft** [comment]
I can do a new mux with the latest version but the behavior in my player is exactly the same. I tried it with your change. It has to do something the structure. I tried a ton of things and nothing works except the old tsMuxer and tsRemux - both can't handle 4k which is what I'll need in the second step.

**Comment by DreckSoft** [comment]
Here's a new mux:
https://anonfiles.com/l31dL2d8z2/multiAVCHD_Out_7z

This time I also included the mux from MultiAVCHD including the META file it uses.

**Comment by DreckSoft** [comment]
And here with a remux of the Nightly tsMuxeR with tsRemux:
https://anonfiles.com/k6B8L1d1z1/multiAVCHD_Out_7z

**Comment by jcdr428** [comment]
@DreckSoft the difference seems to be that tsRemux puts the 0x81 stream_type descriptor for EAC3, whereas tsMuxer puts 0x84.
Bluray specs are clear:
![image](https://user-images.githubusercontent.com/56721609/224549088-75db7cea-1103-4d4c-beda-b2bbed8ed1ad.png)
AVCHD specs might be different, as AVCHD is supposed to know AC-3 only.
Please try changing StreamType::AUDIO_EAC3 with StreamType::AUDIO_AC3 on line 343 of tsMuxer.cpp (last release) to see whether this solves your issue.
If it does, I'll find a way to change the stream_type for AVCHD only.

**Comment by DreckSoft** [comment]
That does also not make any difference. 

Regarding to tsRemux: I don't think it is the descriptors. I also patched tsMuxeR to handle everything like AC3, so the muxing was AC3, the descriptors were AC3, the codec ID was AC3 - did not work. It has be something deeper inside how the stream is created. Maybe a different interleaving, maybe some meta-data MediaInfo does not display. Maybe something in the support tables (PAT,PMT,PCR, ...)

**Comment by DreckSoft** [comment]
Please ignore the tsRemux file for now. I seem to have issues with that two. I'll need to recheck and maybe create a new file.

**Comment by ValZapod** [comment]
>The file size of the M2TS also differs by about 40MB using a 100% identical input.

And why is that? Use java app: https://github.com/EricBerendsen/dvbinspector

**Comment by ValZapod** [comment]
>Muxing with Nightly as AVCHD and burn on DVD => works (this is strange)

Please provide.

>Muxing with 1.10.6 as BD and burn on BD => works

Also please provide.

**Comment by DreckSoft** [comment]
Here's a new set including AVCHD mux from the new version:
https://anonfiles.com/waO0Z5d5zd/multiAVCHD_Out_7z

Currently I'm unable to reproduce the working result(s) from tsRemux. So please ingore all tsRemux files from the previous uploads. I'm not 100% sure I copied the correct file.

**Comment by ValZapod** [comment]
Yep, in new file there is Delay relative to video: 116 ms, does not look great, in fact it should be minus x ms to compensate for encoder delay in EAC3 (usually 256 samples of audio in EAC3 that is just silence and was supposed to be removed, but only correctly signalled in mp4, eac3's reference container).

What is also funny that even though there is a Delay relative to video, -c copy raw.eac3 

gives you same bitperfect EAC3 file. Why is that? Is not TS supposed to be cut perfectly?

So, I would imagine the problem is wrong (and illogical, since this increases delay, not removes it) PTS for audio.

**Comment by ValZapod** [comment]
>Also the only working version is 0.0.21.2

Did not you say it is 1.10.6?

>seems to only produce a usable output if there is at least one PGS stream present

So PGS subtitles fix timestamps?

**Comment by DreckSoft** [comment]
tsRemux 0.21.2 NOT tsMuxeR. I just wanted to provide a second set of working files.

**Comment by ValZapod** [comment]
I am still shocked pure EAC3 without AC3 inside can even work with Blu-ray players.

**Comment by DreckSoft** [comment]
Why shouldn't it? AC3 inside EAC3 was just a fallback for the very beginning. If the equipment was EAC3 capable the AC3 part was never used. And most newer players also offer USB or network playing and those files usually have EAC3 ONLY.

**Comment by ValZapod** [comment]
>If the equipment was EAC3 capable the AC3 part was never used.

You are mistaken. AC3 track is not visable in Mediainfo, it is not a separate track that can be present on Blu-rays for TrueHD. No, AC3 is used get EAC3 sound.

**Comment by ValZapod** [comment]
Do ANY "EAC3 up to 16 ch." tagged files (0x84) play with your Blu-ray player? Can you hex edit the old MPEG-TS to have 0x84?

Also can you provide mediainfo of whatever mp4 or mkv you are using? I am interesting in delay relative to video.

**Comment by DreckSoft** [comment]
No, it's not a separate track but interleaved in EAC3 or TrueHD. However, the AC3 part is not used for decoding EAC3 and I also think not for TrueHD. That was DTS-HD that uses the core for decoding the HD part.

**Comment by ValZapod** [comment]
>No, it's not a separate track but interleaved in EAC3 or TrueHD

In both. And separate.

>However, the AC3 part is not used for decoding EAC3 and I also think not for TrueHD.

It is used in EAC3. See e.g., in Atmos the logic is also different, open source Atmos decoder to object ADM abd renderer: https://github.com/VoidXH/Cavern/issues/56#issuecomment-1374144269

and doom9: 
https://forum.doom9.org/showthread.php?p=1840635#post1840635

https://forum.doom9.org/showpost.php?p=1119297&postcount=11

**Comment by Hellboy00000** [comment]
> Blu-ray with pure EAC3 does not exist

First "Dolby Digital Plus" is EAC3 right?

I don't know much about this but "Puss in Boots: The Last Wish" Blu-ray have EAC3
https://www.blu-ray.com/movies/Puss-in-Boots-The-Last-Wish-Blu-ray/329494/

**Comment by ValZapod** [comment]
>First "Dolby Digital Plus" is EAC3 right?

yes.

>don't know much about this but "Puss in Boots: The Last Wish" Blu-ray have EAC3

Many Blu-rays have EAC3. They all do not have strmtyp: 0 though as used in pure EAC3.

**Comment by jcdr428** [comment]
@DreckSoft the problem might come from the transport_priority flag: it must be set to 1 for independent substreams.

**Comment by DreckSoft** [comment]
Has this changed between 1.10.6 and open source versions? Can you tell me where it's set? The I'll do a local patch and test.

**Comment by ValZapod** [comment]
>Would be interesting to know whether this is the case with all DD+ compatible players.

Modern players support Netflix. So of course it is logical it must support all types of EAC3.

>problem might come from the transport_priority flag: it must be set to 1 for independent substreams.

Yep. AC3 substream is independent. Dependent (sub)stream is only EAC3! See: https://forum.doom9.org/showpost.php?p=1119297&postcount=11

**Comment by jcdr428** [comment]
> So of course it is logical it must support all types of EAC3

What I mean is: will the player play the bluray disk if replacing the ac3 legacy independant substream with an eac3 independant substream (strmtyp 2) ?

**Comment by ValZapod** [comment]
>the player play the bluray disk if replacing the ac3 legacy independant substream

Well, reference panasonic does. Again, many Blu-rays do not even like unencrypted Blu-rays, do they not?

**Comment by DreckSoft** [comment]
Old LG players won't even play BD-R. They removed it on purpose with a firmware update. Newer ones could read them again and I think at least the UP970 could play EAC3 type 2.

**Comment by jcdr428** [comment]
@DreckSoft as stated above, problem most likely comes from the transport_priority flag.

**Comment by DreckSoft** [comment]
That does not seem to be easy to patch. I tried returning always true for AC3StreamReader::isPriorityData but that didn't work.

**Comment by DreckSoft** [comment]
The line already looked like that. I then removed "&& m_strmtyp != 1" and now it plays. I will do more tests to ensure I didn't mix up files or something like that.

**Comment by jcdr428** [comment]
> I then removed "&& m_strmtyp != 1" and now it plays.

Bizarre... Dependent substreams are not supposed to have transport_priority enabled.

**Comment by DreckSoft** [comment]
Maybe the stream is incorrectly recognized? 

Btw: I just muxed an UHD BD with working EAC3 so this works but removing the constraint could cause other issues.

**Comment by ValZapod** [comment]
>Dependent substreams are not supposed to have transport_priority enabled.

But then again EAC3 is always dependent substream on Blu-ray. So...

**Comment by jcdr428** [comment]
Excerpt from Blu-Ray spec: 
![image](https://user-images.githubusercontent.com/56721609/227591030-800695c1-b675-4e45-9c2c-cfec81928184.png)

But then as you say, this is for AC3+EAC3. So with full EAC3 this is 'undefined behavior': we would need to know how the Sony and LG players behave to implement the change.

**Comment by jcdr428** [comment]
@DreckSoft the only purpose of transport_priority = 1 is to show priority over other packets with the same PID having transport_priority = 0. So for me it does not really make sense to have all packets =1.
![image](https://user-images.githubusercontent.com/56721609/227596032-d551006b-b22c-44f7-bdc7-6f296db244bb.png)
I'll try to find some samples of TS with EAC3 from reputable sources.

**Comment by DreckSoft** [comment]
Maybe but I assume for audio decoding the player (or at least Panasonic) look for transport_priority = 1 audio frames first and then subsequently looking for the "non priority" frames. If there is none with transport_priority = 1 (as it is the case with pure EAC3) there will be no decoding. With AC3 also all frames would be transport_priority = 1. So that is consistent.

**Comment by ValZapod** [comment]
>If there is none with transport_priority = 1

Then it should play with 0, as spec says.

**Comment by DreckSoft** [comment]
Not with EAC3 where the EAC3 stream is dependent on the AC3 stream. First it need the AC3 part to decode and then "add" the EAC3 part. So there will always be a part of the audio stream with transport_priority = 1. transport_priority = 0 are just "add-on packets". 

I assume with DTS-HD the core has transport_priority = 1 and the HD part has transport_priority = 0?

**Comment by DreckSoft** [comment]
Even if the specs say something different, shouldn't we adapt to the real world scenarios? Like Linux emulating Windows Bugs (!) with ACPI tables so systems "just work"?

**Comment by jcdr428** [comment]
>I assume with DTS-HD the core has transport_priority = 1 and the HD part has transport_priority = 0?

Correct.
>shouldn't we adapt to the real world scenarios?

Indeed, and that's why it would be better to know how LG and Sony players behave to have the full picture.
I've checked secondary pure EAC3 audios in Blurays, and they use transport_priority  = 0.

**Comment by ValZapod** [comment]
Well, one layer EAC3 is not even supposed to be a supported scenario, so whatever we do to support it would be nice. Pull request?

**Comment by jcdr428** [comment]
>Pull request?

Ok. So to summarize we need for transport_priority:
Pure AC3 = 1
Pure EAC3 = 1 for primary audio, = 0 for secondary audio
Interleaved AC3 = 1 / EAC3 = 0
Interleaved AC3 = 1 / TrueHD = 0

**Comment by DreckSoft** [comment]
That sounds correct to me.

Some good news: I was able to inject the UHD muxing results into a MultiAVCHD created Blu-Ray. So we have the first working UHD BD created using (almost) free tools (BDEdit is Donationware). The guide will be released as soon as we have a working nightly build and maybe another change to BDEdit which makes things more easy.

**Comment by DreckSoft** [comment]
I think secondary audio can also be AC3 (or even any other supported format), so we would have 
Pure AC3 = 1 for primary audio, = 0 for secondary audio
and several other options for the other audio types. 

I'm not sure about the specs here. Maybe secondary audio always has transport_priority=0 and the needed stream for primary audio always transport_priority=1? With interleaved AC3/EAC3, AC3/TrueHD, DTS/DTS-HD I don't have a clue. 

For AC3/EAC3 I'd say AC3=1, EAC3=0 and for DTS/DTS-HD DTS=1 and DTS-HD=0 but that's just a guess based on logic.
For AC3/TrueHD I'm not sure. Both can be decoded independent (MKVToolnix stips the core and it still works). Maybe setting AC3=1 and TrueHD=0 will result in only AC3 played and TrueHD ignored?

For a quick solution I'd say remove "&& m_strmtyp != 1". I just muxed a file with an BD EAC3 track and it still worked. So this shouldn't break anything.

**Comment by DreckSoft** [comment]
It could be that I mixed up my tsMuxeR versions before and worked with one that has a few of my "test-patches" and therefore failed with m_strmtyp != 1. Just let me check check the official nightly build before we change more stuff.

**Comment by DreckSoft** [comment]
First a big SORRY. I did make a mistake yesterday. I checked out the newest version from git and found the line to be already as mentioned by @jcdr428 So I did not test this version but only mine without the strmtype. 

Good news: The nightly works! From my point of view we do not need to go further into the various options for transport priority (unless a new issue appears). 

Unless you want to investigate this further even it's working now, I would close this.

Thanks for all the help, finally I have working UHD Discs.

**Comment by jcdr428** [comment]
@DreckSoft No worries. I suppose you applied the patch on the version where the descriptor was still EAC3 / not changed to AC3.

I suspect the transport_priority flag does not matter in the case of secondary audio, but it would be nice if you can confirm that the latest nightly works with AC3 and EAC3 secondary audios (<=5.1 channels, no dependent substream).

Please also advise what change your make in BDEdit, maybe we can also include in tsMuxer.

**Comment by DreckSoft** [comment]
I use BDEdit to change all files created by MultiAVCHD to version 3.0 (UHD) and to edit the playlist file to include the correct video parameters and subtitle PIDs. This is not something that tsMuxeR could or should do as those are external files not related to the mux. tsMuxeR would already provide a playlist file but that lacks the addition information like popup menu, next play and so on. 

I'm currently talking to Pel about another change and then I'll publish a guide for everyone to use.

**Comment by DreckSoft** [comment]
@jcdr428 you may revert the patch for the format_identifier. I just checked, it also works if it is set correctly to EAC3. So it was just the transport priority.
