### ISSUE TITLE
Latest release ignoring GUI defaults for SEI/VUI and SPS/PPS

### ISSUE THREAD

**Issue by FlaTechNole21** [justdan96/tsMuxer#683]
I see that the latest release added the ability to set the defaults for these in the INI file, but only the GUI reflects these values, not the muxer/demuxer. Changing the values to something else seems to then apply the INI settings (such as checking/unckecking "Change Level" or any of the other options that aren't the mux/demux options).

I've attached the issue I'm seeing.

Running the Windows x64 release on Windows 11 22H2.

<img width="767" alt="SEI_VUI-SPS_PPS_bug" src="https://user-images.githubusercontent.com/64052729/222534857-bd14d754-1719-4bfb-bc76-5c6577fe93bc.png">

**Comment by jcdr428** [comment]
@FlaTechNole21 should be fixed in tomorrow's release, please try.

**Comment by FlaTechNole21** [comment]
Verified it is fixed in ba6a70d
