### ISSUE TITLE
Language information is missing in M2TS when muxing as Blu-Ray

### ISSUE THREAD

**Issue by DreckSoft** [justdan96/tsMuxer#684]
When muxing as Blu-Ray instead of M2TS, the resulting file does not contain language information for the streams. I'm not sure if this is relevant. However, the old 1.10.6 version did include that.

MediaInfo:
[New.txt](https://github.com/justdan96/tsMuxer/files/10883593/New.txt)
[NewM2TS.txt](https://github.com/justdan96/tsMuxer/files/10883595/NewM2TS.txt)

**Comment by jcdr428** [comment]
@DreckSoft in Bluray mode the language must be in the relevant mpls/clpi and not in the m2ts. 1.10.6 was not compliant with bluray specs.

**Comment by DreckSoft** [comment]
I just cross-checked with a commercial BD and that seems right.
