### ISSUE TITLE
Only 6978908 is working properly! new version remuxing error!!

### ISSUE THREAD

**Issue by kirscheee** [justdan96/tsMuxer#693]
except  6978908  
 
af7097b /  2aac012 / f6bb8a6, these three version, if I remuxing the bd file, i couldn't get the right time

for excemple, if I use "6978908" remuxing frome 0:20:12.341 to 0:26:32.884, I can get the file is 6 min. 20 sec.

but if I use af7097b /  2aac012 / f6bb8a6, I can't get the file with 6 min. 20 sec. this duration usually becomes shorter

I don't know why, if you have the same problem, just use the version of 6978908 it's right

**Comment by jcdr428** [comment]
@moveman your commit seems to need more work. I'll have to regress to previous.

**Comment by jcdr428** [comment]
@kirscheee this was due to latest commits, which have not been cancelled.
Closing.

**Comment by moveman** [comment]
Hi @kirscheee, @jcdr428, do you have files (input, meta, and even output) for us to reproduce and debug? Thanks.

**Comment by jcdr428** [comment]
@kirscheee please provide a sample of the file which created the bug, thanks.

**Comment by moveman** [comment]
@jcdr428, I see, thanks for fixing it.
