### ISSUE TITLE
tsMuxerGUI cannot add more than 1 file at one time to the input list to join

### ISSUE THREAD

**Issue by fixer121** [justdan96/tsMuxer#696]
Hello.
I need to join about 500 .ts files. Adding them to the Input list by the **join** button is possible only one at a time, which is a very long time. Through drag-and-drop, they are added, but not in join mode, which is reported for each.
I propose to allow the addition of several files at 1 time, with their automatic sorting. Perhaps via drag-and-drop.

**Comment by jcdr428** [comment]
@fixer121 if I am not mistaken, you can already join several files via the join button, by selecting several files in the "append media files" window ?

**Comment by Hellboy00000** [comment]
I tested the join button and can add more than 1 file (tested with 6 selected files "need to be the same extension") without any problem.

**Comment by jcdr428** [comment]
@fixer121 please confirm that the issue can be closed.
