### ISSUE TITLE
Segmentation fault (core dumped) for git-ae06827 version

### ISSUE THREAD

**Issue by vip5912** [justdan96/tsMuxer#697]
tsmuxer video.mkv
tsMuxeR version git-ae06827. github.com/justdan96/tsMuxer
Segmentation fault (core dumped)
It's only for git-ae06827. The previous ones work fine.
Linux desktop 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jcdr428** [comment]
My mistake, fixed in tomorrow's release...

**Comment by vip5912** [comment]
It's fixed in 82940736405b356a55ef5ffdc6ff618c767bc758.
