### ISSUE TITLE
Blu-Ray Formats Supported

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#698]
Here are specifications for BD-R video as follows:

"Blu-ray discs are capable of supporting different file formats such as MPEG-2, MPEG-4 High Profile AVC and VC-1 decoders which enable the discs to store up to four-hour worth of HDTV audio-video per layer. It is also capable of supporting different multi-channel audio file formats such as the different file formats of Dolby and DTS as well as PCM audio file formats. BD rewritable and recordable disc formats will also be backwards-compatible with older formats such as MPEG-2 while newer codecs will enable Blu-ray technology to support new file formats in the future".

This is how we help us improve the blu-ray section to make them available to watch on many players.

**Comment by missionfloyd** [comment]
https://www.sony.com/electronics/support/articles/00029663

**Comment by jcdr428** [comment]
@donnafaye0323 could you please clarify the issue / the codec not supported by tsMuxer in Bluray mode ?
To my knowledge, tsMuxer supports all Bluray codecs.

**Comment by jcdr428** [comment]
Closing, can be reopened upon request.
