### ISSUE TITLE
mass problem - error while muxing with extracting 29 line of SRT subtitles on almost  all DV MP4 files!

### ISSUE THREAD

**Issue by galactic76** [justdan96/tsMuxer#701]
You.People.2023.2160p.NF.WEB-DL.DDP5.1.Atmos.DV.MP4.x265-DVSUX.mp4
MP4/MOV error: invalid stts index for SRT track #29 at position 2075305747

**Comment by galactic76** [comment]
True.Spirit.2023.2160p.NF.WEB-DL.DDP5.1.Atmos.DV.MP4.x265-DVSUX.mp4
MP4/MOV error: invalid stts index for SRT track #29 at position 1611884284

**Comment by galactic76** [comment]
Im trying to muxing video audio and 29 subtitles, rus

**Comment by galactic76** [comment]
The.Strays.2023.2160p.NF.WEB-DL.DDP5.1.Atmos.DV.MP4.x265-DVSUX

Warning: PGS might not work without HDMV descriptors.
MP4/MOV error: invalid stts index for SRT track #29 at position 1387827529


The 4 film with 36 SRT line is muxing to ps withut errors

Why is that start happening?

It never happens before I use older versions

I already try 25/12/2022 16/09/2022 14/02/2023 - as well as 2 last - all not works :(

**Comment by jcdr428** [comment]
@galactic76 No problems on my side. I believe you don't use the latest tsMuxer version.

![image](https://user-images.githubusercontent.com/56721609/230151033-f84b5b1b-087f-49a5-b57b-a25d08eae3f7.png)

**Comment by galactic76** [comment]
Thanks alot
only last 0504 release is working
all others - not ;(

**Comment by jcdr428** [comment]
Yes fixing the "invalid stts index for SRT track" bug gave me some trouble. But now all should be ok.all subtitles hould mux ok.
