### ISSUE TITLE
I am experiencing an error on tsMuxer Mac (can't find ttf for arial) (please read description)

### ISSUE THREAD

**Issue by VRmt231** [justdan96/tsMuxer#705]
I've been having this error using MacOS Venture 13.1 about not having the ttf font for arial. I tried with a couple ttf fonts but it still shows the same error, even after trying the command from terminal. 

Is there a fix to this? I really need subtitles in this movie.

**Comment by jcdr428** [comment]
@VRmt231 For MacOS, tsMuxer seeks *.ttf in `/System/Library/Fonts/`, `/Library/Fonts/` and `~/Library/Fonts/`.

Do you have the arial.ttf in one of those folders ?

**Comment by VRmt231** [comment]
i checked the file path you mentioned. ill try with another font file that exists as ttf in that folder and share whether it seems to work or not.

**Comment by jcdr428** [comment]
@VRmt231 what is the exact error message ?

**Comment by donnafaye0323** [comment]
It is a bug that will be fixed. @justdan96 #707

**Comment by jcdr428** [comment]
No reply, closing. Can ve reopened upon request.
