### ISSUE TITLE
ISO - Error with label

### ISSUE THREAD

**Issue by allelouia** [justdan96/tsMuxer#710]
There is an error with the label flag. There is no space when the flag is added which sometimes makes the iso unreadable.
Example without label:
MUXOPT --no-pcr-on-video-pid --new-audio-pes --blu-ray --vbr

Same example with label:
MUXOPT --no-pcr-on-video-pid --new-audio-pes **--blu-ray--label="test"**  --vbr

The --label flag is not separate from the --bluray flag.

**Comment by jcdr428** [comment]
@allelouia thanks for reporting. Should be fixed in tomorrow's release.
