### ISSUE TITLE
BUG - Cant remux - immideatly 100% bar and nothing happens

### ISSUE THREAD

**Issue by galactic76** [justdan96/tsMuxer#712]
I want to remux 1 film and it return a bug - immideatly 100% bar and nothing happens

version e346384 ( only this version works fine, others before have a strange bevahior about E-AC3 sound ( it not remuxed)

film is here - http://kinozaltv.life/details.php?id=1977411

**Comment by jcdr428** [comment]
@galactic76 please provide a private link to download.

**Comment by galactic76** [comment]
I dont know how to PM you attach. But you can register by youself on a link and get it by yourself

**Comment by Hellboy00000** [comment]
You can't expect jcdr428 download 50gb movie every time someone has problems. You need to provide a link with the sample (example: in mega or google drive). You can use tsMuxeR or MKVToolNix to split the movie.

**Comment by jcdr428** [comment]
@galaxy76, 
For the "nothing happens": just be a little more patient and wait, the mux will eventually start.
This file is bizarely structured and includes hundreds of thousands of chunks.

For the starting 100%: I've changed the GUI so that it starts at 0%: please try tomorrow's release.

**Comment by jcdr428** [comment]
Fixed with commit [6db8dbb](https://github.com/justdan96/tsMuxer/commit/6db8dbb90a4a09050c7e4f97918d6067efdb7dfe)
