### ISSUE TITLE
film did not opens

### ISSUE THREAD

**Issue by galactic76** [justdan96/tsMuxer#721]
torrent - http://kinozaltv.life/details.php?id=1981503

build of tsmuxer - e346384 

aprox 40 minutes wait = then open file

then - tey ro remux t ts - it says =100% immideatly

i get latest nightly release - 5231f3c - all the same

UPD

40 minutes to open and 40 minutes to demux subtitles, but its work

why its no slow?

Is this normal? 

What shouls I suggest to releaser?

**Comment by jcdr428** [comment]
@galactic76
Anything different with older tsMuxer versions ?
If yes, can you please identify which version initiated the change. It will help identify the commit creating the issue.

**Comment by galactic76** [comment]
The thing is im using the latest and its still opening horrible - 15 minutes to wait - you even forget about it...

**Comment by jcdr428** [comment]
Please help in identifying whether this is a change from older versions.

**Comment by oniiz86** [comment]
@jcdr428 I too seem to have this issue only with a particular MKV file that has Dolby Digital Plus (E-AC-3) with a Bit Depth of 32 bits, is that the issue as I thought technically "lossy" does not have a Bit Depth?

The below image is from tsMuxeR GUI 2.6.12, more recent nightly builds as well as the latest June 28th nightly build https://github.com/justdan96/tsMuxer/commit/49a59c01e8d7f5c4c8a4c788167571767866f209 do not react to the file at all, it does not even open like @galactic76 has mentioned his files have above after quite some time has past :(
https://imgur.com/Sa0mY0u

**Comment by jcdr428** [comment]
@oniiz86 can you run tsMuxer in command line (not the GUI) and report the error message ?

**Comment by oniiz86** [comment]
@jcdr428 Sure, I've provided a short 3 minute sample [https://ufile.io/iu844zfm](url)

**Comment by jcdr428** [comment]
@oniiz86 message in CLI is "Error: Matroska parse error: Invalid EBML number size 10 at pos 0".
If you open the mkv sample in an hex editor, you effectively see that the mkv starts with html code and not with mkv stuff. The mkv is corrupted.

![HxD](https://github.com/justdan96/tsMuxer/assets/56721609/aea98f1c-0ca9-4e35-a16c-7b9864985738)

**Comment by oniiz86** [comment]
@jcdr428 That is strange as it plays back fine on my OPPO UDP-205 & BDP-105D players as well as MPC-HC & VLC media players, is there anyway that I can fix the corruption so it can be opened in tsMuxer as I'd like to mux it to m2ts?

I've tried a FFmpeg utility called Clever FFmpeg-GUI that opens it fine & can successfully re-mux it from mkv to m2ts but was curious as to why there is an issue with tsMuxer :(

**Comment by jcdr428** [comment]
@oniiz86 from the error messages in the html, I believe it is your upload on ufile that failed. Can you give a onedrive or google drive link ?

**Comment by oniiz86** [comment]
@jcdr428 Here is the OneDrive link https://1drv.ms/u/s!AmgVmKyn3jL-gVdhoidD7g63NehN?e=eRBenU

I've noticed that while the m2ts file created by Clever FFmpeg-GUI plays fine on my OPPO player, it fails to recognise the English PGS subtitle which is strange as I've never seen that before, MPC-HC & VLC players do recognise the PGS subtitle fine.

**Comment by jcdr428** [comment]
@oniiz86 Not sure the mkv is fully compliant but anyway I have pushed a fix. Please try tomorrow's release.

**Comment by oniiz86** [comment]
@jcdr428 The latest nightly build https://github.com/justdan96/tsMuxer/commit/fa3b5fc8cae78a099a134342904f3c973aa3a5e1 has fixed the issue, the file now opens without issue & can be muxed successfully, thanks so very much for that :)

I was just curious as to why for TS output the "Generate HDMV Compatible TS" is initially selected but when you select M2TS Output then select TS Output again it deselects, I believe it should remain selected by default as when I tried to create a .ts file the PGS subtitles were not generated by my bluray player only when I selected "Generate HDMV Compatible TS" was the .ts file fine with my bluray player now recognising the PGS subtitles which is correct as it is now bluray compliant, I believe that was the issue with the other program Clever FFmpeg-GUI that I mentioned above, it does not have the option to "Generate HDMV Compatible TS" descriptors for it to be bluray compliant & that is why my bluray player couldn't recognise the PGS subtitle.

**Comment by jcdr428** [comment]
@oniiz86 hdmv is bluray/ m2ts standard. Ts is not bluray standard so hdmv is not default: you need to select manually the option.
