### ISSUE TITLE
error while remuxing a movie nightbreed 

### ISSUE THREAD

**Issue by galactic76** [justdan96/tsMuxer#738]
error while remuxing a movie nightbreed 

on 61% is error #:070==>5 and it stops

I believe its from Tgh

**Comment by jcdr428** [comment]
@galactic76 please give a download link.

**Comment by galactic76** [comment]
5231f3c works fine, only older version have that problem.
you may close this isuue

**Comment by jcdr428** [comment]
@galactic76 what about latest release ?
