### ISSUE TITLE
LPCM

### ISSUE THREAD

**Issue by joske1964** [justdan96/tsMuxer#739]
The channels of LPCM are not seen. They are in the March 4 version.

**Comment by jcdr428** [comment]
@joske1964 not clear: can you please give more details of the issue ?

**Comment by joske1964** [comment]
In latest version I don't see any channels in tsmuxer with lpcm , and I have no audio after muxing. In the version of tsMuxeR 2023-06-28 Nightly Portable Windows 64-bit everything works fine. I mux a uhd blu-ray to iso.

**Comment by jcdr428** [comment]
@joske1964 please try tomorrow's release.

**Comment by joske1964** [comment]
I tested it with tsMuxeR 2023-08-29 Nightly Portable Windows 64-bit, and everything works fine. Thanks a lot
