### ISSUE TITLE
Making Blu-Ray With Error Code 11

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#740]
I created some Blu-ray videos, but it says "**TSMUXER FINISHED WITH ERROR CODE 11**. It may not play on Sony BDPs500 player, and this is a bug for the issue.
Can you fix this error so it will make it successfully function? I think it may help me with this issue. It will work it out so it will successfully keep things going.
![Screenshot from 2023-08-21 05-39-57](https://github.com/justdan96/tsMuxer/assets/40868495/42d8d220-ce91-44d6-aea4-4fc07e1aaaac)

**Comment by jcdr428** [comment]
@donnafaye0323 please provide a link so that I can download the three samples.

**Comment by donnafaye0323** [comment]
https://mixkit.co/free-stock-video/legal/
 Here are some sample videos

**Comment by jcdr428** [comment]
I need the three same 720p MPEG-2 videos that created the bug: the two INXS and the Sha Na Na.

**Comment by donnafaye0323** [comment]
I think that H.264 video format is way better than mpeg-2. Here's The reason:

A video container file stores video, audio, and metadata; one of the most common types of container files is MP4. H.264 works with multiple container formats, including MP4, TS, and [MOV](https://www.cloudflare.com/learning/video/mov-vs-mp4/).
  
So how can i convert videos to h264 format?

**Comment by jcdr428** [comment]
@donnafaye0323 use Handbrake software.

**Comment by jcdr428** [comment]
@donnafaye0323 please confirm whether the bug is fixed with today's release.

**Comment by donnafaye0323** [comment]
This is **error code 11**: MPEG-2 TS Files are corrupt, and this video codec may be outdated.

**Comment by donnafaye0323** [comment]
https://github.com/justdan96/tsMuxer/assets/40868495/b766e094-56ca-4ae4-b7aa-1e62e73819da


https://github.com/justdan96/tsMuxer/assets/40868495/e20fecec-f858-40ab-aae8-7daef3dadbff

These are the videos whose mpeg3-ts files are coruupted.

**Comment by lgoncal** [comment]
Might be time to close this.
Samples are not being provided, and it sounds like like it is a corrupt file causing issues.

**Comment by jcdr428** [comment]
Ok, closing.

**Comment by oniiz86** [comment]
@jcdr428 I believe 2 of the 3 samples were provided by @donnafaye0323 above that exhibits the issue, can those be used to diagnose the "Error Code 11" problem?

**Comment by lgoncal** [comment]
Just tried the 2 samples with the latest nightly 
Remuxed to mkv 
Joined the two files into a .ts
Repeated and joined them into a BD folder.
It all completed properly
NOTE
These two samples are AVC, not mpeg2
And, neither of these two samples are in the metafiles shown in the screen cap, they are completely different.
NOTE 2
Just repeated processed with my own 3 mpeg2 files I know are good.
tsMuxer worked fine
