### ISSUE TITLE
Creating Blu-ray Folders But Has Error Code

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#743]
I joined my 1080p videos and created my Blu-ray folders  to 98% but it says "**TSMUXER FINISHED WITH ERROR CODE 11. "**. Can You fix this error to make it work much better?

![Screenshot from 2023-08-21 15-42-54](https://github.com/justdan96/tsMuxer/assets/40868495/91630756-9da7-4e89-9992-bf4a235217f8)

Maybe because joining files sometimes causes some problems. This may be a bug and it will be fixed soon.

#341 #720  #244 #295

**Comment by jcdr428** [comment]
Duplicate of #740 - closing.
