### ISSUE TITLE
Bug with Avatar 1 & 2 4K

### ISSUE THREAD

**Issue by Hellboy00000** [justdan96/tsMuxer#751]
Same bug for both movie, Avatar 1 4k & Avatar 2 4k. When create a bluray folder with "w64 2023-08-23-01-49-32", finished without errors but playlist, index.bdmv and MovieObject.bdmv are not created. Version "w64 2023-08-01-02-13-35" work correctly.

Can't provide a sample because the movie is split in multiple m2ts files and maybe this is the problem. When i try with other movie with one file work correctly.

*Avatar 2 Log, with working version "w64 2023-08-01-02-13-35".

tsMuxeR version git-f254deb. github.com/justdan96/tsMuxer
HEVC muxing fps is not set. Get fps from stream. Value: 23.976
B-pyramid level 2 detected. Shift DTS to 3 frames
Decoding TRUE-HD stream (track 2): AC3 core + TRUE-HD + ATMOS. Peak bitrate: 4974Kbps (core 640Kbps) Sample Rate: 48KHz Channels: 7.1
Decoding AC3 stream (track 3): Bitrate: 1024Kbps (core 576Kbps) Sample Rate: 48KHz Channels: 7.1
Decoding PGS stream (track 6):  Resolution: 1920:1080  Frame rate: 23.976
Decoding PGS stream (track 4):  Resolution: 1920:1080  Frame rate: 23.976
Decoding PGS stream (track 5):  Resolution: 1920:1080  Frame rate: 23.976
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 00:03:32,895. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 00:04:06,623. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 00:04:33,632. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 00:08:43,135. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 00:17:03,552. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 00:17:14,751. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 00:17:14,847. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 00:22:42,720. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 00:22:42,847. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 00:32:02,976. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 00:32:19,167. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 00:33:19,968. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 00:33:20,160. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 00:50:29,791. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 00:50:30,016. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 00:59:32,255. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:00:13,248. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 01:00:24,096. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:02:15,967. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:10:48,192. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 01:10:48,511. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:16:19,423. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 01:16:29,728. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:16:50,336. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 01:16:50,720. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:24:29,247. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 01:24:42,528. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:30:45,087. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:31:32,640. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 01:31:33,087. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:31:42,815. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 01:31:43,296. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:42:50,815. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 01:43:10,239. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:45:44,863. Remove frame.
E-AC3 (DD+) stream (track 3): overlapped frame detected at position 01:45:56,159. Remove frame.
TRUE-HD stream (track 2): overlapped frame detected at position 01:45:56,735. Remove frame.
Processed 277023 video frames

*Version "w64 2023-08-23-01-49-32" stop here.

Flushing write buffer
Creating Blu-ray stream info and seek index
Creating Blu-ray playlist
Mux successful complete
Muxing time: 9 min 40 sec

**Edit: Last working version "w64 2023-08-14-01-50-37"

**Comment by trzyglow** [comment]
try merging the input files into one, before processing with tsmuxer. maybe that helps.

**Comment by jcdr428** [comment]
@Hellboy00000 please try tomorrow's release.

**Comment by Hellboy00000** [comment]
New version worked. Thanks.
