### ISSUE TITLE
Downconvert to AC3 cannot handle the end, inserts some THD

### ISSUE THREAD

**Issue by ValeZAA** [justdan96/tsMuxer#761]
So, yeah. `https://mailccsf-my.sharepoint.com/:u:/g/personal/dirizar2_mail_ccsf_edu/EYP2uEVslUBGsaq15jmKAFoB1XtcWyW1wbipAmT5kvph-w?e=7o5BSJ`

Demux AC3 and you will see that in hex editor starting with 0x010c33b8604d and until the end it is actually THD data.

FFmpeg has no such bug.

You can also use FFmpeg to verify that it is indeed correct THD stream. Use FFmpeg to extract THD out of m2ts and change last byte (0x40) to 0x10, e.g. FFmpeg will complain that checksum of substream 2 is invalid.

THIS IS problematic because for AC3 ffmpeg does not like the garbage after EOF and does not decode some sound of AC3.

**Comment by ValeZAA** [comment]
Fixed.

**Comment by ValeZAA** [comment]
Another such issue is in EAC3 on Blu-ray: downconvert to AC3 still leaves one last frame to be EAC3.

**Comment by Hellboy00000** [comment]
@jcdr428 @ValeZAA Maybe is better if create a new issue. Probably jcdr428 don't check closed issue.

**Comment by jcdr428** [comment]
Yes I received notification, no need to open new issue.

**Comment by jcdr428** [comment]
@ValeZAA the few trials I have done all produce ac3 without eac3 frames. Do you have a sample that I can use to reproduce the bug ?

**Comment by jcdr428** [comment]
@ValeZAA should be fixed, please try tomorrow's release.

**Comment by Hellboy00000** [comment]
Not received any warning with eac3to this time. Fixed. Question, Why the extension is .ac3+ec3 and not .ac3.

**Comment by jcdr428** [comment]
The extension is based on the detection of the input, I'll see how the extension can be modified in case of downconvert.
