### ISSUE TITLE
00000.clpiBDMV

### ISSUE THREAD

**Issue by Nemesh64** [justdan96/tsMuxer#762]
Hello jcdr428,

Currently I am working on the series The Swarm.
When I mux a episode and I look in the output folder BDMV -> CLIPINF, it contains a folder called: 00000.clpiBDMV
In the 00000.clpiBDMV there is the folder BACKUP, in that folder is the directory CLIPINF
Finally, in the CLIPINF folder is a file called: 00000.clpi
Using the latest TsMuxer from 2 Sept. 2023.
Is this a bug?
It also happens when I mux movies.
With kind regards,

Nemesh

**Comment by Hellboy00000** [comment]
Problem start after "w64 2023-08-14-01-50-37" and before "w64 2023-08-27-01-53-25".

**Comment by jcdr428** [comment]
@Nemesh64 should be fixed in tomorrow's release.

**Comment by Nemesh64** [comment]
Thanks for the fast reply and fix jcdr.
Kind regards.
