### ISSUE TITLE
receiving this error

### ISSUE THREAD

**Issue by Archangel-of-the-Apocolypse** [justdan96/tsMuxer#763]
![image](https://github.com/justdan96/tsMuxer/assets/143966609/596d4d72-cb05-4b4e-8232-cdd3a93d0e82)
there is no error code so unable to ascertain the problem.    Have been trying to get an MP4 to convert to Blue Ray .  Any suggesstions

**Comment by jcdr428** [comment]
@Archangel-of-the-Apocolypse the error message should show in cli mode: save the .meta file and type 'tsMuxer.exe pathto.meta output.ts' in a cmd console (with the correct paths)

**Comment by jcdr428** [comment]
Closing -relates to tsMuxer 2.6.12, not tsMuxer open source.
