### ISSUE TITLE
Tracks not listed for special case of playlist

### ISSUE THREAD

**Issue by medikoo** [justdan96/tsMuxer#764]
I've approached problem which I didn't approach in tens of discs I've remuxed before

There's a Blu-ray disc for which MakeMkv and handbrake properly report that that playlist `00000.mpls` covers 7 chapters video with single audio track and single subtitle track.

When I paste this playlist as input to tsMuxer it presents as below:

<img width="1108" alt="Screenshot 2023-09-06 at 09 34 20" src="https://github.com/justdan96/tsMuxer/assets/122434/0e994e8f-66e8-4f51-a094-09fc0bfdf8d9">

There's no audio and no subtitle tracks is listed. I assume it's because the starting `00002.m2ts` file in playlist which is short production logo, doesn't have any audio and subtitles track. It is that following movie `00000.m2ts` that has that, and I can see that when I paste this `m2ts` as input directly:

<img width="916" alt="Screenshot 2023-09-06 at 09 34 43" src="https://github.com/justdan96/tsMuxer/assets/122434/eef54a95-36c0-46fa-8e31-dbded989c649">

Problem is that I cannot remux this disc preserving the chapters with some edits applied (e.g. not included original subtitles).

I believe that `tsMuxer` should present all channels found in all tracks in such case and not limit tracks list to first `m2ts` file

**Comment by jcdr428** [comment]
Hi @medikoo, this bug has already been reported e.g. in issue #633, however no solution yet.

**Comment by medikoo** [comment]
@jcdr428 thanks for pointing. I've searched but this issue didn't come up. Anyway closing as duplicate
