### ISSUE TITLE
[Feature Request] MKS (Matroska Subtitle Container) support

### ISSUE THREAD

**Issue by trzyglow** [justdan96/tsMuxer#765]
since mkv and mka are supported, it would be nice to also have the option to import subtitle packages in a mks container.

**Comment by jcdr428** [comment]
@trzyglow easy one... please try tomorrow's release.

**Comment by trzyglow** [comment]
Muxing produces errorcode "-2"

**Comment by jcdr428** [comment]
Sorry, I didn't test thouroughly... Should be fixed in tomorrow's release.
You can also try the lastest actions builds https://github.com/justdan96/tsMuxer/actions

**Comment by trzyglow** [comment]
thanks, it's working properly in the latest actions build.
