### ISSUE TITLE
Extracted LPCM audio can't be encoded in ffmpeg nor muxed in mkvtoolnix.

### ISSUE THREAD

**Issue by R3S3t9999** [justdan96/tsMuxer#774]
sample: https://drive.google.com/file/d/1yCbnegd1tLkOB4WsN42xLbi15lXmzCmJ/view?usp=sharing

ffmpeg:
[wav @ 000001bbe75f5340] no 'data' tag found
D:\1.wav: Invalid data found when processing input

mkvtoolnix:
The file '00000.track_4352_eng.wav' was not recognized as a supported format (exit code: 2).

thank you!

**Comment by jcdr428** [comment]
@R3S3t9999 Please try tomorrow's release.

**Comment by R3S3t9999** [comment]
thanks, it worked!
