### ISSUE TITLE
tsMuxeR not found error

### ISSUE THREAD

**Issue by marb99** [justdan96/tsMuxer#78]
with lastest "w32-nightly-2019-12-14--14-44-59" build give me "tsMuxeR not found!" error and I have the "tsMuxeR.exe" and "tsMuxerGUI.exe" in the same folder.

**Comment by justdan96** [comment]
Seems the same as #63, I'll check it on my Windows box

**Comment by xavery** [comment]
This is my fault - please see [this commit](https://github.com/xavery/tsMuxer/commit/f651d65bbf80f7cc103c5a03c1da84e3a4526fdf) for a possible fix, but I don't have a Windows machine to test at the moment.

**Comment by justdan96** [comment]
@xavery you're too quick I was just replying!

I tested a hack that worked for me using a #define but I knew you'd have a much better solution! I've tested that commit and it indeed does resolve the issue on Windows and still works fine on Linux.

**Comment by xavery** [comment]
@justdan96 Fantastic! I'll get my Windows VM sorted out so I can test GUI stuff on it as well.

**Comment by darekpro** [comment]
New problem after fresh build arch git 
https://i.imgur.com/NnML4qg.png
