### ISSUE TITLE
Adding And Joining .mts Files With TsmuxeR Error

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#790]
I was adding video files from my USB Drive and it says "Tsmuxer Error".  I know that it  only outputs to TS and M2TS containers. My operating system is: Linux Mint 21.3 'Victoria."
Here's this screenshot of this error:

![Screenshot from 2023-10-10 14-24-08](https://github.com/justdan96/tsMuxer/assets/40868495/d6e5631c-9ea6-49ff-a9f6-9fa0cabaaebb)
 
This bug needs to be fixed as soon as possible.

**Comment by lgoncal** [comment]
Links for the files causing errors?

**Comment by donnafaye0323** [comment]
> Links for the files causing errors?

Maybe this article will help you explain how to join files without conversion:

https://www.journeybytes.com/how-to-join-videos-without-conversion-using-tsmuxer/

**Comment by lgoncal** [comment]
I know how to join files without converting codecs, thank you.
The developers might need the actual files that caused the issue so they can debug

**Comment by donnafaye0323** [comment]
> I know how to join files without converting codecs, thank you. The developers might need the actual files that caused the issue so they can debug
Here's a video sample about Thanksgiving

https://github.com/justdan96/tsMuxer/assets/40868495/9f2edee4-3a15-4fbd-afb6-0e7fa0c8e3b3

**Comment by donnafaye0323** [comment]
Here's Video Sample Edited From a USB Flash Drive:

https://github.com/justdan96/tsMuxer/assets/40868495/b6d695e7-675f-48ea-a22b-0c8e39bae6d6

**Comment by jcdr428** [comment]
@donnafaye0323 the title is "Adding and joining .mts files", please either provide the correct sample or change the title.

**Comment by donnafaye0323** [comment]
Here's The MP4 Video Sample  Converted From the USB Flash Drive:

https://github.com/justdan96/tsMuxer/assets/40868495/9442af7e-558c-40f2-923f-47559fad468f

**Comment by donnafaye0323** [comment]
> @donnafaye0323 the title is "Adding and joining .mts files", please either provide the correct sample or change the title.

Here's another Video sample from my USB Drive:

https://github.com/justdan96/tsMuxer/assets/40868495/322cea5f-94b6-49fa-b75b-ee641f142dc9

**Comment by jcdr428** [comment]
@donnafaye0323 1. no problems with tsMuxer muxing the samples provided, and 2. the issue title is "adding and joining .mts files".
Closing until clarifications or correct samples are provided.

**Comment by donnafaye0323** [comment]
Here's another video sample of what it looks like while importing .mts files to Blu-Ray:

Uploading WSFX-DT-10282023-0847_H.264.mp4…

**Comment by Hellboy00000** [comment]
That is not a .mts file. That is another .mp4 file.

**Comment by donnafaye0323** [comment]
Here's MTS Vide File Sample 01:

**Comment by lgoncal** [comment]
That's a jpg

**Comment by donnafaye0323** [comment]
> That's a jpg

This is a sample of a MTS Video error that will be fixed:
[Circle-10292023-1242.mts.zip](https://github.com/justdan96/tsMuxer/files/13198822/Circle-10292023-1242.mts.zip)

I hope they can see this type of error.
