### ISSUE TITLE
Importing PVR Recordings from USB Flash Drive But Stack Smashing Error Detected

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#792]
I imported this PVR recording from my USB Drive,  but it says "stack smashing detected" and TsMuxer  was terminated.
Here's a screenshot of this error:

![Screenshot from 2023-10-17 16-06-10](https://github.com/justdan96/tsMuxer/assets/40868495/706d8438-fcc8-4f3a-ae16-9290e3eb3074)

This issue is to be fixed as soon as possible.

**Comment by jcdr428** [comment]
@donnafaye please try tomorrow's release, and if not fixed, please provide a sample provoking the bug.

**Comment by donnafaye0323** [comment]
This is an MP4 video sample encoded from a USB Flash Drive.

https://github.com/justdan96/tsMuxer/assets/40868495/9ba3867c-bbac-452d-901e-95d7506c6633

**Comment by jcdr428** [comment]
@donnafaye0323 no problems with your sample and latest release bb60714.

**Comment by jcdr428** [comment]
No problems with the sample provided, closing.
