### ISSUE TITLE
Importing PVR Videos From USB Drive But With TsMuxer Error and Bad Frames Detected

### ISSUE THREAD

**Issue by donnafaye0323** [justdan96/tsMuxer#795]
![Screenshot from 2023-10-10 14-24-08](https://github.com/justdan96/tsMuxer/assets/40868495/fd05afaf-bb1e-470f-ab6b-d024aba9b732)
This is a error that means TsMuxer created when bad frames were detected  while importing uploading .mts files from my USB Drive. It reminds me of issues #712 ,  #628 and #790. 

I will hope that these bugs will be fixed as soon as possible.

**Comment by jcdr428** [comment]
@donnafaye0323 Please try tomorro's release, should fix reading AVCHD .mts.

**Comment by donnafaye0323** [comment]
Here's one of your MP$4ttps://github.com/justdan96/tsMuxer/assets/40868495/5ee97de5-678e-41a3-ab3b-02f8e7fdbdd1

**Comment by donnafaye0323** [comment]
Here's an MP4 Video Sample From my USB Flash Drive:

https://github.com/justdan96/tsMuxer/assets/40868495/b56a82e8-bba4-4fe7-a045-d796e2e2c8e9

**Comment by jcdr428** [comment]
@donnafaye0323 1. provided mp4 does not create any error, and 2. "bad frames were detected while importing uploading **.mts**": the sample does not correspond to the described issue.
Closing until clarification or correct sample has been provided.

**Comment by donnafaye0323** [comment]
Here Is A Video Sample For This Issue:
