### ISSUE TITLE
Dolby Vision bug

### ISSUE THREAD

**Issue by Hellboy00000** [justdan96/tsMuxer#798]
Dolby Vision bug in last version "2023-10-21-01-50-32"

Original movie
![DV-1-original](https://github.com/justdan96/tsMuxer/assets/53314399/008f88aa-f6c4-4922-b545-eb5511828ab4)

Good tsMuxer 2023-09-30-01-50-24
![DV-3-2023-09-30-01-50-24](https://github.com/justdan96/tsMuxer/assets/53314399/98f4b35a-bdff-478e-a576-555ff8bc9120)

Bad tsMuxer 2023-10-21-01-50-32
![DV-2-2023-10-21-01-50-32](https://github.com/justdan96/tsMuxer/assets/53314399/5d2ccd1e-9b79-48ca-ad6a-e56206c06b0c)

I think the bug was introduced here:
https://github.com/justdan96/tsMuxer/issues/781

I don't understand the use of "Dolby Vision MKV to BD" because those MKV are cropped and when they are used with tsMuxer the picture looks stretch. So you need to encode an encoded video to add the black bars and that make the video looks worse.

**Comment by DreckSoft** [comment]
Of course you can only mux them to BD of they uncropped. No you do not need to reencode anything. Yes, you will lose DV but the result plays fine as HDR10. 

Of course the patch was not supposed to break anything.  The second stream should be recognized as DV_EL but it isn't.

Then I don't know how to patch it so both cases create a correct result.

**Comment by Hellboy00000** [comment]
I always thought you need to encode again to add black bars. How you add the black bars without encoding?

**Comment by DreckSoft** [comment]
Why should I add black bars to a 2160p file? That does not make any sense.
