### ISSUE TITLE
Failure to find: debug/tsMuxerGUI_resource_res.o

### ISSUE THREAD

**Issue by tamplin** [justdan96/tsMuxer#8]
` # generate the tsMuxerGUI makefile`
`export PATH=$PATH:/mingw32/qt5-static/bin`
`cd ..`
`cd tsMuxerGUI`
`qmake`

$ qmake
WARNING: Failure to find: debug/tsMuxerGUI_resource_res.o
WARNING: Failure to find: release/tsMuxerGUI_resource_res.o

**Comment by justdan96** [comment]
Does this stop the build progressing? I think I got that but just ignored it.

**Comment by tamplin** [comment]
no. finally i successed.
