### ISSUE TITLE
TSmux Nightly BREAKS Audio compatibility between HW players ! 

### ISSUE THREAD

**Issue by metagondria** [justdan96/tsMuxer#806]
to my surprise i just found out that media files containing E-AC3 tracks are affected in a bad way once it has been remuxed by latest build of Tsmux Nightly !

Reading original untouched source containing EAC3 track, played just fine from usb stick on my smart HDTV.
After remuxing (not recoding = passsthrough) that very same media file, teletuby throws the following error → audio format not supported ← !!!

That means the compatibility of all new created media files via tsmux nightly builds are ruined to some degree !!!!
It will play in certain HW devices .. not ALL !!

JUST GREAT >_>

**Comment by jcdr428** [comment]
@metagondria can you please advise what is the latest tsMuxer working version.

**Comment by metagondria** [comment]
> @metagondria can you please advise what is the last tsMuxer working version.

You name it , i've used it..  To start with latest build ofcourse... ALL the way Down to old 2.16.x  >_>

**Comment by jcdr428** [comment]
@metagondria you mean all the way down to 2.6.12 ?
So I have no way to know what causes this bug.
Note that reading pure eac3 is not mandatory for Blu-ray players, so it is not really a bug.

**Comment by metagondria** [comment]
> @metagondria you mean all the way down to 2.6.12 ? So I have no way to know what causes this bug. Note that reading pure eac3 is not mandatory for Blu-ray players, so it is not really a bug.

To me it looks like more of an mux issue than anything else.  Since the tele plays the eac3 tracks from the media file as is = untouched just fine..  ONLY when i remux that media file using tsmux, error pops up → Audio format Not supported !?

Like, no recode has been done just remux so the audio track itself hasn't been altered , yet.. no AUDIO .. just and because of an remux !!

Not A bug ?  i beg the differ..

**Comment by metagondria** [comment]
Update:

Just double checked if the audio and / or container is compatible with the HDTV.
And the eac3 track in a m2ts container should play just splendid on my HDTV.

I have tested that with an sample obtained from here → [Link](https://kodi.wiki/view/Samples)

**Comment by jcdr428** [comment]
Can you please post a link for the sample that works, and the link for the remuxed sample that does not work ?

**Comment by metagondria** [comment]
> Can you please post a link for the sample that works, and the link for the remuxed sample that does not work ?

Sure jc, it's the least i can do :) 

check the → **[LINK](https://www.mediafire.com/file/54984gmxlpdn1wj/Working+Non-Working+samples.zip/file)** 

Just so you know, the audio track from the nonworking sample, keeps failing even if i remux that sample to another container (mkv, ts, m2ts ect)..  I mean, once i mux an perfect working source file into another m2ts via tsmux, the compatibility is completely broken, and remux doesn't fix that anymore.  Wich ussually does, but not in this case..  


keep me posted..

cheers,

**Comment by jcdr428** [comment]
@metagondria the link is broken.

**Comment by metagondria** [comment]
> @metagondria the link is broken.

I saw, that it wos downloaded several times so i took it down again.
But i've uploaded better samples.

And to be exact, the issue is that the EaC3 in Mkv does play fine on the tele, but once muxed into m2ts with tsmux , the sound isn't supported message popsup !? 

And i wonder if that has anything to do with the mux process you see  ?!

Here's the **[→LINK←](https://www.mediafire.com/file/gg48ploine2ce6a/Working+Non-Working+samples.zip/file)**

cheers

**Comment by jcdr428** [comment]
The link includes an AC3 in working.m2ts and an EAC3 in non-working.m2ts ?
I need a sample of a m2ts with EAC3 track, working on your player.

**Comment by metagondria** [comment]
> The link includes an AC3 in working.m2ts and an EAC3 in non-working.m2ts ? I need a sample of a m2ts with EAC3 track, working on your player.
> 
> Edit : this is a link from the Kodi Wiki : [M2TS @ 1080p/29.97](https://mega.nz/#!cM9VmBSL!mME5qULH2H5M24vLmjqfZZkaoUjY6RsrGPiw3ultMW0) : does it work on your TV / does it break once muxed ?


I have indeed uploaded 2 files..  an working *.MKV file and a non-working *.M2TS game both containing E-AC3 tracks though (no AC3 tracks !?)

The sample you have uploaded, doesn't work on my hd tv..  That's just the confusing problem...  Me Too have DL m2ts samples with EAC3 from other sources, and the problem is that the EAC3 tracks is NOT SUPPORTED by my tele IF and ONLY IF it's in a M2TS container !?

Why is that do you think?  I mean, the tele  play's MT2S files just fine aslong the audio codec is AC3.  but it supports EAC3 aswell but ONLY from MKV files !?!?!?  That's what i don't understand.

The tele supports E-AC3 audio format just FINE, ONLY NOT when it's in a M2TS container !???  Is that a mux issue or something else ?

cheers,

**Comment by jcdr428** [comment]
> Just so you know, the audio track from the nonworking sample, keeps failing even if i remux that sample to another container (mkv, ts, m2ts ect)..

Do I understand well that if you mux a working eac3 in tsMuxer then transmux the m2ts to mkv, the mkv does not work anymore on your TV ?
What happens if you first demux the eac3 from the non-working m2ts, then remux to mkv: does the mkv work on your TV ? If not, it would mean that the demuxed eac3 is different from the original eac3, which would be worrying.

**Comment by metagondria** [comment]
> > Just so you know, the audio track from the nonworking sample, keeps failing even if i remux that sample to another container (mkv, ts, m2ts ect)..
> 
> Do I understand well that if you mux a working eac3 in tsMuxer then transmux the m2ts to mkv, the mkv does not work anymore on your TV ? What happens if you first demux the eac3 from the non-working m2ts, then remux to mkv: does the mkv work on your TV ? If not, it would mean that the demuxed eac3 is different from the original eac3, which would be worrying.


NO, ONLY M2TS files containgin EAC3 doesn't work!  Other formats like .mkv containing eac3 do just work on my tv , as i have mentioned several times !?

Interestingly enough, i have taken the nonworking m2TS and converted it to an MKV as you have suggested.  So, just changed the container from m2ts To Mkv again using toolnix..  And the EAC3 audio works again on my tele !?

So, it seems my tele has dificulties playing EAC3 audio tracks from ONLY → M2TS ← containers !!!

SO AND AGAIN, is this an TS/M2TS / TSMUX issue or what ?
THAT ↑↑ i dON'T GET !

But i have an large Movie/episode archive ... and i'll try to find an M2TS source containing EAC3 and try to playback that.
If that doesn't work, i suspect the software/firmware from my tele doesn't support EAC3 in M2TS containers i guess..

cheerrs,


cheers,

**Comment by jcdr428** [comment]
Ok .. I close the issue, and ifever you find an eac3 m2ts that initially works then does not work after muxing, you can reopen the issue.

**Comment by metagondria** [comment]
> Ok .. I close the issue, and ifever you find an eac3 m2ts that initially works then does not work after muxing, you can reopen the issue.

yep, i'll do that..
