### ISSUE TITLE
24 bit LPCM audio not working

### ISSUE THREAD

**Issue by jcdr428** [justdan96/tsMuxer#823]
### Discussed in https://github.com/justdan96/tsMuxer/discussions/822

<div type='discussions-op-text'>

<sup>Originally posted by **sebarious70** January 21, 2024</sup>
I created a BD image with a video .264 file and a Wave that is 24 bits 48 Khz. As far as I know, the Blu-ray spec allows for this.

But the resulting BD-RE, when burned and put in the blu-ray player, plays little else than white noise, and in the background you can hear some of the original audio, but for the most part it's loud white noise.

I considered the possibility that it might be a burning error, so I opened the ISO file with VLC, and it's the same thing. I also opened the source 24/48 audio file and it's fine, no white noise.

So I exported the audio again as wav, but this time as 16 bits / 96 Khz, dragged it into TS Muxer, created the ISO file again, and then the audio was perfectly fine.

So I wonder if TS Muxer doesn't allow for BD authoring with LPCM 24 bit audio. Is that the case? I cloned the code and opened the two files with the code that handle LCPM, which as far as I can tell are lpcmStreamReader.cpp and lpcmStreamReader.h. I don't know anything about programming, but the names make that obvious. 

I did a search for 16 and I came to a point in the lpcmStreamReader.cpp file that maybe has something related to this. Of course, not knowing the first thing about code, I'm not sure what those actions are, but it's this part:

<img width="989" alt="Screenshot 2024-01-21 at 01 42 27" src="https://github.com/justdan96/tsMuxer/assets/157246475/52362a16-55f7-4887-a569-c3b9b1f40e51">

So this part tells me that if it's 16 bits, then it does something:

```
if (m_bitsPerSample == 16)
    {
        for (auto curPos = (uint16_t*)start; curPos < (uint16_t*)end; ++curPos) *curPos = my_htons(*curPos);
    }
```

And this part tells me that if the bit depth is higher than 16 bits, then it does something else.

 ```
 else if (m_bitsPerSample > 16)
    {
        for (uint8_t* curPos = start; curPos < end - 2; curPos += 3)
        {
            uint8_t tmp = curPos[0];
            curPos[0] = curPos[2];
            curPos[2] = tmp;
        }
```
But that's just a guess. 

So is it possible to author a BD with TS Muxer that has 24 bit LPCM audio or not?

</div>

**Comment by jcdr428** [comment]
@sebarious70 I've opened an issue.
Can you please share a sample of the 24-bit LPCM creating this issue.

**Comment by sebarious70** [comment]
Do you mean of the file that I import into TS Muxer, or the file that it produces with the glitch?

**Comment by sebarious70** [comment]
OK, so I shared it in the forum because the two emails I sent with the short wav bounced.

**Comment by jcdr428** [comment]
@sebarious70 You should be able to attach the file directly into the github reply window.
Size limits are https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files
Alternatively, post a OneDrive or GoogleDrive or WeTransfer link.

**Comment by jcdr428** [comment]
@sebarious70 the problem arises from the non-standard (but spec compliant) 'FLLR' (filler) chunk added by the iPhone: if you remove the chunk with an hex editor, then tsMuxer muxes correctly.
Same sample with the 'FLLR' chunk removed: [24 bit sample for justdan96 -modified.zip](https://github.com/justdan96/tsMuxer/files/14169000/24.bit.sample.for.justdan96.-modified.zip)

I'll explore how to solve it.

**Comment by sebarious70** [comment]
Sorry, you mean the 24/48 WAV has something called FLLR that is added by the iPhone? But I never used my iPhone for this. However, I used Final Cut Pro X. Could that be the reason?

**Comment by jcdr428** [comment]
Yes the filler chunk is added by Apple to all apps using AVAudioRecorder.
I've just pushed a fix, please try tomorrow's release and confirm whether this issue is solved.

**Comment by sebarious70** [comment]
Thanks for fixing that! Just so I’m clear on what to do, I would have to do what is laid out in the COMPILING.md document at the bottom under "MacOS (Native)”, correct?

**Comment by jcdr428** [comment]
@sebarious70 just download the latest release https://github.com/justdan96/tsMuxer/releases

**Comment by sebarious70** [comment]
Hey man, sorry, I didn't have time to check on this until today. I’m playing the Blu-ray with the LPCM track rendered to 24/48 and it plays perfectly fine. Thank you so much!

What’s the link to donate something?

**Comment by sebarious70** [comment]
I've been up and down the thread and I don't see anywhere I can click to close the issue. Maybe it's because you opened it so you're the only one who can close it? Sorry, I rarely visit Github.

**Comment by sebarious70** [comment]
Sorry, I just saw this:

"We are not currently accepting any kind of donations and we do not have a bounty program."

Makes me feel bad, I've been using this program every once in a while for several years. I'd be happy to donate to you guys if you give me a link or a Paypal email.

**Comment by jcdr428** [comment]
Don't worry about donations, there are only independent volunteers working on tsMuxer. The best way to help is to report issues as you did.
Closing.

**Comment by sebarious70** [comment]
Well, I really appreciate all of you volunteers for working on this great software that has always been my first go to when I have to rewrap something, and now it’s even allowing me to burn my home movies to Blu-ray right from my Mac. Final Cut Pro X can do it but it adds a crappy looking menu even when you tell it not to, and you barely have any control over bitrate and things like that.

Is there a way to get a notification when you guys publish a new version?

**Comment by jcdr428** [comment]
You can customise notifications as explained on this page:

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/about-notifications
