### ISSUE TITLE
Movie Migration problem with Atmos Audio

### ISSUE THREAD

**Issue by Nemesh64** [justdan96/tsMuxer#830]
Have here the movie Migration blu-ray.
I make a movie-only from this blu-ray with my own .sup file.
When I play the result with PowerDVD the audio stutters the few first seconds and then
after approx 15 seconds the screen freezes and the playsback stops.
Then tried a playback on the media player in the livingroom.
Same problem.
But, if I do a Downcovert from the Atmos track to AC3 it works fine.
No problems with the playback.
So it seems TsMuxer has a problem with the Atmos audio track.
Using the latest TsMuxer from 17 Feb. 2024.
Please let me know what files you want for evaluation.
The main .mpls for the movie is: 00800.mpls
With regards,

Nemesh

**Comment by Nemesh64** [comment]
Hello Jcdr, you can download the sample here: https://we.tl/t-5K51ikxQUR

**Comment by Nemesh64** [comment]
Hello Jcdr, were you able to download the sample?

**Comment by jcdr428** [comment]
Hi @Nemesh64 , yes I downloaded and analysed it. All versions of tsMuxer incorrectly mux the AC3, and I could not find the reason.

**Comment by Nemesh64** [comment]
That's to bad... is there anything more I can do?

**Comment by jcdr428** [comment]
Hi @Nemesh64, no need for more sample.
I'll leave it to somebody else to try and resolve...

**Comment by Nemesh64** [comment]
So the chance is very high that it will not be resoved like the bug War Of The Worlds S1 Episode 4 I reported.
Give you my best regards,

Nemesh
