### ISSUE TITLE
MKV -> M2TS output out of sync

### ISSUE THREAD

**Issue by IzanagisBurden** [justdan96/tsMuxer#869]
Importing an MKV into tsMuxer and selecting the M2TS output option results in a file with A/V sync issues. No special delays on any of the tracks.

Extracting the streams first with mkvextract, then importing those streams into tsMuxer results in a file with no sync issues. Tested with 2 movies so far.

This did not seem to be an issue in previous versions of tsMuxer although I am not sure which version caused the issue to appear first.

**Comment by jcdr428** [comment]
@IzanagisBurden Should be solve with resolution of #874. Could you please confirm ?
