### ISSUE TITLE
WARNING - MKV with DTS result in audio out of sync

### ISSUE THREAD

**Issue by Hellboy00000** [justdan96/tsMuxer#874]
When using an MKV file with DTS, the result is a file with out-of-sync audio.

The bug was introduced in w64 2024-04-04-01-54-45.

For now i going back to use w64 2024-02-17-01-49-50
Hope people see this warning and don't need to go back to fix a few files like i have.

**Comment by jcdr428** [comment]
@Hellboy00000 can you provide a sample of DTS MKV resulting in the bug ?
I've tried most of the DTS MKV samples from https://kodi.wiki/view/Samples and could not reproduce.

**Comment by Hellboy00000** [comment]
I created a sample with the first 11 minutes of Super Mario Bros. (1993). (6.2GB)
I tested in "M2TS muxing" and "Blu-ray folder" and the bug occurs on both.

It is easier to see the error starting at minute 9:30. Watch when the man collides with the glass and then when they are on the phone.

Password = tsmuxer

https://drive.google.com/file/d/1ulMBIXxqLkWaj_mLki4w3zgZQNs9SrNW/view?usp=sharing
https://drive.google.com/file/d/1UKhaqle-Pcx33fgWqHeZQhVt-vLjMuQ9/view?usp=sharing
https://drive.google.com/file/d/1FuEDcTksvf4aDZn_yHvmD86wVnQtRtsj/view?usp=sharing
https://drive.google.com/file/d/1AKjFbHMQr_hxlMjNkWaEFR78-IQfCJQm/view?usp=sharing
https://drive.google.com/file/d/1r4KOyRJG5BYtDNJSUEzFoSuU0Rs-f9Bn/view?usp=sharing
https://drive.google.com/file/d/1Mk5XTUmNPOh4dDQg4nM3z6VFNuUj7O4_/view?usp=sharing
https://drive.google.com/file/d/1LC25BnK2N9ahNZS9LK-vr2RvHrPtzm2_/view?usp=sharing

Please let me know when finish downloading the files.

**Comment by jcdr428** [comment]
@Hellboy00000 I have downloaded the file, thank you.

**Comment by Hellboy00000** [comment]
Tested and work great.
Thanks.
