### ISSUE TITLE
TSMUXER 2.6.15 on macbook catalina cant detect image file

### ISSUE THREAD

**Issue by Liv77** [justdan96/tsMuxer#98]
I just downloaded tsmuxerGUI for mac 2.6.15 and this message keeps popping up? How can this be fixed? I searched for reason and it said I had to download homebrew and delete libefreetype  and i did it all in  the terminal and and i tried adding the video file again and same message pops up? Below are the attachments

![TSMUXER on MAC](https://user-images.githubusercontent.com/59346428/71564022-9a7b6e80-2a67-11ea-9dbc-80ebd265be9a.png)

[Hombrew.txt](https://github.com/justdan96/tsMuxer/files/4008704/Hombrew.txt)

**Comment by justdan96** [comment]
Just to make sure, have you followed the steps in the readme and run the following 2 commands:

```
brew install freetype
brew install zlib
```

**Comment by Liv77** [comment]
Last login: Sun Dec 29 17:44:45 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
-bash-3.2$ brew install freetype
==> Installing dependencies for freetype: libpng
==> Installing freetype dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.37.catalina.bott
==> Downloading from https://akamai.bintray.com/c8/c8e74da602c21f978cd7ee3d48997
######################################################################## 100.0%
==> Pouring libpng-1.6.37.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.37: 27 files, 1.2MB
==> Installing freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.10.1.catalina.bo
==> Downloading from https://akamai.bintray.com/dd/ddd686141a969caec11ea248324e3
######################################################################## 100.0%
==> Pouring freetype-2.10.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.10.1: 61 files, 2.2MB
-bash-3.2$ brew install zlib
==> Downloading https://homebrew.bintray.com/bottles/zlib-1.2.11.catalina.bottle
######################################################################## 100.0%
==> Pouring zlib-1.2.11.catalina.bottle.tar.gz
==> Caveats
zlib is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

For compilers to find zlib you may need to set:
  export LDFLAGS="-L/usr/local/opt/zlib/lib"
  export CPPFLAGS="-I/usr/local/opt/zlib/include"

==> Summary
🍺  /usr/local/Cellar/zlib/1.2.11: 12 files, 376.4KB
-bash-3.2$ 


Hi justdan96 ,

I just did this would this work?

**Comment by justdan96** [comment]
It should do! Can you then try:

```
ls -l /opt/local/lib/*.dylib
```

This should display all the libraries, including `libfreetype.6.dylib`.

**Comment by Liv77** [comment]
Got it it worked :) after I added 2 commands that you've told me. but after I've added this below it said no such files or directory but i guess it doesn't matter , It worked without it. 

Last login: Sun Dec 29 18:30:35 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
-bash-3.2$ ls -l /opt/local/lib/*.dylib
ls: /opt/local/lib/*.dylib: No such file or directory
-bash-3.2$

**Comment by justdan96** [comment]
Perfect, glad I could help!

**Comment by mariustrifan83** [comment]
Install freetype on Mac OSX
1. Press Command+Space and type Terminal and press enter/return key.
2. Run in Terminal app:
    **ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" <      /dev/null 2> /dev/null**
    and press enter/return key. 
    If the screen prompts you to enter a password, please enter your Mac's user password to        continue. When you type the password, it won't be displayed on screen, but the system would     accept it. So just type your password and press ENTER/RETURN key. Then wait for the command to finish.
3. Run:
     brew install freetype
      Done! You can now use freetype.
