### ISSUE TITLE
Warning!  HEVC codec is not standard for BD disks! TSmuxer 2.6.15 on macbook pro

### ISSUE THREAD

**Issue by Liv77** [justdan96/tsMuxer#99]
Hi justdan96,

Im trying now to create UHD blu ray folder from mkv file , mix is successful but its says this
Error: Warning! HEVC codec is not standard for BD disks!. How can i fix this? is this the same in UHD Blu ray ISO?

![TSUMXER 2 6 15](https://user-images.githubusercontent.com/59346428/71564810-b1748d80-2a74-11ea-9f74-53c5dabc657c.png)

**Comment by jcdr428** [comment]
@Liv77 The warning on HEVC should have been removed by enhancement #90 merged yesterday. Could you please try latest build and report, thanks.

**Comment by Liv77** [comment]
I done know what that means try the latest build?

**Comment by jcdr428** [comment]
@Liv77 latest build : https://bintray.com/justdan96/tsMuxer/tsMuxerGUI-Nightly#files
which is currently [lnx|mac|w32|w64]-nightly-2019-12-30--01-10-40.zip

**Comment by Liv77** [comment]
I don't know which one to use since i have mac , is it this one

 mac-nightly-2019-12-30--01-10-40.zip

**Comment by jcdr428** [comment]
@Liv77 yes for Mac it is mac-nightly-2019-12-30--01-10-40.zip .

**Comment by Liv77** [comment]
Yes it worked :) thanks. Are there any other changes or updates or that's the final one?

**Comment by jcdr428** [comment]
@Liv77 There is still a lot of work to be done for tsMuxer to be 100% compliant with UHD BD specs. But it is getting better every week...
@xavery I assume this issue #99 can be closed ;)

**Comment by Liv77** [comment]
Yes thanks :)

**Comment by hjason78121** [comment]
i just used tsmuxer for a uhd and also recieved this error Warning! HEVC codec is not standard for BD disks!
i am using the latest windows version

**Comment by jcdr428** [comment]
@hjason78121 this error has been removed from tsMuxer code five years ago ! Just use the lastest build.

**Comment by hjason78121** [comment]
It is the latest build lol

**Comment by hjason78121** [comment]
> @hjason78121 this error has been removed from tsMuxer code five years ago ! Just use the lastest build.

it most certainly is the latest build that is out.. version i have is 2.6.12 the latest on its github page

**Comment by jcdr428** [comment]
@hjason78121 Releases are in https://github.com/justdan96/tsMuxer/releases . Latest release as of today is 72d4b4e.
